/*
 * Superposition
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2025-03-05
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct CreateTypeTemplatesRequestContent {
    #[serde(rename = "type_name")]
    pub type_name: String,
    #[serde(rename = "type_schema", deserialize_with = "Option::deserialize")]
    pub type_schema: Option<serde_json::Value>,
    #[serde(rename = "description")]
    pub description: String,
    #[serde(rename = "change_reason")]
    pub change_reason: String,
}

impl CreateTypeTemplatesRequestContent {
    pub fn new(type_name: String, type_schema: Option<serde_json::Value>, description: String, change_reason: String) -> CreateTypeTemplatesRequestContent {
        CreateTypeTemplatesRequestContent {
            type_name,
            type_schema,
            description,
            change_reason,
        }
    }
}

