/*
 * Superposition
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2025-03-05
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct ListContextsResponseContent {
    #[serde(rename = "total_pages", skip_serializing_if = "Option::is_none")]
    pub total_pages: Option<f64>,
    #[serde(rename = "total_items", skip_serializing_if = "Option::is_none")]
    pub total_items: Option<f64>,
    #[serde(rename = "data", skip_serializing_if = "Option::is_none")]
    pub data: Option<Vec<models::ContextFull>>,
}

impl ListContextsResponseContent {
    pub fn new() -> ListContextsResponseContent {
        ListContextsResponseContent {
            total_pages: None,
            total_items: None,
            data: None,
        }
    }
}

