/**
 * Application Constants
 * Contains all static configuration data
 */

export const PAYMENT_CONFIG = {
  connectors: [
    "Aci",
    "Adyen",
    "Airwallex",
    "Authipay",
    "Authorizedotnet",
    "Bambora",
    "Bankofamerica",
    "Billwerk",
    "Bluecode",
    "Bluesnap",
    "Boku",
    "Braintree",
    "Checkout",
    "Coinbase",
    "Cryptopay",
    "Cybersource",
    "Datatrans",
    "Deutschebank",
    "Digitalvirgo",
    "Dlocal",
    "Elavon",
    "Facilitapay",
    "Fiserv",
    "Fiuu",
    "Flexiti",
    "Forte",
    "Getnet",
    "Globalpay",
    "Helcim",
    "Hipay",
    "Iatapay",
    "Inespay",
    "Itaubank",
    "Klarna",
    "Mifinity",
    "Mollie",
    "Moneris",
    "Multisafepay",
    "Nexinets",
    "Nexixpay",
    "Nmi",
    "Noon",
    "Novalnet",
    "Nuvei",
    "Paybox",
    "Payload",
    "Payme",
    "Paypal",
    "Paytm",
    "Payu",
    "Phonepe",
    "Powertranz",
    "Rapyd",
    "Razorpay",
    "Redsys",
    "Santander",
    "Shift4",
    "Silverflow",
    "Square",
    "Stax",
    "Stripe",
    "Trustpay",
    "Tsys",
    "Volt",
    "Wellsfargo",
    "Worldline",
    "Worldpay",
    "Worldpayvantiv",
    "Xendit",
    "Zen",
    "Zsl",
  ],

  paymentMethods: [
    "Card",
    "BankRedirect",
    "BankDebit",
    "BankTransfer",
    "CardRedirect",
    "Crypto",
    "GiftCard",
    "MobilePayment",
    "PayLater",
    "Upi",
    "Voucher",
    "Wallet",
  ],

  paymentMethodTypes: [
    "Credit",
    "Debit",
    "OpenBankingUk",
    "Trustly",
    "OnlineBankingCzechRepublic",
    "OnlineBankingFinland",
    "OnlineBankingPoland",
    "OnlineBankingSlovakia",
    "OnlineBankingFpx",
    "OnlineBankingThailand",
    "Bizum",
    "Przelewy24",
    "BancontactCard",
    "Giropay",
    "Ideal",
    "Sofort",
    "Eps",
    "Blik",
    "ApplePay",
    "SamsungPay",
    "GooglePay",
    "WeChatPay",
    "AliPay",
    "AliPayHk",
    "AmazonPay",
    "Cashapp",
    "MbWay",
    "KakaoPay",
    "Twint",
    "Gcash",
    "Vipps",
    "Dana",
    "Momo",
    "Swish",
    "TouchNGo",
    "Paypal",
    "Mifinity",
    "Skrill",
    "AfterpayClearpay",
    "Flexiti",
    "Klarna",
    "Affirm",
    "PayBright",
    "Walley",
    "Alma",
    "Atome",
    "Boleto",
    "Alfamart",
    "Indomaret",
    "Oxxo",
    "SevenEleven",
    "Lawson",
    "MiniStop",
    "FamilyMart",
    "Seicomart",
    "PayEasy",
    "Ach",
    "Sepa",
    "Bacs",
    "Becs",
    "Multibanco",
    "LocalBankTransfer",
    "Pix",
    "PermataBankTransfer",
    "BcaBankTransfer",
    "BniVa",
    "BriVa",
    "CimbVa",
    "DanamonVa",
    "MandiriVa",
    "SepaBankTransfer",
    "InstantBankTransfer",
    "InstantBankTransferFinland",
    "InstantBankTransferPoland",
    "CryptoCurrency",
    "UpiCollect",
    "PaySafeCard",
    "Givex",
    "Benefit",
    "Knet",
    "MomoAtm",
    "DirectCarrierBilling",
  ],

  countries: [
    "AC",
    "AD",
    "AE",
    "AF",
    "AG",
    "AI",
    "AL",
    "AM",
    "AO",
    "AQ",
    "AR",
    "AS",
    "AT",
    "AU",
    "AW",
    "AX",
    "AZ",
    "BA",
    "BB",
    "BD",
    "BE",
    "BF",
    "BG",
    "BH",
    "BI",
    "BJ",
    "BL",
    "BM",
    "BN",
    "BO",
    "BQ",
    "BR",
    "BS",
    "BT",
    "BV",
    "BW",
    "BY",
    "BZ",
    "CA",
    "CC",
    "CD",
    "CF",
    "CG",
    "CH",
    "CI",
    "CK",
    "CL",
    "CM",
    "CN",
    "CO",
    "CR",
    "CU",
    "CV",
    "CW",
    "CX",
    "CY",
    "CZ",
    "DE",
    "DJ",
    "DK",
    "DM",
    "DO",
    "DZ",
    "EC",
    "EE",
    "EG",
    "EH",
    "ER",
    "ES",
    "ET",
    "FI",
    "FJ",
    "FK",
    "FM",
    "FO",
    "FR",
    "GA",
    "GB",
    "GD",
    "GE",
    "GF",
    "GG",
    "GH",
    "GI",
    "GL",
    "GM",
    "GN",
    "GP",
    "GQ",
    "GR",
    "GS",
    "GT",
    "GU",
    "GW",
    "GY",
    "HK",
    "HM",
    "HN",
    "HR",
    "HT",
    "HU",
    "ID",
    "IE",
    "IL",
    "IM",
    "IN",
    "IO",
    "IQ",
    "IR",
    "IS",
    "IT",
    "JE",
    "JM",
    "JO",
    "JP",
    "KE",
    "KG",
    "KH",
    "KI",
    "KM",
    "KN",
    "KP",
    "KR",
    "KW",
    "KY",
    "KZ",
    "LA",
    "LB",
    "LC",
    "LI",
    "LK",
    "LR",
    "LS",
    "LT",
    "LU",
    "LV",
    "LY",
    "MA",
    "MC",
    "MD",
    "ME",
    "MF",
    "MG",
    "MH",
    "MK",
    "ML",
    "MM",
    "MN",
    "MO",
    "MP",
    "MQ",
    "MR",
    "MS",
    "MT",
    "MU",
    "MV",
    "MW",
    "MX",
    "MY",
    "MZ",
    "NA",
    "NC",
    "NE",
    "NF",
    "NG",
    "NI",
    "NL",
    "NO",
    "NP",
    "NR",
    "NU",
    "NZ",
    "OM",
    "PA",
    "PE",
    "PF",
    "PG",
    "PH",
    "PK",
    "PL",
    "PM",
    "PN",
    "PR",
    "PS",
    "PT",
    "PW",
    "PY",
    "QA",
    "RE",
    "RO",
    "RS",
    "RU",
    "RW",
    "SA",
    "SB",
    "SC",
    "SD",
    "SE",
    "SG",
    "SH",
    "SI",
    "SJ",
    "SK",
    "SL",
    "SM",
    "SN",
    "SO",
    "SR",
    "SS",
    "ST",
    "SV",
    "SX",
    "SY",
    "SZ",
    "TA",
    "TC",
    "TD",
    "TF",
    "TG",
    "TH",
    "TJ",
    "TK",
    "TL",
    "TM",
    "TN",
    "TO",
    "TR",
    "TT",
    "TV",
    "TW",
    "TZ",
    "UA",
    "UG",
    "UM",
    "US",
    "UY",
    "UZ",
    "VA",
    "VC",
    "VE",
    "VG",
    "VI",
    "VN",
    "VU",
    "WF",
    "WS",
    "XK",
    "YE",
    "YT",
    "ZA",
    "ZM",
    "ZW",
  ],

  mandateTypes: ["mandate", "non_mandate"],

  collectBillingDetailsFromWalletConnector: ["required", "always"],

  collectShippingDetailsFromWalletConnector: ["required", "always"],
};

export const COMPONENT_CONFIG = {
  icons: {
    card: "💳",
    billing: "📋",
    shipping: "🚚",
    bank: "🏦",
    wallet: "👛",
    crypto: "₿",
    upi: "📱",
    voucher: "🎫",
    gift_card: "🎁",
    mobile_payment: "📲",
    other: "⚙️",
    connector: "🔌",
    payment_method: "💳",
    payment_method_type: "🎯",
    country: "🌍",
    mandate_type: "📋",
    collect_billing_details_from_wallet_connector: "💳",
    collect_shipping_details_from_wallet_connector: "🚚",
  },

  names: {
    card: "Card Information",
    billing: "Billing Address",
    shipping: "Shipping Address",
    bank: "Bank Details",
    wallet: "Wallet Information",
    crypto: "Crypto Details",
    upi: "UPI Information",
    voucher: "Voucher Details",
    gift_card: "Gift Card",
    mobile_payment: "Mobile Payment",
    other: "Additional Information",
  },
};

export const CSS_CLASSES = {
  input:
    "bg-gray-50 border border-gray-300 text-gray-900 text-sm rounded-lg focus:ring-blue-500 focus:border-blue-500 block w-full p-2.5",
  button: {
    primary:
      "px-6 py-2 text-sm font-medium text-white bg-indigo-600 border border-transparent rounded-md hover:bg-indigo-700 focus:outline-none focus:ring-2 focus:ring-offset-2 focus:ring-indigo-500",
    secondary:
      "px-4 py-2 text-sm font-medium text-gray-700 bg-white border border-gray-300 rounded-md hover:bg-gray-50 focus:outline-none focus:ring-2 focus:ring-offset-2 focus:ring-indigo-500",
  },
  contextBadge: "context-badge",
};
