/**
 * Payment Method Mappings
 * Contains connector-specific payment method and type mappings
 */

export const CONNECTOR_PAYMENT_METHODS = {
  Aci: ["Card", "BankRedirect"],
  Adyen: [
    "Card",
    "BankRedirect",
    "Wallet",
    "PayLater",
    "Voucher",
    "BankDebit",
    "BankTransfer",
    "GiftCard",
    "CardRedirect",
  ],
  Airwallex: ["Card", "BankRedirect", "Wallet", "PayLater"],
  Authipay: ["Card"],
  Authorizedotnet: ["Card", "Wallet"],
  Bambora: ["Card"],
  Bankofamerica: ["Card", "Wallet"],
  Billwerk: ["Card"],
  Bluecode: ["BankTransfer"],
  Bluesnap: ["Card", "Wallet"],
  Boku: ["Card"],
  Braintree: ["Card", "Wallet"],
  Checkout: ["Card", "Wallet"],
  Coinbase: ["Card"],
  Cryptopay: ["Crypto"],
  Cybersource: ["Card", "Wallet"],
  Datatrans: ["Card"],
  Deutschebank: ["Card", "BankDebit"],
  Digitalvirgo: ["MobilePayment"],
  Dlocal: ["Card"],
  Elavon: ["Card"],
  Facilitapay: ["BankTransfer"],
  Fiserv: ["Card"],
  Fiuu: ["Card"],
  Flexiti: ["PayLater"],
  Forte: ["Card"],
  Globalpay: ["Card", "BankRedirect", "Wallet"],
  Helcim: ["Card"],
  Hipay: ["Card"],
  Iatapay: ["Card"],
  Inespay: ["BankDebit"],
  Itaubank: ["BankTransfer"],
  Klarna: ["PayLater"],
  Mifinity: ["Wallet"],
  Mollie: ["Card", "BankRedirect"],
  Moneris: ["Card"],
  Multisafepay: ["Card", "Wallet"],
  Nexinets: ["Card", "BankRedirect"],
  Nexixpay: ["Card"],
  Nmi: ["Card"],
  Noon: ["Card", "Wallet"],
  Novalnet: ["Card", "Wallet"],
  Nuvei: ["Card", "BankRedirect", "Wallet"],
  Paybox: ["Card"],
  Payload: ["Card"],
  Payme: ["Card"],
  Paypal: ["Card", "Wallet"],
  Paytm: ["Upi"],
  Payu: ["Card", "Wallet"],
  Phonepe: ["Upi"],
  Powertranz: ["Card"],
  Rapyd: ["Card", "Wallet"],
  Razorpay: ["Upi"],
  Redsys: ["Card"],
  Santander: ["BankTransfer"],
  Shift4: ["Card", "BankRedirect"],
  Silverflow: ["Card"],
  Square: ["Card"],
  Stax: ["Card"],
  Stripe: [
    "Card",
    "BankRedirect",
    "Wallet",
    "PayLater",
    "BankDebit",
    "BankTransfer",
  ],
  Trustpay: ["Card", "BankRedirect", "BankTransfer", "Wallet"],
  Tsys: ["Card"],
  Volt: ["BankRedirect"],
  Wellsfargo: ["Card", "Wallet"],
  Worldline: ["Card"],
  Worldpay: ["Card"],
  Worldpayvantiv: ["Card"],
  Xendit: ["Card"],
  Zen: ["Card", "Voucher"],
  Zsl: ["BankTransfer"],
};

export const CONNECTOR_PAYMENT_METHOD_TYPES = {
  Aci: ["Credit", "Debit", "Giropay", "Ideal", "Sofort", "Eps"],
  Adyen: [
    "Credit",
    "Debit",
    "OpenBankingUk",
    "Trustly",
    "OnlineBankingCzechRepublic",
    "OnlineBankingFinland",
    "OnlineBankingPoland",
    "OnlineBankingSlovakia",
    "OnlineBankingFpx",
    "OnlineBankingThailand",
    "Bizum",
    "BancontactCard",
    "Giropay",
    "Ideal",
    "Sofort",
    "Eps",
    "Blik",
    "ApplePay",
    "GooglePay",
    "WeChatPay",
    "AliPay",
    "AliPayHk",
    "MbWay",
    "KakaoPay",
    "Twint",
    "Gcash",
    "Vipps",
    "Dana",
    "Momo",
    "Swish",
    "TouchNGo",
    "Paypal",
    "AfterpayClearpay",
    "Klarna",
    "Affirm",
    "PayBright",
    "Walley",
    "Alma",
    "Atome",
    "Boleto",
    "Alfamart",
    "Indomaret",
    "Oxxo",
    "SevenEleven",
    "Lawson",
    "MiniStop",
    "FamilyMart",
    "Seicomart",
    "PayEasy",
    "Ach",
    "Sepa",
    "Bacs",
    "Becs",
    "Pix",
    "PermataBankTransfer",
    "BcaBankTransfer",
    "BniVa",
    "BriVa",
    "CimbVa",
    "DanamonVa",
    "MandiriVa",
    "PaySafeCard",
    "Givex",
    "Benefit",
    "Knet",
    "MomoAtm",
  ],
  Stripe: [
    "Credit",
    "Debit",
    "Przelewy24",
    "BancontactCard",
    "Giropay",
    "Ideal",
    "Sofort",
    "Eps",
    "Blik",
    "ApplePay",
    "GooglePay",
    "WeChatPay",
    "AliPay",
    "AmazonPay",
    "Cashapp",
    "AfterpayClearpay",
    "Klarna",
    "Affirm",
    "Ach",
    "Sepa",
    "Bacs",
    "Becs",
    "Multibanco",
    "SepaBankTransfer",
  ],
  Bankofamerica: ["Credit", "Debit", "ApplePay", "GooglePay"],
  Bluesnap: ["Credit", "Debit", "GooglePay"],
  Checkout: ["Credit", "Debit", "GooglePay"],
  Cybersource: ["Credit", "Debit", "ApplePay", "SamsungPay", "GooglePay"],
  Globalpay: [
    "Credit",
    "Debit",
    "Giropay",
    "Ideal",
    "Sofort",
    "Eps",
    "GooglePay",
  ],
  Klarna: ["Klarna"],
  Mollie: [
    "Credit",
    "Debit",
    "BancontactCard",
    "Giropay",
    "Ideal",
    "Sofort",
    "Eps",
  ],
  Multisafepay: ["Credit", "Debit", "GooglePay"],
  Nexinets: ["Credit", "Debit", "Ideal", "Sofort"],
  Noon: ["Credit", "Debit", "GooglePay"],
  Novalnet: ["Credit", "Debit", "ApplePay", "GooglePay", "Paypal"],
  Nuvei: ["Credit", "Debit", "Giropay", "Ideal", "Sofort", "Eps", "GooglePay"],
  Paypal: ["Credit", "Debit", "Giropay", "Ideal", "Sofort", "Eps", "Paypal"],
  Payu: ["Credit", "Debit", "GooglePay"],
  Rapyd: ["Credit", "Debit", "GooglePay"],
  Shift4: ["Credit", "Debit", "Giropay", "Ideal", "Sofort", "Eps"],
  Trustpay: [
    "Credit",
    "Debit",
    "Giropay",
    "Ideal",
    "Sofort",
    "Eps",
    "Blik",
    "GooglePay",
    "SepaBankTransfer",
    "InstantBankTransfer",
    "InstantBankTransferFinland",
    "InstantBankTransferPoland",
  ],
  Wellsfargo: ["Credit", "Debit", "ApplePay", "GooglePay"],
  Worldline: ["Credit", "Debit"],
  Worldpay: ["Credit", "Debit"],
  Zen: ["Credit", "Debit", "Boleto"],
  Volt: ["OpenBankingUk"],
  Airwallex: [
    "Trustly",
    "Blik",
    "GooglePay",
    "Paypal",
    "Skrill",
    "Klarna",
    "Atome",
  ],
  Authorizedotnet: ["GooglePay"],
  Braintree: ["Paypal"],
  Mifinity: ["Mifinity"],
  Flexiti: ["Flexiti"],
  Cryptopay: ["CryptoCurrency"],
  Razorpay: ["UpiCollect"],
  Phonepe: ["UpiCollect"],
  Paytm: ["UpiCollect"],
  Deutschebank: ["Sepa"],
  Inespay: ["Sepa"],
  Zsl: ["LocalBankTransfer"],
  Itaubank: ["Pix"],
  Santander: ["Pix"],
  Bluecode: ["Pix"],
  Facilitapay: ["Pix"],
  Digitalvirgo: ["DirectCarrierBilling"],
};

export const PAYMENT_METHOD_TYPES = {
  Card: ["Credit", "Debit"],
  BankRedirect: [
    "OpenBankingUk",
    "Trustly",
    "OnlineBankingCzechRepublic",
    "OnlineBankingFinland",
    "OnlineBankingPoland",
    "OnlineBankingSlovakia",
    "OnlineBankingFpx",
    "OnlineBankingThailand",
    "Bizum",
    "Przelewy24",
    "BancontactCard",
    "Giropay",
    "Ideal",
    "Sofort",
    "Eps",
    "Blik",
  ],
  Wallet: [
    "ApplePay",
    "SamsungPay",
    "GooglePay",
    "WeChatPay",
    "AliPay",
    "AliPayHk",
    "AmazonPay",
    "Cashapp",
    "MbWay",
    "KakaoPay",
    "Twint",
    "Gcash",
    "Vipps",
    "Dana",
    "Momo",
    "Swish",
    "TouchNGo",
    "Paypal",
    "Mifinity",
    "Skrill",
  ],
  PayLater: [
    "AfterpayClearpay",
    "Flexiti",
    "Klarna",
    "Affirm",
    "PayBright",
    "Walley",
    "Alma",
    "Atome",
  ],
  Crypto: ["CryptoCurrency"],
  Voucher: [
    "Boleto",
    "Alfamart",
    "Indomaret",
    "Oxxo",
    "SevenEleven",
    "Lawson",
    "MiniStop",
    "FamilyMart",
    "Seicomart",
    "PayEasy",
  ],
  Upi: ["UpiCollect"],
  BankDebit: ["Ach", "Sepa", "Bacs", "Becs"],
  BankTransfer: [
    "Multibanco",
    "LocalBankTransfer",
    "Ach",
    "Pix",
    "PermataBankTransfer",
    "BcaBankTransfer",
    "BniVa",
    "BriVa",
    "CimbVa",
    "DanamonVa",
    "MandiriVa",
    "SepaBankTransfer",
    "InstantBankTransfer",
    "InstantBankTransferFinland",
    "InstantBankTransferPoland",
    "Bacs",
  ],
  GiftCard: ["PaySafeCard", "Givex"],
  CardRedirect: ["Benefit", "Knet", "MomoAtm"],
  MobilePayment: ["DirectCarrierBilling"],
};

export const CRYPTO_NETWORK_MAPPING = {
  BTC: ["bitcoin", "bnb_smart_chain"],
  LTC: ["litecoin", "bnb_smart_chain"],
  ETH: ["ethereum", "bnb_smart_chain"],
  XRP: ["ripple", "bnb_smart_chain"],
  XLM: ["stellar", "bnb_smart_chain"],
  BCH: ["bitcoin_cash", "bnb_smart_chain"],
  ADA: ["cardano", "bnb_smart_chain"],
  SOL: ["solana", "bnb_smart_chain"],
  SHIB: ["ethereum", "bnb_smart_chain"],
  TRX: ["tron", "bnb_smart_chain"],
  DOGE: ["dogecoin", "bnb_smart_chain"],
  BNB: ["bnb_smart_chain"],
  USDT: ["ethereum", "tron", "bnb_smart_chain"],
  USDC: ["ethereum", "tron", "bnb_smart_chain"],
  DAI: ["ethereum", "bnb_smart_chain"],
};
