// Code generated by software.amazon.smithy.rust.codegen.smithy-rs. DO NOT EDIT.
#[allow(missing_docs)] // documentation missing in model
#[non_exhaustive]
#[derive(::std::clone::Clone, ::std::cmp::PartialEq, ::std::fmt::Debug)]
pub struct ListAuditLogsInput  {
    #[allow(missing_docs)] // documentation missing in model
    pub workspace_id: ::std::option::Option<::std::string::String>,
    #[allow(missing_docs)] // documentation missing in model
    pub org_id: ::std::option::Option<::std::string::String>,
    /// Number of items to be returned in each page.
    pub count: ::std::option::Option<i32>,
    /// Page number to retrieve, starting from 1.
    pub page: ::std::option::Option<i32>,
    /// If true, returns all requested items, ignoring pagination parameters page and count.
    pub all: ::std::option::Option<bool>,
    #[allow(missing_docs)] // documentation missing in model
    pub from_date: ::std::option::Option<::aws_smithy_types::DateTime>,
    #[allow(missing_docs)] // documentation missing in model
    pub to_date: ::std::option::Option<::aws_smithy_types::DateTime>,
    #[allow(missing_docs)] // documentation missing in model
    pub tables: ::std::option::Option<::std::vec::Vec::<::std::string::String>>,
    #[allow(missing_docs)] // documentation missing in model
    pub action: ::std::option::Option<::std::vec::Vec::<crate::types::AuditAction>>,
    #[allow(missing_docs)] // documentation missing in model
    pub username: ::std::option::Option<::std::string::String>,
    /// Sort order enumeration for list operations.
    pub sort_by: ::std::option::Option<crate::types::SortBy>,
}
impl  ListAuditLogsInput  {
    #[allow(missing_docs)] // documentation missing in model
    pub fn workspace_id(&self) -> ::std::option::Option<&str> {
        self.workspace_id.as_deref()
    }
    #[allow(missing_docs)] // documentation missing in model
    pub fn org_id(&self) -> ::std::option::Option<&str> {
        self.org_id.as_deref()
    }
    /// Number of items to be returned in each page.
    pub fn count(&self) -> ::std::option::Option<i32> {
        self.count
    }
    /// Page number to retrieve, starting from 1.
    pub fn page(&self) -> ::std::option::Option<i32> {
        self.page
    }
    /// If true, returns all requested items, ignoring pagination parameters page and count.
    pub fn all(&self) -> ::std::option::Option<bool> {
        self.all
    }
    #[allow(missing_docs)] // documentation missing in model
    pub fn from_date(&self) -> ::std::option::Option<&::aws_smithy_types::DateTime> {
        self.from_date.as_ref()
    }
    #[allow(missing_docs)] // documentation missing in model
    pub fn to_date(&self) -> ::std::option::Option<&::aws_smithy_types::DateTime> {
        self.to_date.as_ref()
    }
    #[allow(missing_docs)] // documentation missing in model
    /// 
    /// If no value was sent for this field, a default will be set. If you want to determine if no value was sent, use `.tables.is_none()`.
    pub fn tables(&self) -> &[::std::string::String] {
        self.tables.as_deref()
        .unwrap_or_default()
    }
    #[allow(missing_docs)] // documentation missing in model
    /// 
    /// If no value was sent for this field, a default will be set. If you want to determine if no value was sent, use `.action.is_none()`.
    pub fn action(&self) -> &[crate::types::AuditAction] {
        self.action.as_deref()
        .unwrap_or_default()
    }
    #[allow(missing_docs)] // documentation missing in model
    pub fn username(&self) -> ::std::option::Option<&str> {
        self.username.as_deref()
    }
    /// Sort order enumeration for list operations.
    pub fn sort_by(&self) -> ::std::option::Option<&crate::types::SortBy> {
        self.sort_by.as_ref()
    }
}
impl ListAuditLogsInput {
    /// Creates a new builder-style object to manufacture [`ListAuditLogsInput`](crate::operation::list_audit_logs::ListAuditLogsInput).
    pub fn builder() -> crate::operation::list_audit_logs::builders::ListAuditLogsInputBuilder {
        crate::operation::list_audit_logs::builders::ListAuditLogsInputBuilder::default()
    }
}

/// A builder for [`ListAuditLogsInput`](crate::operation::list_audit_logs::ListAuditLogsInput).
#[derive(::std::clone::Clone, ::std::cmp::PartialEq, ::std::default::Default, ::std::fmt::Debug)]
#[non_exhaustive]
pub struct ListAuditLogsInputBuilder {
    pub(crate) workspace_id: ::std::option::Option<::std::string::String>,
    pub(crate) org_id: ::std::option::Option<::std::string::String>,
    pub(crate) count: ::std::option::Option<i32>,
    pub(crate) page: ::std::option::Option<i32>,
    pub(crate) all: ::std::option::Option<bool>,
    pub(crate) from_date: ::std::option::Option<::aws_smithy_types::DateTime>,
    pub(crate) to_date: ::std::option::Option<::aws_smithy_types::DateTime>,
    pub(crate) tables: ::std::option::Option<::std::vec::Vec::<::std::string::String>>,
    pub(crate) action: ::std::option::Option<::std::vec::Vec::<crate::types::AuditAction>>,
    pub(crate) username: ::std::option::Option<::std::string::String>,
    pub(crate) sort_by: ::std::option::Option<crate::types::SortBy>,
}
impl ListAuditLogsInputBuilder {
    #[allow(missing_docs)] // documentation missing in model
    /// This field is required.
    pub fn workspace_id(mut self, input: impl ::std::convert::Into<::std::string::String>) -> Self {
        self.workspace_id = ::std::option::Option::Some(input.into());
        self
    }
    #[allow(missing_docs)] // documentation missing in model
    pub fn set_workspace_id(mut self, input: ::std::option::Option<::std::string::String>) -> Self {
        self.workspace_id = input; self
    }
    #[allow(missing_docs)] // documentation missing in model
    pub fn get_workspace_id(&self) -> &::std::option::Option<::std::string::String> {
        &self.workspace_id
    }
    #[allow(missing_docs)] // documentation missing in model
    /// This field is required.
    pub fn org_id(mut self, input: impl ::std::convert::Into<::std::string::String>) -> Self {
        self.org_id = ::std::option::Option::Some(input.into());
        self
    }
    #[allow(missing_docs)] // documentation missing in model
    pub fn set_org_id(mut self, input: ::std::option::Option<::std::string::String>) -> Self {
        self.org_id = input; self
    }
    #[allow(missing_docs)] // documentation missing in model
    pub fn get_org_id(&self) -> &::std::option::Option<::std::string::String> {
        &self.org_id
    }
    /// Number of items to be returned in each page.
    pub fn count(mut self, input: i32) -> Self {
        self.count = ::std::option::Option::Some(input);
        self
    }
    /// Number of items to be returned in each page.
    pub fn set_count(mut self, input: ::std::option::Option<i32>) -> Self {
        self.count = input; self
    }
    /// Number of items to be returned in each page.
    pub fn get_count(&self) -> &::std::option::Option<i32> {
        &self.count
    }
    /// Page number to retrieve, starting from 1.
    pub fn page(mut self, input: i32) -> Self {
        self.page = ::std::option::Option::Some(input);
        self
    }
    /// Page number to retrieve, starting from 1.
    pub fn set_page(mut self, input: ::std::option::Option<i32>) -> Self {
        self.page = input; self
    }
    /// Page number to retrieve, starting from 1.
    pub fn get_page(&self) -> &::std::option::Option<i32> {
        &self.page
    }
    /// If true, returns all requested items, ignoring pagination parameters page and count.
    pub fn all(mut self, input: bool) -> Self {
        self.all = ::std::option::Option::Some(input);
        self
    }
    /// If true, returns all requested items, ignoring pagination parameters page and count.
    pub fn set_all(mut self, input: ::std::option::Option<bool>) -> Self {
        self.all = input; self
    }
    /// If true, returns all requested items, ignoring pagination parameters page and count.
    pub fn get_all(&self) -> &::std::option::Option<bool> {
        &self.all
    }
    #[allow(missing_docs)] // documentation missing in model
    pub fn from_date(mut self, input: ::aws_smithy_types::DateTime) -> Self {
        self.from_date = ::std::option::Option::Some(input);
        self
    }
    #[allow(missing_docs)] // documentation missing in model
    pub fn set_from_date(mut self, input: ::std::option::Option<::aws_smithy_types::DateTime>) -> Self {
        self.from_date = input; self
    }
    #[allow(missing_docs)] // documentation missing in model
    pub fn get_from_date(&self) -> &::std::option::Option<::aws_smithy_types::DateTime> {
        &self.from_date
    }
    #[allow(missing_docs)] // documentation missing in model
    pub fn to_date(mut self, input: ::aws_smithy_types::DateTime) -> Self {
        self.to_date = ::std::option::Option::Some(input);
        self
    }
    #[allow(missing_docs)] // documentation missing in model
    pub fn set_to_date(mut self, input: ::std::option::Option<::aws_smithy_types::DateTime>) -> Self {
        self.to_date = input; self
    }
    #[allow(missing_docs)] // documentation missing in model
    pub fn get_to_date(&self) -> &::std::option::Option<::aws_smithy_types::DateTime> {
        &self.to_date
    }
    /// Appends an item to `tables`.
    ///
    /// To override the contents of this collection use [`set_tables`](Self::set_tables).
    ///
    pub fn tables(mut self, input: impl ::std::convert::Into<::std::string::String>) -> Self {
        let mut v = self.tables.unwrap_or_default();
                        v.push(input.into());
                        self.tables = ::std::option::Option::Some(v);
                        self
    }
    #[allow(missing_docs)] // documentation missing in model
    pub fn set_tables(mut self, input: ::std::option::Option<::std::vec::Vec::<::std::string::String>>) -> Self {
        self.tables = input; self
    }
    #[allow(missing_docs)] // documentation missing in model
    pub fn get_tables(&self) -> &::std::option::Option<::std::vec::Vec::<::std::string::String>> {
        &self.tables
    }
    /// Appends an item to `action`.
    ///
    /// To override the contents of this collection use [`set_action`](Self::set_action).
    ///
    pub fn action(mut self, input: crate::types::AuditAction) -> Self {
        let mut v = self.action.unwrap_or_default();
                        v.push(input);
                        self.action = ::std::option::Option::Some(v);
                        self
    }
    #[allow(missing_docs)] // documentation missing in model
    pub fn set_action(mut self, input: ::std::option::Option<::std::vec::Vec::<crate::types::AuditAction>>) -> Self {
        self.action = input; self
    }
    #[allow(missing_docs)] // documentation missing in model
    pub fn get_action(&self) -> &::std::option::Option<::std::vec::Vec::<crate::types::AuditAction>> {
        &self.action
    }
    #[allow(missing_docs)] // documentation missing in model
    pub fn username(mut self, input: impl ::std::convert::Into<::std::string::String>) -> Self {
        self.username = ::std::option::Option::Some(input.into());
        self
    }
    #[allow(missing_docs)] // documentation missing in model
    pub fn set_username(mut self, input: ::std::option::Option<::std::string::String>) -> Self {
        self.username = input; self
    }
    #[allow(missing_docs)] // documentation missing in model
    pub fn get_username(&self) -> &::std::option::Option<::std::string::String> {
        &self.username
    }
    /// Sort order enumeration for list operations.
    pub fn sort_by(mut self, input: crate::types::SortBy) -> Self {
        self.sort_by = ::std::option::Option::Some(input);
        self
    }
    /// Sort order enumeration for list operations.
    pub fn set_sort_by(mut self, input: ::std::option::Option<crate::types::SortBy>) -> Self {
        self.sort_by = input; self
    }
    /// Sort order enumeration for list operations.
    pub fn get_sort_by(&self) -> &::std::option::Option<crate::types::SortBy> {
        &self.sort_by
    }
    /// Consumes the builder and constructs a [`ListAuditLogsInput`](crate::operation::list_audit_logs::ListAuditLogsInput).
    pub fn build(self) -> ::std::result::Result<crate::operation::list_audit_logs::ListAuditLogsInput, ::aws_smithy_types::error::operation::BuildError> {
        ::std::result::Result::Ok(
            crate::operation::list_audit_logs::ListAuditLogsInput {
                workspace_id: self.workspace_id
                ,
                org_id: self.org_id
                ,
                count: self.count
                ,
                page: self.page
                ,
                all: self.all
                ,
                from_date: self.from_date
                ,
                to_date: self.to_date
                ,
                tables: self.tables
                ,
                action: self.action
                ,
                username: self.username
                ,
                sort_by: self.sort_by
                ,
            }
        )
    }
}

