// Code generated by software.amazon.smithy.rust.codegen.smithy-rs. DO NOT EDIT.
#[allow(missing_docs)] // documentation missing in model
#[non_exhaustive]
#[derive(::std::clone::Clone, ::std::cmp::PartialEq, ::std::fmt::Debug)]
pub struct ListAuditLogsOutput  {
    #[allow(missing_docs)] // documentation missing in model
    pub total_pages: i32,
    #[allow(missing_docs)] // documentation missing in model
    pub total_items: i32,
    #[allow(missing_docs)] // documentation missing in model
    pub data: ::std::vec::Vec::<crate::types::AuditLogFull>,
}
impl  ListAuditLogsOutput  {
    #[allow(missing_docs)] // documentation missing in model
    pub fn total_pages(&self) -> i32 {
        self.total_pages
    }
    #[allow(missing_docs)] // documentation missing in model
    pub fn total_items(&self) -> i32 {
        self.total_items
    }
    #[allow(missing_docs)] // documentation missing in model
    pub fn data(&self) -> &[crate::types::AuditLogFull] {
        use std::ops::Deref; self.data.deref()
    }
}
impl ListAuditLogsOutput {
    /// Creates a new builder-style object to manufacture [`ListAuditLogsOutput`](crate::operation::list_audit_logs::ListAuditLogsOutput).
    pub fn builder() -> crate::operation::list_audit_logs::builders::ListAuditLogsOutputBuilder {
        crate::operation::list_audit_logs::builders::ListAuditLogsOutputBuilder::default()
    }
}

/// A builder for [`ListAuditLogsOutput`](crate::operation::list_audit_logs::ListAuditLogsOutput).
#[derive(::std::clone::Clone, ::std::cmp::PartialEq, ::std::default::Default, ::std::fmt::Debug)]
#[non_exhaustive]
pub struct ListAuditLogsOutputBuilder {
    pub(crate) total_pages: ::std::option::Option<i32>,
    pub(crate) total_items: ::std::option::Option<i32>,
    pub(crate) data: ::std::option::Option<::std::vec::Vec::<crate::types::AuditLogFull>>,
}
impl ListAuditLogsOutputBuilder {
    #[allow(missing_docs)] // documentation missing in model
    /// This field is required.
    pub fn total_pages(mut self, input: i32) -> Self {
        self.total_pages = ::std::option::Option::Some(input);
        self
    }
    #[allow(missing_docs)] // documentation missing in model
    pub fn set_total_pages(mut self, input: ::std::option::Option<i32>) -> Self {
        self.total_pages = input; self
    }
    #[allow(missing_docs)] // documentation missing in model
    pub fn get_total_pages(&self) -> &::std::option::Option<i32> {
        &self.total_pages
    }
    #[allow(missing_docs)] // documentation missing in model
    /// This field is required.
    pub fn total_items(mut self, input: i32) -> Self {
        self.total_items = ::std::option::Option::Some(input);
        self
    }
    #[allow(missing_docs)] // documentation missing in model
    pub fn set_total_items(mut self, input: ::std::option::Option<i32>) -> Self {
        self.total_items = input; self
    }
    #[allow(missing_docs)] // documentation missing in model
    pub fn get_total_items(&self) -> &::std::option::Option<i32> {
        &self.total_items
    }
    /// Appends an item to `data`.
    ///
    /// To override the contents of this collection use [`set_data`](Self::set_data).
    ///
    pub fn data(mut self, input: crate::types::AuditLogFull) -> Self {
        let mut v = self.data.unwrap_or_default();
                        v.push(input);
                        self.data = ::std::option::Option::Some(v);
                        self
    }
    #[allow(missing_docs)] // documentation missing in model
    pub fn set_data(mut self, input: ::std::option::Option<::std::vec::Vec::<crate::types::AuditLogFull>>) -> Self {
        self.data = input; self
    }
    #[allow(missing_docs)] // documentation missing in model
    pub fn get_data(&self) -> &::std::option::Option<::std::vec::Vec::<crate::types::AuditLogFull>> {
        &self.data
    }
    /// Consumes the builder and constructs a [`ListAuditLogsOutput`](crate::operation::list_audit_logs::ListAuditLogsOutput).
    /// This method will fail if any of the following fields are not set:
    /// - [`total_pages`](crate::operation::list_audit_logs::builders::ListAuditLogsOutputBuilder::total_pages)
    /// - [`total_items`](crate::operation::list_audit_logs::builders::ListAuditLogsOutputBuilder::total_items)
    /// - [`data`](crate::operation::list_audit_logs::builders::ListAuditLogsOutputBuilder::data)
    pub fn build(self) -> ::std::result::Result<crate::operation::list_audit_logs::ListAuditLogsOutput, ::aws_smithy_types::error::operation::BuildError> {
        ::std::result::Result::Ok(
            crate::operation::list_audit_logs::ListAuditLogsOutput {
                total_pages: self.total_pages
                    .ok_or_else(||
                        ::aws_smithy_types::error::operation::BuildError::missing_field("total_pages", "total_pages was not specified but it is required when building ListAuditLogsOutput")
                    )?
                ,
                total_items: self.total_items
                    .ok_or_else(||
                        ::aws_smithy_types::error::operation::BuildError::missing_field("total_items", "total_items was not specified but it is required when building ListAuditLogsOutput")
                    )?
                ,
                data: self.data
                    .ok_or_else(||
                        ::aws_smithy_types::error::operation::BuildError::missing_field("data", "data was not specified but it is required when building ListAuditLogsOutput")
                    )?
                ,
            }
        )
    }
}

