[default-config]
mandatory_dimensions = { "value" = [
], "schema" = { "type" = "array", "items" = { "type" = "number" } } }
experiments_webhook_config = { "value" = { "enabled" = false }, "schema" = { "type" = "object", "properties" = { "enabled" = { "type" = "boolean" }, "configuration" = { "type" = "object", "properties" = { "url" = { "type" = "string" }, "method" = { "enum" = [
    "Post",
    "Get",
], "type" = "string" }, "headers" = { "type" = "array", "items" = { "type" = "string", "enum" = [
    "ConfigVersion",
] } }, "authorization" = { "type" = "object", "properties" = { "key" = { "type" = "string" }, "value" = { "type" = "string" } }, "required" = [
    "key",
    "value",
] }, "required" = [
    "url",
    "method",
    "headers",
    "authorization",
], "additionalProperties" = false } } }, "required" = [
    "enabled",
] } }

[dimensions]
tenant = { schema = { "type" = "string", "enum" = ["test", "dev"] } }

[context."$tenant == 'dev'"]
mandatory_dimensions = []
experiments_webhook_config = { "enabled" = false, "configuration" = { "url" = "http://localhost:8080/config/test", "method" = "Get", "headers" = [
    "ConfigVersion",
], "authorization" = { key = "Authorization", value = "TOKEN_FOR_WEBHOOK" } } }
