[package]
name = "superposition-local-provider"
edition = "2024"

[dependencies]
superposition_provider = { path = "../../crates/superposition_provider/" }
open-feature = "0.2"
tokio = { version = "1.0", features = ["full"] }
env_logger = "0.10"
clap = { version = "4.0", features = ["derive"] }
chrono = { version = "0.4", features = ["serde"] }
toml = "0.8"

[workspace]
