[package]
name = "superposition-local-provider"
edition = "2024"

[dependencies]
superposition_provider = { path = "../../crates/superposition_provider/" }
open-feature = "0.2"
tokio = { version = "1.0", features = ["full"] }
env_logger = "0.10"

[workspace]
