// Code generated by software.amazon.smithy.rust.codegen.smithy-rs. DO NOT EDIT.
pub use crate::operation::list_grouped_default_configs::_list_grouped_default_configs_output::ListGroupedDefaultConfigsOutputBuilder;

pub use crate::operation::list_grouped_default_configs::_list_grouped_default_configs_input::ListGroupedDefaultConfigsInputBuilder;

impl crate::operation::list_grouped_default_configs::builders::ListGroupedDefaultConfigsInputBuilder {
                    /// Sends a request with this input using the given client.
                    pub async fn send_with(self, client: &crate::Client) -> ::std::result::Result<
                        crate::operation::list_grouped_default_configs::ListGroupedDefaultConfigsOutput,
                        ::aws_smithy_runtime_api::client::result::SdkError<
                            crate::operation::list_grouped_default_configs::ListGroupedDefaultConfigsError,
                            ::aws_smithy_runtime_api::client::orchestrator::HttpResponse
                        >
                    > {
                        let mut fluent_builder = client.list_grouped_default_configs();
                        fluent_builder.inner = self;
                        fluent_builder.send().await
                    }
                }
/// Fluent builder constructing a request to `ListGroupedDefaultConfigs`.
/// 
/// Retrieves a paginated list of all default config entries in the workspace, including their values, schemas, and metadata.
#[derive(::std::clone::Clone, ::std::fmt::Debug)]
pub struct ListGroupedDefaultConfigsFluentBuilder {
                handle: ::std::sync::Arc<crate::client::Handle>,
                inner: crate::operation::list_grouped_default_configs::builders::ListGroupedDefaultConfigsInputBuilder,
config_override: ::std::option::Option<crate::config::Builder>,
            }
impl
                crate::client::customize::internal::CustomizableSend<
                    crate::operation::list_grouped_default_configs::ListGroupedDefaultConfigsOutput,
                    crate::operation::list_grouped_default_configs::ListGroupedDefaultConfigsError,
                > for ListGroupedDefaultConfigsFluentBuilder
            {
                fn send(
                    self,
                    config_override: crate::config::Builder,
                ) -> crate::client::customize::internal::BoxFuture<
                    crate::client::customize::internal::SendResult<
                        crate::operation::list_grouped_default_configs::ListGroupedDefaultConfigsOutput,
                        crate::operation::list_grouped_default_configs::ListGroupedDefaultConfigsError,
                    >,
                > {
                    ::std::boxed::Box::pin(async move { self.config_override(config_override).send().await })
                }
            }
impl ListGroupedDefaultConfigsFluentBuilder {
    /// Creates a new `ListGroupedDefaultConfigsFluentBuilder`.
                    pub(crate) fn new(handle: ::std::sync::Arc<crate::client::Handle>) -> Self {
                        Self {
                            handle,
                            inner: ::std::default::Default::default(),
    config_override: ::std::option::Option::None,
                        }
                    }
    /// Access the ListGroupedDefaultConfigs as a reference.
                    pub fn as_input(&self) -> &crate::operation::list_grouped_default_configs::builders::ListGroupedDefaultConfigsInputBuilder {
                        &self.inner
                    }
    /// Sends the request and returns the response.
                    ///
                    /// If an error occurs, an `SdkError` will be returned with additional details that
                    /// can be matched against.
                    ///
                    /// By default, any retryable failures will be retried twice. Retry behavior
                    /// is configurable with the [RetryConfig](aws_smithy_types::retry::RetryConfig), which can be
                    /// set when configuring the client.
                    pub async fn send(self) -> ::std::result::Result<crate::operation::list_grouped_default_configs::ListGroupedDefaultConfigsOutput, ::aws_smithy_runtime_api::client::result::SdkError<crate::operation::list_grouped_default_configs::ListGroupedDefaultConfigsError, ::aws_smithy_runtime_api::client::orchestrator::HttpResponse>> {
                        let input = self.inner.build().map_err(::aws_smithy_runtime_api::client::result::SdkError::construction_failure)?;
                        let runtime_plugins = crate::operation::list_grouped_default_configs::ListGroupedDefaultConfigs::operation_runtime_plugins(
                            self.handle.runtime_plugins.clone(),
                            &self.handle.conf,
                            self.config_override,
                        );
                        crate::operation::list_grouped_default_configs::ListGroupedDefaultConfigs::orchestrate(&runtime_plugins, input).await
                    }
    
                    /// Consumes this builder, creating a customizable operation that can be modified before being sent.
                    pub fn customize(
                        self,
                    ) -> crate::client::customize::CustomizableOperation<crate::operation::list_grouped_default_configs::ListGroupedDefaultConfigsOutput, crate::operation::list_grouped_default_configs::ListGroupedDefaultConfigsError, Self> {
                        crate::client::customize::CustomizableOperation::new(self)
                    }
    pub(crate) fn config_override(
                            mut self,
                            config_override: impl ::std::convert::Into<crate::config::Builder>,
                        ) -> Self {
                            self.set_config_override(::std::option::Option::Some(config_override.into()));
                            self
                        }
    
                        pub(crate) fn set_config_override(
                            &mut self,
                            config_override: ::std::option::Option<crate::config::Builder>,
                        ) -> &mut Self {
                            self.config_override = config_override;
                            self
                        }
    #[allow(missing_docs)] // documentation missing in model
    pub fn workspace_id(mut self, input: impl ::std::convert::Into<::std::string::String>) -> Self {
                    self.inner = self.inner.workspace_id(input.into());
                    self
                }
    #[allow(missing_docs)] // documentation missing in model
    pub fn set_workspace_id(mut self, input: ::std::option::Option<::std::string::String>) -> Self {
                    self.inner = self.inner.set_workspace_id(input);
                    self
                }
    #[allow(missing_docs)] // documentation missing in model
    pub fn get_workspace_id(&self) -> &::std::option::Option<::std::string::String> {
                    self.inner.get_workspace_id()
                }
    #[allow(missing_docs)] // documentation missing in model
    pub fn org_id(mut self, input: impl ::std::convert::Into<::std::string::String>) -> Self {
                    self.inner = self.inner.org_id(input.into());
                    self
                }
    #[allow(missing_docs)] // documentation missing in model
    pub fn set_org_id(mut self, input: ::std::option::Option<::std::string::String>) -> Self {
                    self.inner = self.inner.set_org_id(input);
                    self
                }
    #[allow(missing_docs)] // documentation missing in model
    pub fn get_org_id(&self) -> &::std::option::Option<::std::string::String> {
                    self.inner.get_org_id()
                }
    /// Number of items to be returned in each page.
    pub fn count(mut self, input: i32) -> Self {
                    self.inner = self.inner.count(input);
                    self
                }
    /// Number of items to be returned in each page.
    pub fn set_count(mut self, input: ::std::option::Option<i32>) -> Self {
                    self.inner = self.inner.set_count(input);
                    self
                }
    /// Number of items to be returned in each page.
    pub fn get_count(&self) -> &::std::option::Option<i32> {
                    self.inner.get_count()
                }
    /// Page number to retrieve, starting from 1.
    pub fn page(mut self, input: i32) -> Self {
                    self.inner = self.inner.page(input);
                    self
                }
    /// Page number to retrieve, starting from 1.
    pub fn set_page(mut self, input: ::std::option::Option<i32>) -> Self {
                    self.inner = self.inner.set_page(input);
                    self
                }
    /// Page number to retrieve, starting from 1.
    pub fn get_page(&self) -> &::std::option::Option<i32> {
                    self.inner.get_page()
                }
    /// If true, returns all requested items, ignoring pagination parameters page and count.
    pub fn all(mut self, input: bool) -> Self {
                    self.inner = self.inner.all(input);
                    self
                }
    /// If true, returns all requested items, ignoring pagination parameters page and count.
    pub fn set_all(mut self, input: ::std::option::Option<bool>) -> Self {
                    self.inner = self.inner.set_all(input);
                    self
                }
    /// If true, returns all requested items, ignoring pagination parameters page and count.
    pub fn get_all(&self) -> &::std::option::Option<bool> {
                    self.inner.get_all()
                }
    /// 
    /// Appends an item to `name`.
    /// 
    /// To override the contents of this collection use [`set_name`](Self::set_name).
    /// 
    #[allow(missing_docs)] // documentation missing in model
    pub fn name(mut self, input: impl ::std::convert::Into<::std::string::String>) -> Self {
                        self.inner = self.inner.name(input.into());
                        self
                    }
    #[allow(missing_docs)] // documentation missing in model
    pub fn set_name(mut self, input: ::std::option::Option<::std::vec::Vec::<::std::string::String>>) -> Self {
                    self.inner = self.inner.set_name(input);
                    self
                }
    #[allow(missing_docs)] // documentation missing in model
    pub fn get_name(&self) -> &::std::option::Option<::std::vec::Vec::<::std::string::String>> {
                    self.inner.get_name()
                }
    #[allow(missing_docs)] // documentation missing in model
    pub fn prefix(mut self, input: impl ::std::convert::Into<::std::string::String>) -> Self {
                    self.inner = self.inner.prefix(input.into());
                    self
                }
    #[allow(missing_docs)] // documentation missing in model
    pub fn set_prefix(mut self, input: ::std::option::Option<::std::string::String>) -> Self {
                    self.inner = self.inner.set_prefix(input);
                    self
                }
    #[allow(missing_docs)] // documentation missing in model
    pub fn get_prefix(&self) -> &::std::option::Option<::std::string::String> {
                    self.inner.get_prefix()
                }
    /// Sort order enumeration for list operations.
    pub fn sort_by(mut self, input: crate::types::SortBy) -> Self {
                    self.inner = self.inner.sort_by(input);
                    self
                }
    /// Sort order enumeration for list operations.
    pub fn set_sort_by(mut self, input: ::std::option::Option<crate::types::SortBy>) -> Self {
                    self.inner = self.inner.set_sort_by(input);
                    self
                }
    /// Sort order enumeration for list operations.
    pub fn get_sort_by(&self) -> &::std::option::Option<crate::types::SortBy> {
                    self.inner.get_sort_by()
                }
    #[allow(missing_docs)] // documentation missing in model
    pub fn sort_on(mut self, input: crate::types::DefaultConfigSortOn) -> Self {
                    self.inner = self.inner.sort_on(input);
                    self
                }
    #[allow(missing_docs)] // documentation missing in model
    pub fn set_sort_on(mut self, input: ::std::option::Option<crate::types::DefaultConfigSortOn>) -> Self {
                    self.inner = self.inner.set_sort_on(input);
                    self
                }
    #[allow(missing_docs)] // documentation missing in model
    pub fn get_sort_on(&self) -> &::std::option::Option<crate::types::DefaultConfigSortOn> {
                    self.inner.get_sort_on()
                }
}

