[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"

[project]
name = "superposition_bindings"
version = "0.1.0"
description = "Python bindings for Superposition"
requires-python = ">=3.8"

[tool.setuptools]
packages = ["superposition_bindings"]

[tool.setuptools.package-data]
superposition_bindings = ["libsuperposition_core.*"]
