[project]
name = "superposition_bindings"
dynamic = ["version"]
description = "Python bindings for Superposition"
requires-python = ">=3.8"

[tool.setuptools]
packages = ["superposition_bindings"]

[tool.setuptools.package-data]
superposition_bindings = ["libsuperposition_core.*", "superposition_core.*"]


[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[tool.hatch.version]
source = "env"
variable = "VERSION"

[tool.versioningit]
