[project]
name = "superposition_bindings"
dynamic = ["version"]
description = "Python bindings for Superposition"
requires-python = ">=3.8"
readme = "README.md"

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[tool.hatch.build.targets.wheel]
include = ["libsuperposition_core.*", "superposition_core.*"]

[tool.hatch.version]
source = "env"
variable = "VERSION"
