[build-system]
requires = ["setuptools>=61", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "superposition_bindings"
dynamic = ["version"]
description = "Python bindings for Superposition"
authors = [{ name = "Your Name", email = "you@example.com" }]
readme = "README.md"
requires-python = ">=3.8"
dependencies = []

[tool.setuptools]
packages = ["superposition_bindings"]

[tool.setuptools.package-data]
superposition_bindings = [
    "libsuperposition_core.*"
]
