[project]
name = "superposition_provider"
dynamic = ["version"]
description = "superposition_provider"
readme = "README.md"
requires-python = ">=3.12"
keywords = ["openfeature", "superposition_provider"]
license = { text = "Apache-2.0" }

dependencies = [
    "smithy_core==0.0.1",
    "smithy_http[aiohttp]==0.0.1",
    "smithy_json==0.0.1",
]

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[tool.hatch.version]
source = "env"
variable = "VERSION"

[tool.hatch.build.targets.wheel]
# Include the local dependencies directly in the wheel
force-include = { "../sdk/superposition_sdk" = "superposition_sdk", "../bindings/superposition_bindings" = "superposition_bindings" }

packages = ["superposition_provider"]

[tool.hatch.build]
# Exclude test files and other unnecessary files
exclude = ["tests/", "**/__pycache__/", "**/*.pyc", "**/*.pyo"]

# Include package data (like binary files from bindings)
artifacts = ["superposition_bindings/.*superposition_core.*"]

[tool.hatch.metadata]
allow-direct-references = true
