[project]
name = "superposition_provider"
dynamic = ["version"]
description = "superposition_provider"
readme = "README.md"
requires-python = ">=3.12"
keywords = ["openfeature", "superposition_provider"]
license = { text = "Apache-2.0" }

dependencies = [
    "superposition_sdk @ ../sdk",
    "superposition_bindings @ ../bindings",
]

[tool.setuptools.packages.find]
where = ["."]
include = ["superposition_provider"]

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[tool.hatch.version]
source = "env"
variable = "VERSION"

[tool.hatch.metadata]
allow-direct-references = true