// Code generated by software.amazon.smithy.rust.codegen.smithy-rs. DO NOT EDIT.
#[allow(missing_docs)] // documentation missing in model
#[non_exhaustive]
#[derive(::std::clone::Clone, ::std::cmp::PartialEq, ::std::fmt::Debug)]
pub enum ContextActionOut {
    #[allow(missing_docs)] // documentation missing in model
    Delete(::std::string::String),
    #[allow(missing_docs)] // documentation missing in model
    Move(crate::types::ContextResponse),
    #[allow(missing_docs)] // documentation missing in model
    Put(crate::types::ContextResponse),
    #[allow(missing_docs)] // documentation missing in model
    Replace(crate::types::ContextResponse),
    /// The `Unknown` variant represents cases where new union variant was received. Consider upgrading the SDK to the latest available version.
    /// An unknown enum variant
    ///
    /// _Note: If you encounter this error, consider upgrading your SDK to the latest version._
    /// The `Unknown` variant represents cases where the server sent a value that wasn't recognized
    /// by the client. This can happen when the server adds new functionality, but the client has not been updated.
    /// To investigate this, consider turning on debug logging to print the raw HTTP response.
    #[non_exhaustive]
    Unknown,
}
impl ContextActionOut {
    /// Tries to convert the enum instance into [`Delete`](crate::types::ContextActionOut::Delete), extracting the inner [`String`](::std::string::String).
    /// Returns `Err(&Self)` if it can't be converted.
    pub fn as_delete(&self) -> ::std::result::Result<&::std::string::String, &Self> {
        if let ContextActionOut::Delete(val) = &self { ::std::result::Result::Ok(val) } else { ::std::result::Result::Err(self) }
    }
    /// Returns true if this is a [`Delete`](crate::types::ContextActionOut::Delete).
    pub fn is_delete(&self) -> bool {
        self.as_delete().is_ok()
    }
    /// Tries to convert the enum instance into [`Move`](crate::types::ContextActionOut::Move), extracting the inner [`ContextResponse`](crate::types::ContextResponse).
    /// Returns `Err(&Self)` if it can't be converted.
    pub fn as_move(&self) -> ::std::result::Result<&crate::types::ContextResponse, &Self> {
        if let ContextActionOut::Move(val) = &self { ::std::result::Result::Ok(val) } else { ::std::result::Result::Err(self) }
    }
    /// Returns true if this is a [`Move`](crate::types::ContextActionOut::Move).
    pub fn is_move(&self) -> bool {
        self.as_move().is_ok()
    }
    /// Tries to convert the enum instance into [`Put`](crate::types::ContextActionOut::Put), extracting the inner [`ContextResponse`](crate::types::ContextResponse).
    /// Returns `Err(&Self)` if it can't be converted.
    pub fn as_put(&self) -> ::std::result::Result<&crate::types::ContextResponse, &Self> {
        if let ContextActionOut::Put(val) = &self { ::std::result::Result::Ok(val) } else { ::std::result::Result::Err(self) }
    }
    /// Returns true if this is a [`Put`](crate::types::ContextActionOut::Put).
    pub fn is_put(&self) -> bool {
        self.as_put().is_ok()
    }
    /// Tries to convert the enum instance into [`Replace`](crate::types::ContextActionOut::Replace), extracting the inner [`ContextResponse`](crate::types::ContextResponse).
    /// Returns `Err(&Self)` if it can't be converted.
    pub fn as_replace(&self) -> ::std::result::Result<&crate::types::ContextResponse, &Self> {
        if let ContextActionOut::Replace(val) = &self { ::std::result::Result::Ok(val) } else { ::std::result::Result::Err(self) }
    }
    /// Returns true if this is a [`Replace`](crate::types::ContextActionOut::Replace).
    pub fn is_replace(&self) -> bool {
        self.as_replace().is_ok()
    }
    /// Returns true if the enum instance is the `Unknown` variant.
    pub fn is_unknown(&self) -> bool {
        matches!(self, Self::Unknown)
    }
}

