// Code generated by software.amazon.smithy.rust.codegen.smithy-rs. DO NOT EDIT.
#[allow(missing_docs)] // documentation missing in model
#[non_exhaustive]
#[derive(::std::clone::Clone, ::std::cmp::PartialEq, ::std::fmt::Debug)]
pub struct ContextPartial  {
    #[allow(missing_docs)] // documentation missing in model
    pub id: ::std::string::String,
    /// Represents conditional criteria used for context matching. Keys define dimension names and values specify the criteria that must be met.
    pub condition: ::std::collections::HashMap::<::std::string::String, ::aws_smithy_types::Document>,
    #[allow(missing_docs)] // documentation missing in model
    pub priority: i32,
    #[allow(missing_docs)] // documentation missing in model
    pub weight: i32,
    #[allow(missing_docs)] // documentation missing in model
    pub override_with_keys: ::std::vec::Vec::<::std::string::String>,
}
impl  ContextPartial  {
    #[allow(missing_docs)] // documentation missing in model
    pub fn id(&self) -> &str {
        use std::ops::Deref; self.id.deref()
    }
    /// Represents conditional criteria used for context matching. Keys define dimension names and values specify the criteria that must be met.
    pub fn condition(&self) -> &::std::collections::HashMap::<::std::string::String, ::aws_smithy_types::Document> {
        &self.condition
    }
    #[allow(missing_docs)] // documentation missing in model
    pub fn priority(&self) -> i32 {
        self.priority
    }
    #[allow(missing_docs)] // documentation missing in model
    pub fn weight(&self) -> i32 {
        self.weight
    }
    #[allow(missing_docs)] // documentation missing in model
    pub fn override_with_keys(&self) -> &[::std::string::String] {
        use std::ops::Deref; self.override_with_keys.deref()
    }
}
impl ContextPartial {
    /// Creates a new builder-style object to manufacture [`ContextPartial`](crate::types::ContextPartial).
    pub fn builder() -> crate::types::builders::ContextPartialBuilder {
        crate::types::builders::ContextPartialBuilder::default()
    }
}

/// A builder for [`ContextPartial`](crate::types::ContextPartial).
#[derive(::std::clone::Clone, ::std::cmp::PartialEq, ::std::default::Default, ::std::fmt::Debug)]
#[non_exhaustive]
pub struct ContextPartialBuilder {
    pub(crate) id: ::std::option::Option<::std::string::String>,
    pub(crate) condition: ::std::option::Option<::std::collections::HashMap::<::std::string::String, ::aws_smithy_types::Document>>,
    pub(crate) priority: ::std::option::Option<i32>,
    pub(crate) weight: ::std::option::Option<i32>,
    pub(crate) override_with_keys: ::std::option::Option<::std::vec::Vec::<::std::string::String>>,
}
impl ContextPartialBuilder {
    #[allow(missing_docs)] // documentation missing in model
    /// This field is required.
    pub fn id(mut self, input: impl ::std::convert::Into<::std::string::String>) -> Self {
        self.id = ::std::option::Option::Some(input.into());
        self
    }
    #[allow(missing_docs)] // documentation missing in model
    pub fn set_id(mut self, input: ::std::option::Option<::std::string::String>) -> Self {
        self.id = input; self
    }
    #[allow(missing_docs)] // documentation missing in model
    pub fn get_id(&self) -> &::std::option::Option<::std::string::String> {
        &self.id
    }
    /// Adds a key-value pair to `condition`.
    ///
    /// To override the contents of this collection use [`set_condition`](Self::set_condition).
    ///
    /// Represents conditional criteria used for context matching. Keys define dimension names and values specify the criteria that must be met.
    pub fn condition(mut self, k: impl ::std::convert::Into<::std::string::String>, v: ::aws_smithy_types::Document) -> Self {
        let mut hash_map = self.condition.unwrap_or_default();
                        hash_map.insert(k.into(), v);
                        self.condition = ::std::option::Option::Some(hash_map);
                        self
    }
    /// Represents conditional criteria used for context matching. Keys define dimension names and values specify the criteria that must be met.
    pub fn set_condition(mut self, input: ::std::option::Option<::std::collections::HashMap::<::std::string::String, ::aws_smithy_types::Document>>) -> Self {
        self.condition = input; self
    }
    /// Represents conditional criteria used for context matching. Keys define dimension names and values specify the criteria that must be met.
    pub fn get_condition(&self) -> &::std::option::Option<::std::collections::HashMap::<::std::string::String, ::aws_smithy_types::Document>> {
        &self.condition
    }
    #[allow(missing_docs)] // documentation missing in model
    /// This field is required.
    pub fn priority(mut self, input: i32) -> Self {
        self.priority = ::std::option::Option::Some(input);
        self
    }
    #[allow(missing_docs)] // documentation missing in model
    pub fn set_priority(mut self, input: ::std::option::Option<i32>) -> Self {
        self.priority = input; self
    }
    #[allow(missing_docs)] // documentation missing in model
    pub fn get_priority(&self) -> &::std::option::Option<i32> {
        &self.priority
    }
    #[allow(missing_docs)] // documentation missing in model
    /// This field is required.
    pub fn weight(mut self, input: i32) -> Self {
        self.weight = ::std::option::Option::Some(input);
        self
    }
    #[allow(missing_docs)] // documentation missing in model
    pub fn set_weight(mut self, input: ::std::option::Option<i32>) -> Self {
        self.weight = input; self
    }
    #[allow(missing_docs)] // documentation missing in model
    pub fn get_weight(&self) -> &::std::option::Option<i32> {
        &self.weight
    }
    /// Appends an item to `override_with_keys`.
    ///
    /// To override the contents of this collection use [`set_override_with_keys`](Self::set_override_with_keys).
    ///
    pub fn override_with_keys(mut self, input: impl ::std::convert::Into<::std::string::String>) -> Self {
        let mut v = self.override_with_keys.unwrap_or_default();
                        v.push(input.into());
                        self.override_with_keys = ::std::option::Option::Some(v);
                        self
    }
    #[allow(missing_docs)] // documentation missing in model
    pub fn set_override_with_keys(mut self, input: ::std::option::Option<::std::vec::Vec::<::std::string::String>>) -> Self {
        self.override_with_keys = input; self
    }
    #[allow(missing_docs)] // documentation missing in model
    pub fn get_override_with_keys(&self) -> &::std::option::Option<::std::vec::Vec::<::std::string::String>> {
        &self.override_with_keys
    }
    /// Consumes the builder and constructs a [`ContextPartial`](crate::types::ContextPartial).
    /// This method will fail if any of the following fields are not set:
    /// - [`id`](crate::types::builders::ContextPartialBuilder::id)
    /// - [`condition`](crate::types::builders::ContextPartialBuilder::condition)
    /// - [`priority`](crate::types::builders::ContextPartialBuilder::priority)
    /// - [`weight`](crate::types::builders::ContextPartialBuilder::weight)
    /// - [`override_with_keys`](crate::types::builders::ContextPartialBuilder::override_with_keys)
    pub fn build(self) -> ::std::result::Result<crate::types::ContextPartial, ::aws_smithy_types::error::operation::BuildError> {
        ::std::result::Result::Ok(
            crate::types::ContextPartial {
                id: self.id
                    .ok_or_else(||
                        ::aws_smithy_types::error::operation::BuildError::missing_field("id", "id was not specified but it is required when building ContextPartial")
                    )?
                ,
                condition: self.condition
                    .ok_or_else(||
                        ::aws_smithy_types::error::operation::BuildError::missing_field("condition", "condition was not specified but it is required when building ContextPartial")
                    )?
                ,
                priority: self.priority
                    .ok_or_else(||
                        ::aws_smithy_types::error::operation::BuildError::missing_field("priority", "priority was not specified but it is required when building ContextPartial")
                    )?
                ,
                weight: self.weight
                    .ok_or_else(||
                        ::aws_smithy_types::error::operation::BuildError::missing_field("weight", "weight was not specified but it is required when building ContextPartial")
                    )?
                ,
                override_with_keys: self.override_with_keys
                    .ok_or_else(||
                        ::aws_smithy_types::error::operation::BuildError::missing_field("override_with_keys", "override_with_keys was not specified but it is required when building ContextPartial")
                    )?
                ,
            }
        )
    }
}

