// Code generated by software.amazon.smithy.rust.codegen.smithy-rs. DO NOT EDIT.
#[allow(missing_docs)] // documentation missing in model
#[non_exhaustive]
#[derive(::std::clone::Clone, ::std::cmp::PartialEq, ::std::fmt::Debug)]
pub enum GroupedDefaultConfig {
    #[allow(missing_docs)] // documentation missing in model
    Config(crate::types::DefaultConfigResponse),
    #[allow(missing_docs)] // documentation missing in model
    Group(::std::string::String),
    /// The `Unknown` variant represents cases where new union variant was received. Consider upgrading the SDK to the latest available version.
    /// An unknown enum variant
    ///
    /// _Note: If you encounter this error, consider upgrading your SDK to the latest version._
    /// The `Unknown` variant represents cases where the server sent a value that wasn't recognized
    /// by the client. This can happen when the server adds new functionality, but the client has not been updated.
    /// To investigate this, consider turning on debug logging to print the raw HTTP response.
    #[non_exhaustive]
    Unknown,
}
impl GroupedDefaultConfig {
    /// Tries to convert the enum instance into [`Config`](crate::types::GroupedDefaultConfig::Config), extracting the inner [`DefaultConfigResponse`](crate::types::DefaultConfigResponse).
    /// Returns `Err(&Self)` if it can't be converted.
    pub fn as_config(&self) -> ::std::result::Result<&crate::types::DefaultConfigResponse, &Self> {
        if let GroupedDefaultConfig::Config(val) = &self { ::std::result::Result::Ok(val) } else { ::std::result::Result::Err(self) }
    }
    /// Returns true if this is a [`Config`](crate::types::GroupedDefaultConfig::Config).
    pub fn is_config(&self) -> bool {
        self.as_config().is_ok()
    }
    /// Tries to convert the enum instance into [`Group`](crate::types::GroupedDefaultConfig::Group), extracting the inner [`String`](::std::string::String).
    /// Returns `Err(&Self)` if it can't be converted.
    pub fn as_group(&self) -> ::std::result::Result<&::std::string::String, &Self> {
        if let GroupedDefaultConfig::Group(val) = &self { ::std::result::Result::Ok(val) } else { ::std::result::Result::Err(self) }
    }
    /// Returns true if this is a [`Group`](crate::types::GroupedDefaultConfig::Group).
    pub fn is_group(&self) -> bool {
        self.as_group().is_ok()
    }
    /// Returns true if the enum instance is the `Unknown` variant.
    pub fn is_unknown(&self) -> bool {
        matches!(self, Self::Unknown)
    }
}

