{
  "formatVersion": "1.1",
  "component": {
    "group": "in.juspay.smithy",
    "module": "smithy-mcp-codegen",
    "version": "0.1.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.5"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "smithy-mcp-codegen-0.1.0.jar",
          "url": "smithy-mcp-codegen-0.1.0.jar",
          "size": 25241,
          "sha512": "37558950ef0f2cc198a2c5ef52fe9c4836aeab87ef6a9867a46edd24a093bdcb47b90190a5a7fb45d10df4c228a9fd94d95dbe161476c9d084aab723d00e8779",
          "sha256": "5010e006bfac8f49872a5e580eb194ff8cf2ba0d222e0a24b9c3259e0cab2f45",
          "sha1": "70fea7476a53acbe5a729cb7895346e32308b05e",
          "md5": "fad6173cff9828d31ff14a18f953b2b4"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "in.juspay.smithy",
          "module": "smithy-mcp-traits",
          "version": {
            "requires": "0.1.0"
          }
        },
        {
          "group": "software.amazon.smithy",
          "module": "smithy-model",
          "version": {
            "requires": "1.55.0"
          }
        },
        {
          "group": "software.amazon.smithy",
          "module": "smithy-build",
          "version": {
            "requires": "1.55.0"
          }
        }
      ],
      "files": [
        {
          "name": "smithy-mcp-codegen-0.1.0.jar",
          "url": "smithy-mcp-codegen-0.1.0.jar",
          "size": 25241,
          "sha512": "37558950ef0f2cc198a2c5ef52fe9c4836aeab87ef6a9867a46edd24a093bdcb47b90190a5a7fb45d10df4c228a9fd94d95dbe161476c9d084aab723d00e8779",
          "sha256": "5010e006bfac8f49872a5e580eb194ff8cf2ba0d222e0a24b9c3259e0cab2f45",
          "sha1": "70fea7476a53acbe5a729cb7895346e32308b05e",
          "md5": "fad6173cff9828d31ff14a18f953b2b4"
        }
      ]
    }
  ]
}
