global:
    scrape_interval: 5s

scrape_configs:
    - job_name: "node"
      static_configs:
          - targets: ["node-exporter:9100"]

    - job_name: "custom"
      static_configs:
          - targets: ["custom-exporter:8090"]
