// Code generated by software.amazon.smithy.rust.codegen.smithy-rs. DO NOT EDIT.
impl super::Client {
    /// Constructs a fluent builder for the [`CreateSecret`](crate::operation::create_secret::builders::CreateSecretFluentBuilder) operation.
                            ///
                            /// - The fluent builder is configurable:
    ///   - [`workspace_id(impl Into<String>)`](crate::operation::create_secret::builders::CreateSecretFluentBuilder::workspace_id) / [`set_workspace_id(Option<String>)`](crate::operation::create_secret::builders::CreateSecretFluentBuilder::set_workspace_id):<br>required: **true**<br>(undocumented)<br>
    ///   - [`org_id(impl Into<String>)`](crate::operation::create_secret::builders::CreateSecretFluentBuilder::org_id) / [`set_org_id(Option<String>)`](crate::operation::create_secret::builders::CreateSecretFluentBuilder::set_org_id):<br>required: **true**<br>(undocumented)<br>
    ///   - [`name(impl Into<String>)`](crate::operation::create_secret::builders::CreateSecretFluentBuilder::name) / [`set_name(Option<String>)`](crate::operation::create_secret::builders::CreateSecretFluentBuilder::set_name):<br>required: **true**<br>(undocumented)<br>
    ///   - [`value(impl Into<String>)`](crate::operation::create_secret::builders::CreateSecretFluentBuilder::value) / [`set_value(Option<String>)`](crate::operation::create_secret::builders::CreateSecretFluentBuilder::set_value):<br>required: **true**<br>Plaintext value to be encrypted and stored.<br>
    ///   - [`description(impl Into<String>)`](crate::operation::create_secret::builders::CreateSecretFluentBuilder::description) / [`set_description(Option<String>)`](crate::operation::create_secret::builders::CreateSecretFluentBuilder::set_description):<br>required: **true**<br>(undocumented)<br>
    ///   - [`change_reason(impl Into<String>)`](crate::operation::create_secret::builders::CreateSecretFluentBuilder::change_reason) / [`set_change_reason(Option<String>)`](crate::operation::create_secret::builders::CreateSecretFluentBuilder::set_change_reason):<br>required: **true**<br>(undocumented)<br>
                            /// - On success, responds with [`CreateSecretOutput`](crate::operation::create_secret::CreateSecretOutput) with field(s):
    ///   - [`name(String)`](crate::operation::create_secret::CreateSecretOutput::name): (undocumented)
    ///   - [`description(String)`](crate::operation::create_secret::CreateSecretOutput::description): (undocumented)
    ///   - [`change_reason(String)`](crate::operation::create_secret::CreateSecretOutput::change_reason): (undocumented)
    ///   - [`created_by(String)`](crate::operation::create_secret::CreateSecretOutput::created_by): (undocumented)
    ///   - [`created_at(DateTime)`](crate::operation::create_secret::CreateSecretOutput::created_at): (undocumented)
    ///   - [`last_modified_by(String)`](crate::operation::create_secret::CreateSecretOutput::last_modified_by): (undocumented)
    ///   - [`last_modified_at(DateTime)`](crate::operation::create_secret::CreateSecretOutput::last_modified_at): (undocumented)
                            /// - On failure, responds with [`SdkError<CreateSecretError>`](crate::operation::create_secret::CreateSecretError)
    pub fn create_secret(&self) -> crate::operation::create_secret::builders::CreateSecretFluentBuilder {
                                crate::operation::create_secret::builders::CreateSecretFluentBuilder::new(self.handle.clone())
                            }
}

