// Code generated by software.amazon.smithy.rust.codegen.smithy-rs. DO NOT EDIT.
impl super::Client {
    /// Constructs a fluent builder for the [`DeleteTypeTemplates`](crate::operation::delete_type_templates::builders::DeleteTypeTemplatesFluentBuilder) operation.
                            ///
                            /// - The fluent builder is configurable:
    ///   - [`workspace_id(impl Into<String>)`](crate::operation::delete_type_templates::builders::DeleteTypeTemplatesFluentBuilder::workspace_id) / [`set_workspace_id(Option<String>)`](crate::operation::delete_type_templates::builders::DeleteTypeTemplatesFluentBuilder::set_workspace_id):<br>required: **true**<br>(undocumented)<br>
    ///   - [`org_id(impl Into<String>)`](crate::operation::delete_type_templates::builders::DeleteTypeTemplatesFluentBuilder::org_id) / [`set_org_id(Option<String>)`](crate::operation::delete_type_templates::builders::DeleteTypeTemplatesFluentBuilder::set_org_id):<br>required: **true**<br>(undocumented)<br>
    ///   - [`type_name(impl Into<String>)`](crate::operation::delete_type_templates::builders::DeleteTypeTemplatesFluentBuilder::type_name) / [`set_type_name(Option<String>)`](crate::operation::delete_type_templates::builders::DeleteTypeTemplatesFluentBuilder::set_type_name):<br>required: **true**<br>(undocumented)<br>
                            /// - On success, responds with [`DeleteTypeTemplatesOutput`](crate::operation::delete_type_templates::DeleteTypeTemplatesOutput) with field(s):
    ///   - [`type_name(String)`](crate::operation::delete_type_templates::DeleteTypeTemplatesOutput::type_name): (undocumented)
    ///   - [`type_schema(HashMap::<String, Document>)`](crate::operation::delete_type_templates::DeleteTypeTemplatesOutput::type_schema): Generic key-value object structure used for flexible data representation throughout the API.
    ///   - [`description(String)`](crate::operation::delete_type_templates::DeleteTypeTemplatesOutput::description): (undocumented)
    ///   - [`change_reason(String)`](crate::operation::delete_type_templates::DeleteTypeTemplatesOutput::change_reason): (undocumented)
    ///   - [`created_by(String)`](crate::operation::delete_type_templates::DeleteTypeTemplatesOutput::created_by): (undocumented)
    ///   - [`created_at(DateTime)`](crate::operation::delete_type_templates::DeleteTypeTemplatesOutput::created_at): (undocumented)
    ///   - [`last_modified_at(DateTime)`](crate::operation::delete_type_templates::DeleteTypeTemplatesOutput::last_modified_at): (undocumented)
    ///   - [`last_modified_by(String)`](crate::operation::delete_type_templates::DeleteTypeTemplatesOutput::last_modified_by): (undocumented)
                            /// - On failure, responds with [`SdkError<DeleteTypeTemplatesError>`](crate::operation::delete_type_templates::DeleteTypeTemplatesError)
    pub fn delete_type_templates(&self) -> crate::operation::delete_type_templates::builders::DeleteTypeTemplatesFluentBuilder {
                                crate::operation::delete_type_templates::builders::DeleteTypeTemplatesFluentBuilder::new(self.handle.clone())
                            }
}

