// Code generated by software.amazon.smithy.rust.codegen.smithy-rs. DO NOT EDIT.
impl super::Client {
    /// Constructs a fluent builder for the [`DeleteVariable`](crate::operation::delete_variable::builders::DeleteVariableFluentBuilder) operation.
                            ///
                            /// - The fluent builder is configurable:
    ///   - [`workspace_id(impl Into<String>)`](crate::operation::delete_variable::builders::DeleteVariableFluentBuilder::workspace_id) / [`set_workspace_id(Option<String>)`](crate::operation::delete_variable::builders::DeleteVariableFluentBuilder::set_workspace_id):<br>required: **true**<br>(undocumented)<br>
    ///   - [`org_id(impl Into<String>)`](crate::operation::delete_variable::builders::DeleteVariableFluentBuilder::org_id) / [`set_org_id(Option<String>)`](crate::operation::delete_variable::builders::DeleteVariableFluentBuilder::set_org_id):<br>required: **true**<br>(undocumented)<br>
    ///   - [`name(impl Into<String>)`](crate::operation::delete_variable::builders::DeleteVariableFluentBuilder::name) / [`set_name(Option<String>)`](crate::operation::delete_variable::builders::DeleteVariableFluentBuilder::set_name):<br>required: **true**<br>(undocumented)<br>
                            /// - On success, responds with [`DeleteVariableOutput`](crate::operation::delete_variable::DeleteVariableOutput)
                            /// - On failure, responds with [`SdkError<DeleteVariableError>`](crate::operation::delete_variable::DeleteVariableError)
    pub fn delete_variable(&self) -> crate::operation::delete_variable::builders::DeleteVariableFluentBuilder {
                                crate::operation::delete_variable::builders::DeleteVariableFluentBuilder::new(self.handle.clone())
                            }
}

