// Code generated by software.amazon.smithy.rust.codegen.smithy-rs. DO NOT EDIT.
impl super::Client {
    /// Constructs a fluent builder for the [`GetSecret`](crate::operation::get_secret::builders::GetSecretFluentBuilder) operation.
                            ///
                            /// - The fluent builder is configurable:
    ///   - [`workspace_id(impl Into<String>)`](crate::operation::get_secret::builders::GetSecretFluentBuilder::workspace_id) / [`set_workspace_id(Option<String>)`](crate::operation::get_secret::builders::GetSecretFluentBuilder::set_workspace_id):<br>required: **true**<br>(undocumented)<br>
    ///   - [`org_id(impl Into<String>)`](crate::operation::get_secret::builders::GetSecretFluentBuilder::org_id) / [`set_org_id(Option<String>)`](crate::operation::get_secret::builders::GetSecretFluentBuilder::set_org_id):<br>required: **true**<br>(undocumented)<br>
    ///   - [`name(impl Into<String>)`](crate::operation::get_secret::builders::GetSecretFluentBuilder::name) / [`set_name(Option<String>)`](crate::operation::get_secret::builders::GetSecretFluentBuilder::set_name):<br>required: **true**<br>(undocumented)<br>
                            /// - On success, responds with [`GetSecretOutput`](crate::operation::get_secret::GetSecretOutput) with field(s):
    ///   - [`name(String)`](crate::operation::get_secret::GetSecretOutput::name): (undocumented)
    ///   - [`description(String)`](crate::operation::get_secret::GetSecretOutput::description): (undocumented)
    ///   - [`change_reason(String)`](crate::operation::get_secret::GetSecretOutput::change_reason): (undocumented)
    ///   - [`created_by(String)`](crate::operation::get_secret::GetSecretOutput::created_by): (undocumented)
    ///   - [`created_at(DateTime)`](crate::operation::get_secret::GetSecretOutput::created_at): (undocumented)
    ///   - [`last_modified_by(String)`](crate::operation::get_secret::GetSecretOutput::last_modified_by): (undocumented)
    ///   - [`last_modified_at(DateTime)`](crate::operation::get_secret::GetSecretOutput::last_modified_at): (undocumented)
                            /// - On failure, responds with [`SdkError<GetSecretError>`](crate::operation::get_secret::GetSecretError)
    pub fn get_secret(&self) -> crate::operation::get_secret::builders::GetSecretFluentBuilder {
                                crate::operation::get_secret::builders::GetSecretFluentBuilder::new(self.handle.clone())
                            }
}

