// Code generated by software.amazon.smithy.rust.codegen.smithy-rs. DO NOT EDIT.
impl super::Client {
    /// Constructs a fluent builder for the [`GetConfigToml`](crate::operation::get_config_toml::builders::GetConfigTomlFluentBuilder) operation.
                            ///
                            /// - The fluent builder is configurable:
    ///   - [`workspace_id(impl Into<String>)`](crate::operation::get_config_toml::builders::GetConfigTomlFluentBuilder::workspace_id) / [`set_workspace_id(Option<String>)`](crate::operation::get_config_toml::builders::GetConfigTomlFluentBuilder::set_workspace_id):<br>required: **true**<br>(undocumented)<br>
    ///   - [`org_id(impl Into<String>)`](crate::operation::get_config_toml::builders::GetConfigTomlFluentBuilder::org_id) / [`set_org_id(Option<String>)`](crate::operation::get_config_toml::builders::GetConfigTomlFluentBuilder::set_org_id):<br>required: **true**<br>(undocumented)<br>
                            /// - On success, responds with [`GetConfigTomlOutput`](crate::operation::get_config_toml::GetConfigTomlOutput) with field(s):
    ///   - [`toml_config(String)`](crate::operation::get_config_toml::GetConfigTomlOutput::toml_config): (undocumented)
    ///   - [`last_modified(Option<DateTime>)`](crate::operation::get_config_toml::GetConfigTomlOutput::last_modified): (undocumented)
                            /// - On failure, responds with [`SdkError<GetConfigTomlError>`](crate::operation::get_config_toml::GetConfigTomlError)
    pub fn get_config_toml(&self) -> crate::operation::get_config_toml::builders::GetConfigTomlFluentBuilder {
                                crate::operation::get_config_toml::builders::GetConfigTomlFluentBuilder::new(self.handle.clone())
                            }
}

