// Code generated by software.amazon.smithy.rust.codegen.smithy-rs. DO NOT EDIT.
impl super::Client {
    /// Constructs a fluent builder for the [`GetFunction`](crate::operation::get_function::builders::GetFunctionFluentBuilder) operation.
                            ///
                            /// - The fluent builder is configurable:
    ///   - [`workspace_id(impl Into<String>)`](crate::operation::get_function::builders::GetFunctionFluentBuilder::workspace_id) / [`set_workspace_id(Option<String>)`](crate::operation::get_function::builders::GetFunctionFluentBuilder::set_workspace_id):<br>required: **true**<br>(undocumented)<br>
    ///   - [`org_id(impl Into<String>)`](crate::operation::get_function::builders::GetFunctionFluentBuilder::org_id) / [`set_org_id(Option<String>)`](crate::operation::get_function::builders::GetFunctionFluentBuilder::set_org_id):<br>required: **true**<br>(undocumented)<br>
    ///   - [`function_name(impl Into<String>)`](crate::operation::get_function::builders::GetFunctionFluentBuilder::function_name) / [`set_function_name(Option<String>)`](crate::operation::get_function::builders::GetFunctionFluentBuilder::set_function_name):<br>required: **true**<br>(undocumented)<br>
                            /// - On success, responds with [`GetFunctionOutput`](crate::operation::get_function::GetFunctionOutput) with field(s):
    ///   - [`function_name(String)`](crate::operation::get_function::GetFunctionOutput::function_name): (undocumented)
    ///   - [`published_code(Option<String>)`](crate::operation::get_function::GetFunctionOutput::published_code): (undocumented)
    ///   - [`draft_code(String)`](crate::operation::get_function::GetFunctionOutput::draft_code): (undocumented)
    ///   - [`published_runtime_version(Option<FunctionRuntimeVersion>)`](crate::operation::get_function::GetFunctionOutput::published_runtime_version): (undocumented)
    ///   - [`draft_runtime_version(FunctionRuntimeVersion)`](crate::operation::get_function::GetFunctionOutput::draft_runtime_version): (undocumented)
    ///   - [`published_at(Option<DateTime>)`](crate::operation::get_function::GetFunctionOutput::published_at): (undocumented)
    ///   - [`draft_edited_at(DateTime)`](crate::operation::get_function::GetFunctionOutput::draft_edited_at): (undocumented)
    ///   - [`published_by(Option<String>)`](crate::operation::get_function::GetFunctionOutput::published_by): (undocumented)
    ///   - [`draft_edited_by(String)`](crate::operation::get_function::GetFunctionOutput::draft_edited_by): (undocumented)
    ///   - [`last_modified_at(DateTime)`](crate::operation::get_function::GetFunctionOutput::last_modified_at): (undocumented)
    ///   - [`last_modified_by(String)`](crate::operation::get_function::GetFunctionOutput::last_modified_by): (undocumented)
    ///   - [`change_reason(String)`](crate::operation::get_function::GetFunctionOutput::change_reason): (undocumented)
    ///   - [`description(String)`](crate::operation::get_function::GetFunctionOutput::description): (undocumented)
    ///   - [`function_type(FunctionTypes)`](crate::operation::get_function::GetFunctionOutput::function_type): (undocumented)
                            /// - On failure, responds with [`SdkError<GetFunctionError>`](crate::operation::get_function::GetFunctionError)
    pub fn get_function(&self) -> crate::operation::get_function::builders::GetFunctionFluentBuilder {
                                crate::operation::get_function::builders::GetFunctionFluentBuilder::new(self.handle.clone())
                            }
}

