// Code generated by software.amazon.smithy.rust.codegen.smithy-rs. DO NOT EDIT.
impl super::Client {
    /// Constructs a fluent builder for the [`GetContextFromCondition`](crate::operation::get_context_from_condition::builders::GetContextFromConditionFluentBuilder) operation.
                            ///
                            /// - The fluent builder is configurable:
    ///   - [`workspace_id(impl Into<String>)`](crate::operation::get_context_from_condition::builders::GetContextFromConditionFluentBuilder::workspace_id) / [`set_workspace_id(Option<String>)`](crate::operation::get_context_from_condition::builders::GetContextFromConditionFluentBuilder::set_workspace_id):<br>required: **true**<br>(undocumented)<br>
    ///   - [`org_id(impl Into<String>)`](crate::operation::get_context_from_condition::builders::GetContextFromConditionFluentBuilder::org_id) / [`set_org_id(Option<String>)`](crate::operation::get_context_from_condition::builders::GetContextFromConditionFluentBuilder::set_org_id):<br>required: **true**<br>(undocumented)<br>
    ///   - [`context(Document)`](crate::operation::get_context_from_condition::builders::GetContextFromConditionFluentBuilder::context) / [`set_context(Option<Document>)`](crate::operation::get_context_from_condition::builders::GetContextFromConditionFluentBuilder::set_context):<br>required: **false**<br>(undocumented)<br>
                            /// - On success, responds with [`GetContextFromConditionOutput`](crate::operation::get_context_from_condition::GetContextFromConditionOutput) with field(s):
    ///   - [`id(String)`](crate::operation::get_context_from_condition::GetContextFromConditionOutput::id): (undocumented)
    ///   - [`value(Option<HashMap::<String, Document>>)`](crate::operation::get_context_from_condition::GetContextFromConditionOutput::value): Represents conditional criteria used for context matching. Keys define dimension names and values specify the criteria that must be met.
    ///   - [`r#override(Option<HashMap::<String, Document>>)`](crate::operation::get_context_from_condition::GetContextFromConditionOutput::override): Configuration overrides that replace default values when context conditions are met. Keys represent configuration keys and values are the override data.
    ///   - [`override_id(Option<String>)`](crate::operation::get_context_from_condition::GetContextFromConditionOutput::override_id): (undocumented)
    ///   - [`weight(Option<String>)`](crate::operation::get_context_from_condition::GetContextFromConditionOutput::weight): Priority weight used to determine the order of context evaluation. Higher weights take precedence during configuration resolution.
    ///   - [`description(Option<String>)`](crate::operation::get_context_from_condition::GetContextFromConditionOutput::description): (undocumented)
    ///   - [`change_reason(Option<String>)`](crate::operation::get_context_from_condition::GetContextFromConditionOutput::change_reason): (undocumented)
    ///   - [`created_at(Option<DateTime>)`](crate::operation::get_context_from_condition::GetContextFromConditionOutput::created_at): (undocumented)
    ///   - [`created_by(Option<String>)`](crate::operation::get_context_from_condition::GetContextFromConditionOutput::created_by): (undocumented)
    ///   - [`last_modified_at(Option<DateTime>)`](crate::operation::get_context_from_condition::GetContextFromConditionOutput::last_modified_at): (undocumented)
    ///   - [`last_modified_by(Option<String>)`](crate::operation::get_context_from_condition::GetContextFromConditionOutput::last_modified_by): (undocumented)
                            /// - On failure, responds with [`SdkError<GetContextFromConditionError>`](crate::operation::get_context_from_condition::GetContextFromConditionError)
    pub fn get_context_from_condition(&self) -> crate::operation::get_context_from_condition::builders::GetContextFromConditionFluentBuilder {
                                crate::operation::get_context_from_condition::builders::GetContextFromConditionFluentBuilder::new(self.handle.clone())
                            }
}

