// Code generated by software.amazon.smithy.rust.codegen.smithy-rs. DO NOT EDIT.
impl super::Client {
    /// Constructs a fluent builder for the [`GetWebhook`](crate::operation::get_webhook::builders::GetWebhookFluentBuilder) operation.
                            ///
                            /// - The fluent builder is configurable:
    ///   - [`workspace_id(impl Into<String>)`](crate::operation::get_webhook::builders::GetWebhookFluentBuilder::workspace_id) / [`set_workspace_id(Option<String>)`](crate::operation::get_webhook::builders::GetWebhookFluentBuilder::set_workspace_id):<br>required: **true**<br>(undocumented)<br>
    ///   - [`org_id(impl Into<String>)`](crate::operation::get_webhook::builders::GetWebhookFluentBuilder::org_id) / [`set_org_id(Option<String>)`](crate::operation::get_webhook::builders::GetWebhookFluentBuilder::set_org_id):<br>required: **true**<br>(undocumented)<br>
    ///   - [`name(impl Into<String>)`](crate::operation::get_webhook::builders::GetWebhookFluentBuilder::name) / [`set_name(Option<String>)`](crate::operation::get_webhook::builders::GetWebhookFluentBuilder::set_name):<br>required: **true**<br>(undocumented)<br>
                            /// - On success, responds with [`GetWebhookOutput`](crate::operation::get_webhook::GetWebhookOutput) with field(s):
    ///   - [`name(String)`](crate::operation::get_webhook::GetWebhookOutput::name): (undocumented)
    ///   - [`description(String)`](crate::operation::get_webhook::GetWebhookOutput::description): (undocumented)
    ///   - [`enabled(bool)`](crate::operation::get_webhook::GetWebhookOutput::enabled): (undocumented)
    ///   - [`url(String)`](crate::operation::get_webhook::GetWebhookOutput::url): (undocumented)
    ///   - [`method(HttpMethod)`](crate::operation::get_webhook::GetWebhookOutput::method): (undocumented)
    ///   - [`version(Version)`](crate::operation::get_webhook::GetWebhookOutput::version): (undocumented)
    ///   - [`custom_headers(Option<HashMap::<String, Document>>)`](crate::operation::get_webhook::GetWebhookOutput::custom_headers): Generic key-value object structure used for flexible data representation throughout the API.
    ///   - [`events(Vec::<String>)`](crate::operation::get_webhook::GetWebhookOutput::events): (undocumented)
    ///   - [`max_retries(i32)`](crate::operation::get_webhook::GetWebhookOutput::max_retries): (undocumented)
    ///   - [`last_triggered_at(Option<DateTime>)`](crate::operation::get_webhook::GetWebhookOutput::last_triggered_at): (undocumented)
    ///   - [`change_reason(String)`](crate::operation::get_webhook::GetWebhookOutput::change_reason): (undocumented)
    ///   - [`created_by(String)`](crate::operation::get_webhook::GetWebhookOutput::created_by): (undocumented)
    ///   - [`created_at(DateTime)`](crate::operation::get_webhook::GetWebhookOutput::created_at): (undocumented)
    ///   - [`last_modified_by(String)`](crate::operation::get_webhook::GetWebhookOutput::last_modified_by): (undocumented)
    ///   - [`last_modified_at(DateTime)`](crate::operation::get_webhook::GetWebhookOutput::last_modified_at): (undocumented)
                            /// - On failure, responds with [`SdkError<GetWebhookError>`](crate::operation::get_webhook::GetWebhookError)
    pub fn get_webhook(&self) -> crate::operation::get_webhook::builders::GetWebhookFluentBuilder {
                                crate::operation::get_webhook::builders::GetWebhookFluentBuilder::new(self.handle.clone())
                            }
}

