// Code generated by software.amazon.smithy.rust.codegen.smithy-rs. DO NOT EDIT.
impl super::Client {
    /// Constructs a fluent builder for the [`ImportConfigToml`](crate::operation::import_config_toml::builders::ImportConfigTomlFluentBuilder) operation.
                            ///
                            /// - The fluent builder is configurable:
    ///   - [`workspace_id(impl Into<String>)`](crate::operation::import_config_toml::builders::ImportConfigTomlFluentBuilder::workspace_id) / [`set_workspace_id(Option<String>)`](crate::operation::import_config_toml::builders::ImportConfigTomlFluentBuilder::set_workspace_id):<br>required: **true**<br>(undocumented)<br>
    ///   - [`org_id(impl Into<String>)`](crate::operation::import_config_toml::builders::ImportConfigTomlFluentBuilder::org_id) / [`set_org_id(Option<String>)`](crate::operation::import_config_toml::builders::ImportConfigTomlFluentBuilder::set_org_id):<br>required: **true**<br>(undocumented)<br>
    ///   - [`strategy(ImportStrategy)`](crate::operation::import_config_toml::builders::ImportConfigTomlFluentBuilder::strategy) / [`set_strategy(Option<ImportStrategy>)`](crate::operation::import_config_toml::builders::ImportConfigTomlFluentBuilder::set_strategy):<br>required: **false**<br>How the import applies file entities to the workspace. Defaults to upsert.<br>
    ///   - [`on_error(ImportOnError)`](crate::operation::import_config_toml::builders::ImportConfigTomlFluentBuilder::on_error) / [`set_on_error(Option<ImportOnError>)`](crate::operation::import_config_toml::builders::ImportConfigTomlFluentBuilder::set_on_error):<br>required: **false**<br>Whether to abort (default) or continue on per-entity errors.<br>
    ///   - [`dry_run(bool)`](crate::operation::import_config_toml::builders::ImportConfigTomlFluentBuilder::dry_run) / [`set_dry_run(Option<bool>)`](crate::operation::import_config_toml::builders::ImportConfigTomlFluentBuilder::set_dry_run):<br>required: **false**<br>When true, validates and summarises the import without persisting anything. Defaults to false.<br>
    ///   - [`config_tags(impl Into<String>)`](crate::operation::import_config_toml::builders::ImportConfigTomlFluentBuilder::config_tags) / [`set_config_tags(Option<String>)`](crate::operation::import_config_toml::builders::ImportConfigTomlFluentBuilder::set_config_tags):<br>required: **false**<br>(undocumented)<br>
    ///   - [`toml_config(impl Into<String>)`](crate::operation::import_config_toml::builders::ImportConfigTomlFluentBuilder::toml_config) / [`set_toml_config(Option<String>)`](crate::operation::import_config_toml::builders::ImportConfigTomlFluentBuilder::set_toml_config):<br>required: **true**<br>(undocumented)<br>
                            /// - On success, responds with [`ImportConfigTomlOutput`](crate::operation::import_config_toml::ImportConfigTomlOutput) with field(s):
    ///   - [`strategy(String)`](crate::operation::import_config_toml::ImportConfigTomlOutput::strategy): (undocumented)
    ///   - [`dry_run(bool)`](crate::operation::import_config_toml::ImportConfigTomlOutput::dry_run): (undocumented)
    ///   - [`config_version(Option<String>)`](crate::operation::import_config_toml::ImportConfigTomlOutput::config_version): (undocumented)
    ///   - [`dimensions(ImportEntityReport)`](crate::operation::import_config_toml::ImportConfigTomlOutput::dimensions): Per-entity outcome counts for an import.
    ///   - [`default_configs(ImportEntityReport)`](crate::operation::import_config_toml::ImportConfigTomlOutput::default_configs): Per-entity outcome counts for an import.
    ///   - [`contexts(ImportEntityReport)`](crate::operation::import_config_toml::ImportConfigTomlOutput::contexts): Per-entity outcome counts for an import.
                            /// - On failure, responds with [`SdkError<ImportConfigTomlError>`](crate::operation::import_config_toml::ImportConfigTomlError)
    pub fn import_config_toml(&self) -> crate::operation::import_config_toml::builders::ImportConfigTomlFluentBuilder {
                                crate::operation::import_config_toml::builders::ImportConfigTomlFluentBuilder::new(self.handle.clone())
                            }
}

