// Code generated by software.amazon.smithy.rust.codegen.smithy-rs. DO NOT EDIT.
impl super::Client {
    /// Constructs a fluent builder for the [`ListGroupedDefaultConfigs`](crate::operation::list_grouped_default_configs::builders::ListGroupedDefaultConfigsFluentBuilder) operation.
                            ///
                            /// - The fluent builder is configurable:
    ///   - [`workspace_id(impl Into<String>)`](crate::operation::list_grouped_default_configs::builders::ListGroupedDefaultConfigsFluentBuilder::workspace_id) / [`set_workspace_id(Option<String>)`](crate::operation::list_grouped_default_configs::builders::ListGroupedDefaultConfigsFluentBuilder::set_workspace_id):<br>required: **true**<br>(undocumented)<br>
    ///   - [`org_id(impl Into<String>)`](crate::operation::list_grouped_default_configs::builders::ListGroupedDefaultConfigsFluentBuilder::org_id) / [`set_org_id(Option<String>)`](crate::operation::list_grouped_default_configs::builders::ListGroupedDefaultConfigsFluentBuilder::set_org_id):<br>required: **true**<br>(undocumented)<br>
    ///   - [`count(i32)`](crate::operation::list_grouped_default_configs::builders::ListGroupedDefaultConfigsFluentBuilder::count) / [`set_count(Option<i32>)`](crate::operation::list_grouped_default_configs::builders::ListGroupedDefaultConfigsFluentBuilder::set_count):<br>required: **false**<br>Number of items to be returned in each page.<br>
    ///   - [`page(i32)`](crate::operation::list_grouped_default_configs::builders::ListGroupedDefaultConfigsFluentBuilder::page) / [`set_page(Option<i32>)`](crate::operation::list_grouped_default_configs::builders::ListGroupedDefaultConfigsFluentBuilder::set_page):<br>required: **false**<br>Page number to retrieve, starting from 1.<br>
    ///   - [`all(bool)`](crate::operation::list_grouped_default_configs::builders::ListGroupedDefaultConfigsFluentBuilder::all) / [`set_all(Option<bool>)`](crate::operation::list_grouped_default_configs::builders::ListGroupedDefaultConfigsFluentBuilder::set_all):<br>required: **false**<br>If true, returns all requested items, ignoring pagination parameters page and count.<br>
    ///   - [`name(impl Into<String>)`](crate::operation::list_grouped_default_configs::builders::ListGroupedDefaultConfigsFluentBuilder::name) / [`set_name(Option<Vec::<String>>)`](crate::operation::list_grouped_default_configs::builders::ListGroupedDefaultConfigsFluentBuilder::set_name):<br>required: **false**<br>(undocumented)<br>
    ///   - [`prefix(impl Into<String>)`](crate::operation::list_grouped_default_configs::builders::ListGroupedDefaultConfigsFluentBuilder::prefix) / [`set_prefix(Option<String>)`](crate::operation::list_grouped_default_configs::builders::ListGroupedDefaultConfigsFluentBuilder::set_prefix):<br>required: **false**<br>(undocumented)<br>
    ///   - [`sort_by(SortBy)`](crate::operation::list_grouped_default_configs::builders::ListGroupedDefaultConfigsFluentBuilder::sort_by) / [`set_sort_by(Option<SortBy>)`](crate::operation::list_grouped_default_configs::builders::ListGroupedDefaultConfigsFluentBuilder::set_sort_by):<br>required: **false**<br>Sort order enumeration for list operations.<br>
    ///   - [`sort_on(DefaultConfigSortOn)`](crate::operation::list_grouped_default_configs::builders::ListGroupedDefaultConfigsFluentBuilder::sort_on) / [`set_sort_on(Option<DefaultConfigSortOn>)`](crate::operation::list_grouped_default_configs::builders::ListGroupedDefaultConfigsFluentBuilder::set_sort_on):<br>required: **false**<br>(undocumented)<br>
                            /// - On success, responds with [`ListGroupedDefaultConfigsOutput`](crate::operation::list_grouped_default_configs::ListGroupedDefaultConfigsOutput) with field(s):
    ///   - [`total_pages(i32)`](crate::operation::list_grouped_default_configs::ListGroupedDefaultConfigsOutput::total_pages): (undocumented)
    ///   - [`total_items(i32)`](crate::operation::list_grouped_default_configs::ListGroupedDefaultConfigsOutput::total_items): (undocumented)
    ///   - [`data(Vec::<GroupedDefaultConfig>)`](crate::operation::list_grouped_default_configs::ListGroupedDefaultConfigsOutput::data): (undocumented)
                            /// - On failure, responds with [`SdkError<ListGroupedDefaultConfigsError>`](crate::operation::list_grouped_default_configs::ListGroupedDefaultConfigsError)
    pub fn list_grouped_default_configs(&self) -> crate::operation::list_grouped_default_configs::builders::ListGroupedDefaultConfigsFluentBuilder {
                                crate::operation::list_grouped_default_configs::builders::ListGroupedDefaultConfigsFluentBuilder::new(self.handle.clone())
                            }
}

