// Code generated by software.amazon.smithy.rust.codegen.smithy-rs. DO NOT EDIT.
impl super::Client {
    /// Constructs a fluent builder for the [`ListVariables`](crate::operation::list_variables::builders::ListVariablesFluentBuilder) operation.
                            ///
                            /// - The fluent builder is configurable:
    ///   - [`count(i32)`](crate::operation::list_variables::builders::ListVariablesFluentBuilder::count) / [`set_count(Option<i32>)`](crate::operation::list_variables::builders::ListVariablesFluentBuilder::set_count):<br>required: **false**<br>Number of items to be returned in each page.<br>
    ///   - [`page(i32)`](crate::operation::list_variables::builders::ListVariablesFluentBuilder::page) / [`set_page(Option<i32>)`](crate::operation::list_variables::builders::ListVariablesFluentBuilder::set_page):<br>required: **false**<br>Page number to retrieve, starting from 1.<br>
    ///   - [`all(bool)`](crate::operation::list_variables::builders::ListVariablesFluentBuilder::all) / [`set_all(Option<bool>)`](crate::operation::list_variables::builders::ListVariablesFluentBuilder::set_all):<br>required: **false**<br>If true, returns all requested items, ignoring pagination parameters page and count.<br>
    ///   - [`workspace_id(impl Into<String>)`](crate::operation::list_variables::builders::ListVariablesFluentBuilder::workspace_id) / [`set_workspace_id(Option<String>)`](crate::operation::list_variables::builders::ListVariablesFluentBuilder::set_workspace_id):<br>required: **true**<br>(undocumented)<br>
    ///   - [`org_id(impl Into<String>)`](crate::operation::list_variables::builders::ListVariablesFluentBuilder::org_id) / [`set_org_id(Option<String>)`](crate::operation::list_variables::builders::ListVariablesFluentBuilder::set_org_id):<br>required: **true**<br>(undocumented)<br>
    ///   - [`name(impl Into<String>)`](crate::operation::list_variables::builders::ListVariablesFluentBuilder::name) / [`set_name(Option<Vec::<String>>)`](crate::operation::list_variables::builders::ListVariablesFluentBuilder::set_name):<br>required: **false**<br>Filter by variable name (exact match or substring, depending on backend implementation).<br>
    ///   - [`created_by(impl Into<String>)`](crate::operation::list_variables::builders::ListVariablesFluentBuilder::created_by) / [`set_created_by(Option<Vec::<String>>)`](crate::operation::list_variables::builders::ListVariablesFluentBuilder::set_created_by):<br>required: **false**<br>Filter by the user who created the variable<br>
    ///   - [`last_modified_by(impl Into<String>)`](crate::operation::list_variables::builders::ListVariablesFluentBuilder::last_modified_by) / [`set_last_modified_by(Option<Vec::<String>>)`](crate::operation::list_variables::builders::ListVariablesFluentBuilder::set_last_modified_by):<br>required: **false**<br>Filter by the user who last modified the variable<br>
    ///   - [`sort_on(VariableSortOn)`](crate::operation::list_variables::builders::ListVariablesFluentBuilder::sort_on) / [`set_sort_on(Option<VariableSortOn>)`](crate::operation::list_variables::builders::ListVariablesFluentBuilder::set_sort_on):<br>required: **false**<br>Field to sort the results by.<br>
    ///   - [`sort_by(SortBy)`](crate::operation::list_variables::builders::ListVariablesFluentBuilder::sort_by) / [`set_sort_by(Option<SortBy>)`](crate::operation::list_variables::builders::ListVariablesFluentBuilder::set_sort_by):<br>required: **false**<br>Sort order (ascending or descending).<br>
                            /// - On success, responds with [`ListVariablesOutput`](crate::operation::list_variables::ListVariablesOutput) with field(s):
    ///   - [`total_pages(i32)`](crate::operation::list_variables::ListVariablesOutput::total_pages): (undocumented)
    ///   - [`total_items(i32)`](crate::operation::list_variables::ListVariablesOutput::total_items): (undocumented)
    ///   - [`data(Vec::<VariableResponse>)`](crate::operation::list_variables::ListVariablesOutput::data): (undocumented)
                            /// - On failure, responds with [`SdkError<ListVariablesError>`](crate::operation::list_variables::ListVariablesError)
    pub fn list_variables(&self) -> crate::operation::list_variables::builders::ListVariablesFluentBuilder {
                                crate::operation::list_variables::builders::ListVariablesFluentBuilder::new(self.handle.clone())
                            }
}

