// Code generated by software.amazon.smithy.rust.codegen.smithy-rs. DO NOT EDIT.
impl super::Client {
    /// Constructs a fluent builder for the [`RotateMasterKey`](crate::operation::rotate_master_key::builders::RotateMasterKeyFluentBuilder) operation.
                            ///
                            /// - The fluent builder takes no input, just [`send`](crate::operation::rotate_master_key::builders::RotateMasterKeyFluentBuilder::send) it.
                            /// - On success, responds with [`RotateMasterKeyOutput`](crate::operation::rotate_master_key::RotateMasterKeyOutput) with field(s):
    ///   - [`workspaces_rotated(i64)`](crate::operation::rotate_master_key::RotateMasterKeyOutput::workspaces_rotated): (undocumented)
    ///   - [`total_secrets_re_encrypted(i64)`](crate::operation::rotate_master_key::RotateMasterKeyOutput::total_secrets_re_encrypted): (undocumented)
    ///   - [`rotated_at(DateTime)`](crate::operation::rotate_master_key::RotateMasterKeyOutput::rotated_at): (undocumented)
    ///   - [`new_master_key(String)`](crate::operation::rotate_master_key::RotateMasterKeyOutput::new_master_key): (undocumented)
                            /// - On failure, responds with [`SdkError<RotateMasterKeyError>`](crate::operation::rotate_master_key::RotateMasterKeyError)
    pub fn rotate_master_key(&self) -> crate::operation::rotate_master_key::builders::RotateMasterKeyFluentBuilder {
                                crate::operation::rotate_master_key::builders::RotateMasterKeyFluentBuilder::new(self.handle.clone())
                            }
}

