// Code generated by software.amazon.smithy.rust.codegen.smithy-rs. DO NOT EDIT.
#[allow(missing_docs)] // documentation missing in model
#[non_exhaustive]
#[derive(::std::clone::Clone, ::std::cmp::PartialEq, ::std::fmt::Debug)]
pub struct ListJobsInput  {
    /// Number of items to be returned in each page.
    pub count: ::std::option::Option<i32>,
    /// Page number to retrieve, starting from 1.
    pub page: ::std::option::Option<i32>,
    /// If true, returns all requested items, ignoring pagination parameters page and count.
    pub all: ::std::option::Option<bool>,
    #[allow(missing_docs)] // documentation missing in model
    pub workspace_id: ::std::option::Option<::std::string::String>,
    #[allow(missing_docs)] // documentation missing in model
    pub org_id: ::std::option::Option<::std::string::String>,
    /// Lifecycle status of a background job.
    pub status: ::std::option::Option<crate::types::BackgroundJobStatus>,
    /// Type of background job.
    pub job_type: ::std::option::Option<crate::types::BackgroundJobType>,
}
impl  ListJobsInput  {
    /// Number of items to be returned in each page.
    pub fn count(&self) -> ::std::option::Option<i32> {
        self.count
    }
    /// Page number to retrieve, starting from 1.
    pub fn page(&self) -> ::std::option::Option<i32> {
        self.page
    }
    /// If true, returns all requested items, ignoring pagination parameters page and count.
    pub fn all(&self) -> ::std::option::Option<bool> {
        self.all
    }
    #[allow(missing_docs)] // documentation missing in model
    pub fn workspace_id(&self) -> ::std::option::Option<&str> {
        self.workspace_id.as_deref()
    }
    #[allow(missing_docs)] // documentation missing in model
    pub fn org_id(&self) -> ::std::option::Option<&str> {
        self.org_id.as_deref()
    }
    /// Lifecycle status of a background job.
    pub fn status(&self) -> ::std::option::Option<&crate::types::BackgroundJobStatus> {
        self.status.as_ref()
    }
    /// Type of background job.
    pub fn job_type(&self) -> ::std::option::Option<&crate::types::BackgroundJobType> {
        self.job_type.as_ref()
    }
}
impl ListJobsInput {
    /// Creates a new builder-style object to manufacture [`ListJobsInput`](crate::operation::list_jobs::ListJobsInput).
    pub fn builder() -> crate::operation::list_jobs::builders::ListJobsInputBuilder {
        crate::operation::list_jobs::builders::ListJobsInputBuilder::default()
    }
}

/// A builder for [`ListJobsInput`](crate::operation::list_jobs::ListJobsInput).
#[derive(::std::clone::Clone, ::std::cmp::PartialEq, ::std::default::Default, ::std::fmt::Debug)]
#[non_exhaustive]
pub struct ListJobsInputBuilder {
    pub(crate) count: ::std::option::Option<i32>,
    pub(crate) page: ::std::option::Option<i32>,
    pub(crate) all: ::std::option::Option<bool>,
    pub(crate) workspace_id: ::std::option::Option<::std::string::String>,
    pub(crate) org_id: ::std::option::Option<::std::string::String>,
    pub(crate) status: ::std::option::Option<crate::types::BackgroundJobStatus>,
    pub(crate) job_type: ::std::option::Option<crate::types::BackgroundJobType>,
}
impl ListJobsInputBuilder {
    /// Number of items to be returned in each page.
    pub fn count(mut self, input: i32) -> Self {
        self.count = ::std::option::Option::Some(input);
        self
    }
    /// Number of items to be returned in each page.
    pub fn set_count(mut self, input: ::std::option::Option<i32>) -> Self {
        self.count = input; self
    }
    /// Number of items to be returned in each page.
    pub fn get_count(&self) -> &::std::option::Option<i32> {
        &self.count
    }
    /// Page number to retrieve, starting from 1.
    pub fn page(mut self, input: i32) -> Self {
        self.page = ::std::option::Option::Some(input);
        self
    }
    /// Page number to retrieve, starting from 1.
    pub fn set_page(mut self, input: ::std::option::Option<i32>) -> Self {
        self.page = input; self
    }
    /// Page number to retrieve, starting from 1.
    pub fn get_page(&self) -> &::std::option::Option<i32> {
        &self.page
    }
    /// If true, returns all requested items, ignoring pagination parameters page and count.
    pub fn all(mut self, input: bool) -> Self {
        self.all = ::std::option::Option::Some(input);
        self
    }
    /// If true, returns all requested items, ignoring pagination parameters page and count.
    pub fn set_all(mut self, input: ::std::option::Option<bool>) -> Self {
        self.all = input; self
    }
    /// If true, returns all requested items, ignoring pagination parameters page and count.
    pub fn get_all(&self) -> &::std::option::Option<bool> {
        &self.all
    }
    #[allow(missing_docs)] // documentation missing in model
    /// This field is required.
    pub fn workspace_id(mut self, input: impl ::std::convert::Into<::std::string::String>) -> Self {
        self.workspace_id = ::std::option::Option::Some(input.into());
        self
    }
    #[allow(missing_docs)] // documentation missing in model
    pub fn set_workspace_id(mut self, input: ::std::option::Option<::std::string::String>) -> Self {
        self.workspace_id = input; self
    }
    #[allow(missing_docs)] // documentation missing in model
    pub fn get_workspace_id(&self) -> &::std::option::Option<::std::string::String> {
        &self.workspace_id
    }
    #[allow(missing_docs)] // documentation missing in model
    /// This field is required.
    pub fn org_id(mut self, input: impl ::std::convert::Into<::std::string::String>) -> Self {
        self.org_id = ::std::option::Option::Some(input.into());
        self
    }
    #[allow(missing_docs)] // documentation missing in model
    pub fn set_org_id(mut self, input: ::std::option::Option<::std::string::String>) -> Self {
        self.org_id = input; self
    }
    #[allow(missing_docs)] // documentation missing in model
    pub fn get_org_id(&self) -> &::std::option::Option<::std::string::String> {
        &self.org_id
    }
    /// Lifecycle status of a background job.
    pub fn status(mut self, input: crate::types::BackgroundJobStatus) -> Self {
        self.status = ::std::option::Option::Some(input);
        self
    }
    /// Lifecycle status of a background job.
    pub fn set_status(mut self, input: ::std::option::Option<crate::types::BackgroundJobStatus>) -> Self {
        self.status = input; self
    }
    /// Lifecycle status of a background job.
    pub fn get_status(&self) -> &::std::option::Option<crate::types::BackgroundJobStatus> {
        &self.status
    }
    /// Type of background job.
    pub fn job_type(mut self, input: crate::types::BackgroundJobType) -> Self {
        self.job_type = ::std::option::Option::Some(input);
        self
    }
    /// Type of background job.
    pub fn set_job_type(mut self, input: ::std::option::Option<crate::types::BackgroundJobType>) -> Self {
        self.job_type = input; self
    }
    /// Type of background job.
    pub fn get_job_type(&self) -> &::std::option::Option<crate::types::BackgroundJobType> {
        &self.job_type
    }
    /// Consumes the builder and constructs a [`ListJobsInput`](crate::operation::list_jobs::ListJobsInput).
    pub fn build(self) -> ::std::result::Result<crate::operation::list_jobs::ListJobsInput, ::aws_smithy_types::error::operation::BuildError> {
        ::std::result::Result::Ok(
            crate::operation::list_jobs::ListJobsInput {
                count: self.count
                ,
                page: self.page
                ,
                all: self.all
                ,
                workspace_id: self.workspace_id
                ,
                org_id: self.org_id
                ,
                status: self.status
                ,
                job_type: self.job_type
                ,
            }
        )
    }
}

