[package]
name = "superposition_toml"
version.workspace = true
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[lib]
name = "superposition_toml"
path = "src/lib.rs"

[[bin]]
name = "superposition_toml_bin"
path = "src/bin.rs"

[dependencies]
blake3 = "1.3.3"
clap = { version = "4.3.0", features = ["derive"] }
itertools = { workspace = true }
pest = "2.6"
pest_derive = "2.6"
serde_json = { workspace = true }
superposition_core = { workspace = true }
superposition_types = { workspace = true }
toml = { workspace = true }
