// Code generated by software.amazon.smithy.rust.codegen.smithy-rs. DO NOT EDIT.
#[allow(clippy::unnecessary_wraps)]
pub fn de_import_config_toml_http_error(_response_status: u16, _response_headers: &::aws_smithy_runtime_api::http::Headers, _response_body: &[u8]) -> std::result::Result<crate::operation::import_config_toml::ImportConfigTomlOutput, crate::operation::import_config_toml::ImportConfigTomlError> {
    #[allow(unused_mut)]
    let mut generic_builder = crate::protocol_serde::parse_http_error_metadata(_response_status, _response_headers, _response_body).map_err(crate::operation::import_config_toml::ImportConfigTomlError::unhandled)?;
    let generic = generic_builder.build();
    let error_code = match generic.code() {
                                Some(code) => code,
                                None => return Err(crate::operation::import_config_toml::ImportConfigTomlError::unhandled(generic))
                            };
    
                            let _error_message = generic.message().map(|msg|msg.to_owned());
    Err(match error_code {
        "InternalServerError" => crate::operation::import_config_toml::ImportConfigTomlError::InternalServerError({
            #[allow(unused_mut)]
            let mut tmp =
                 {
                    #[allow(unused_mut)]
                    let mut output = crate::types::error::builders::InternalServerErrorBuilder::default();
                    output = crate::protocol_serde::shape_internal_server_error::de_internal_server_error_json_err(_response_body, output).map_err(crate::operation::import_config_toml::ImportConfigTomlError::unhandled)?;
                    let output = output.meta(generic);
                    output.build()
                }
            ;
            if tmp.message.is_none() {
                                                            tmp.message = _error_message;
                                                        }
            tmp
        }),
        _ => crate::operation::import_config_toml::ImportConfigTomlError::generic(generic)
    })
}

#[allow(clippy::unnecessary_wraps)]
pub fn de_import_config_toml_http_response(_response_status: u16, _response_headers: &::aws_smithy_runtime_api::http::Headers, _response_body: &[u8]) -> std::result::Result<crate::operation::import_config_toml::ImportConfigTomlOutput, crate::operation::import_config_toml::ImportConfigTomlError> {
    Ok({
        #[allow(unused_mut)]
        let mut output = crate::operation::import_config_toml::builders::ImportConfigTomlOutputBuilder::default();
        output = crate::protocol_serde::shape_import_config_toml::de_import_config_toml(_response_body, output).map_err(crate::operation::import_config_toml::ImportConfigTomlError::unhandled)?;
        crate::serde_util::import_config_toml_output_output_correct_errors(output).build().map_err(crate::operation::import_config_toml::ImportConfigTomlError::unhandled)?
    })
}

pub fn ser_import_config_toml_headers(
                    input: &crate::operation::import_config_toml::ImportConfigTomlInput,
                    mut builder: ::http::request::Builder
                ) -> std::result::Result<::http::request::Builder, ::aws_smithy_types::error::operation::BuildError> {
    if let ::std::option::Option::Some(inner_1) = &input.workspace_id {
        let formatted_2 = inner_1.as_str();
        let header_value = formatted_2;
                            let header_value: ::http::HeaderValue = header_value.parse().map_err(|err| {
                                ::aws_smithy_types::error::operation::BuildError::invalid_field("workspace_id", format!(
                                "`{}` cannot be used as a header value: {}",
                                &header_value,
                                err
                            ))
                            })?;
                            builder = builder.header("x-workspace", header_value);
    }
    if let ::std::option::Option::Some(inner_3) = &input.org_id {
        let formatted_4 = inner_3.as_str();
        let header_value = formatted_4;
                            let header_value: ::http::HeaderValue = header_value.parse().map_err(|err| {
                                ::aws_smithy_types::error::operation::BuildError::invalid_field("org_id", format!(
                                "`{}` cannot be used as a header value: {}",
                                &header_value,
                                err
                            ))
                            })?;
                            builder = builder.header("x-org-id", header_value);
    }
    if let ::std::option::Option::Some(inner_5) = &input.mode {
        let formatted_6 = inner_5.as_str();
        let header_value = formatted_6;
                            let header_value: ::http::HeaderValue = header_value.parse().map_err(|err| {
                                ::aws_smithy_types::error::operation::BuildError::invalid_field("mode", format!(
                                "`{}` cannot be used as a header value: {}",
                                &header_value,
                                err
                            ))
                            })?;
                            builder = builder.header("x-import-mode", header_value);
    }
    if let ::std::option::Option::Some(inner_7) = &input.overwrite {
        let mut encoder = ::aws_smithy_types::primitive::Encoder::from(*inner_7);
        let formatted_8 = encoder.encode();
        let header_value = formatted_8;
                            let header_value: ::http::HeaderValue = header_value.parse().map_err(|err| {
                                ::aws_smithy_types::error::operation::BuildError::invalid_field("overwrite", format!(
                                "`{}` cannot be used as a header value: {}",
                                &header_value,
                                err
                            ))
                            })?;
                            builder = builder.header("x-import-overwrite", header_value);
    }
    if let ::std::option::Option::Some(inner_9) = &input.on_error {
        let formatted_10 = inner_9.as_str();
        let header_value = formatted_10;
                            let header_value: ::http::HeaderValue = header_value.parse().map_err(|err| {
                                ::aws_smithy_types::error::operation::BuildError::invalid_field("on_error", format!(
                                "`{}` cannot be used as a header value: {}",
                                &header_value,
                                err
                            ))
                            })?;
                            builder = builder.header("x-import-on-error", header_value);
    }
    if let ::std::option::Option::Some(inner_11) = &input.dry_run {
        let mut encoder = ::aws_smithy_types::primitive::Encoder::from(*inner_11);
        let formatted_12 = encoder.encode();
        let header_value = formatted_12;
                            let header_value: ::http::HeaderValue = header_value.parse().map_err(|err| {
                                ::aws_smithy_types::error::operation::BuildError::invalid_field("dry_run", format!(
                                "`{}` cannot be used as a header value: {}",
                                &header_value,
                                err
                            ))
                            })?;
                            builder = builder.header("x-import-dry-run", header_value);
    }
    if let ::std::option::Option::Some(inner_13) = &input.value_merge {
        let mut encoder = ::aws_smithy_types::primitive::Encoder::from(*inner_13);
        let formatted_14 = encoder.encode();
        let header_value = formatted_14;
                            let header_value: ::http::HeaderValue = header_value.parse().map_err(|err| {
                                ::aws_smithy_types::error::operation::BuildError::invalid_field("value_merge", format!(
                                "`{}` cannot be used as a header value: {}",
                                &header_value,
                                err
                            ))
                            })?;
                            builder = builder.header("x-import-value-merge", header_value);
    }
    if let ::std::option::Option::Some(inner_15) = &input.config_tags {
        let formatted_16 = inner_15.as_str();
        let header_value = formatted_16;
                            let header_value: ::http::HeaderValue = header_value.parse().map_err(|err| {
                                ::aws_smithy_types::error::operation::BuildError::invalid_field("config_tags", format!(
                                "`{}` cannot be used as a header value: {}",
                                &header_value,
                                err
                            ))
                            })?;
                            builder = builder.header("x-config-tags", header_value);
    }
    Ok(builder)
}

pub(crate) fn de_import_config_toml(value: &[u8], mut builder: crate::operation::import_config_toml::builders::ImportConfigTomlOutputBuilder) -> ::std::result::Result<crate::operation::import_config_toml::builders::ImportConfigTomlOutputBuilder, ::aws_smithy_json::deserialize::error::DeserializeError> {
    let mut tokens_owned = ::aws_smithy_json::deserialize::json_token_iter(crate::protocol_serde::or_empty_doc(value)).peekable();
                        let tokens = &mut tokens_owned;
                        ::aws_smithy_json::deserialize::token::expect_start_object(tokens.next())?;
    loop {
        match tokens.next().transpose()? {
            Some(::aws_smithy_json::deserialize::Token::EndObject { .. }) => break,
                                    Some(::aws_smithy_json::deserialize::Token::ObjectKey { key, .. }) => {
                match key.to_unescaped()?.as_ref() {
                    "config_version" => {
                        builder = builder.set_config_version(
                            ::aws_smithy_json::deserialize::token::expect_string_or_null(tokens.next())?.map(|s|
                                s.to_unescaped().map(|u|
                                    u.into_owned()
                                )
                            ).transpose()?
                        );
                    }
                    "contexts" => {
                        builder = builder.set_contexts(
                            crate::protocol_serde::shape_import_entity_report::de_import_entity_report(tokens)?
                        );
                    }
                    "default_configs" => {
                        builder = builder.set_default_configs(
                            crate::protocol_serde::shape_import_entity_report::de_import_entity_report(tokens)?
                        );
                    }
                    "dimensions" => {
                        builder = builder.set_dimensions(
                            crate::protocol_serde::shape_import_entity_report::de_import_entity_report(tokens)?
                        );
                    }
                    "dry_run" => {
                        builder = builder.set_dry_run(
                            ::aws_smithy_json::deserialize::token::expect_bool_or_null(tokens.next())?
                        );
                    }
                    "mode" => {
                        builder = builder.set_mode(
                            ::aws_smithy_json::deserialize::token::expect_string_or_null(tokens.next())?.map(|s|
                                s.to_unescaped().map(|u|
                                    u.into_owned()
                                )
                            ).transpose()?
                        );
                    }
                    _ => ::aws_smithy_json::deserialize::token::skip_value(tokens)?
                }
            }
            other => return Err(::aws_smithy_json::deserialize::error::DeserializeError::custom(format!("expected object key or end object, found: {:?}", other)))
        }
    }
    if tokens.next().is_some() {
        return Err(::aws_smithy_json::deserialize::error::DeserializeError::custom("found more JSON tokens after completing parsing"));
    }
    Ok(builder)
}

