// Code generated by software.amazon.smithy.rust.codegen.smithy-rs. DO NOT EDIT.
pub(crate) fn de_context_action_out<'a, I>(tokens: &mut ::std::iter::Peekable<I>) -> ::std::result::Result<Option<crate::types::ContextActionOut>, ::aws_smithy_json::deserialize::error::DeserializeError>
                        where I: Iterator<Item = Result<::aws_smithy_json::deserialize::Token<'a>, ::aws_smithy_json::deserialize::error::DeserializeError>> {
    let mut variant = None;
    match tokens.next().transpose()? {
        Some(::aws_smithy_json::deserialize::Token::ValueNull { .. }) => return Ok(None),
                                    Some(::aws_smithy_json::deserialize::Token::StartObject { .. }) => {
            loop {
                match tokens.next().transpose()? {
                    Some(::aws_smithy_json::deserialize::Token::EndObject { .. }) => break,
                                            Some(::aws_smithy_json::deserialize::Token::ObjectKey { key, .. }) => {
                        if let ::std::option::Option::Some(::std::result::Result::Ok(::aws_smithy_json::deserialize::Token::ValueNull { .. })) = tokens.peek() {
                                                                let _ = tokens.next().expect("peek returned a token")?;
                                                                continue;
                                                            }
                        let key = key.to_unescaped()?;
                                                            if key == "__type" {
                                                                ::aws_smithy_json::deserialize::token::skip_value(tokens)?;
                                                                continue
                                                            }
                                                            if variant.is_some() {
                                                                return Err(::aws_smithy_json::deserialize::error::DeserializeError::custom("encountered mixed variants in union"));
                                                            }
                        variant = match key.as_ref() {
                            "PUT" => {
                                Some(crate::types::ContextActionOut::Put(
                                    crate::protocol_serde::shape_context_put_out::de_context_put_out(tokens)?
                                    .ok_or_else(|| ::aws_smithy_json::deserialize::error::DeserializeError::custom("value for 'PUT' cannot be null"))?
                                ))
                            }
                            "REPLACE" => {
                                Some(crate::types::ContextActionOut::Replace(
                                    crate::protocol_serde::shape_context_put_out::de_context_put_out(tokens)?
                                    .ok_or_else(|| ::aws_smithy_json::deserialize::error::DeserializeError::custom("value for 'REPLACE' cannot be null"))?
                                ))
                            }
                            "DELETE" => {
                                Some(crate::types::ContextActionOut::Delete(
                                    ::aws_smithy_json::deserialize::token::expect_string_or_null(tokens.next())?.map(|s|
                                        s.to_unescaped().map(|u|
                                            u.into_owned()
                                        )
                                    ).transpose()?
                                    .ok_or_else(|| ::aws_smithy_json::deserialize::error::DeserializeError::custom("value for 'DELETE' cannot be null"))?
                                ))
                            }
                            "MOVE" => {
                                Some(crate::types::ContextActionOut::Move(
                                    crate::protocol_serde::shape_context_move_out::de_context_move_out(tokens)?
                                    .ok_or_else(|| ::aws_smithy_json::deserialize::error::DeserializeError::custom("value for 'MOVE' cannot be null"))?
                                ))
                            }
                            _ => {
                                                                              ::aws_smithy_json::deserialize::token::skip_value(tokens)?;
                                                                              Some(crate::types::ContextActionOut::Unknown)
                                                                            }
                        };
                    }
                    other => return Err(::aws_smithy_json::deserialize::error::DeserializeError::custom(format!("expected object key or end object, found: {:?}", other)))
                }
            }
        }
        _ => return Err(::aws_smithy_json::deserialize::error::DeserializeError::custom("expected start object or null"))
    }
    if variant.is_none() {
                                return Err(::aws_smithy_json::deserialize::error::DeserializeError::custom("Union did not contain a valid variant."))
                            }
    Ok(variant)
}

