// Code generated by software.amazon.smithy.rust.codegen.smithy-rs. DO NOT EDIT.
pub(crate) fn de_json_config_payload(body: &[u8]) -> std::result::Result<::std::option::Option<::std::string::String>, crate::operation::get_config_json::GetConfigJsonError> {
    (!body.is_empty()).then(||{
        let body_str = std::str::from_utf8(body).map_err(crate::operation::get_config_json::GetConfigJsonError::unhandled)?;
        Ok(body_str.to_string())
    }).transpose()
}

pub(crate) fn de_last_modified_header(header_map: &::aws_smithy_runtime_api::http::Headers) -> ::std::result::Result<::std::option::Option<::aws_smithy_types::DateTime>, ::aws_smithy_http::header::ParseError> {
    let headers = header_map.get_all("last-modified");
    let var_1: Vec<::aws_smithy_types::DateTime> = ::aws_smithy_http::header::many_dates(headers, ::aws_smithy_types::date_time::Format::DateTimeWithOffset)?
    ;
    if var_1.len() > 1 {
                                Err(::aws_smithy_http::header::ParseError::new(format!("expected one item but found {}", var_1.len())))
                            } else {
                                let mut var_1 = var_1;
                                Ok(var_1.pop())
                            }
}

