# coding: utf-8

"""
    Superposition

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 2025-03-05
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from superposition_sdk_python.models.publish_response_content import PublishResponseContent

class TestPublishResponseContent(unittest.TestCase):
    """PublishResponseContent unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> PublishResponseContent:
        """Test PublishResponseContent
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `PublishResponseContent`
        """
        model = PublishResponseContent()
        if include_optional:
            return PublishResponseContent(
                function_name = '',
                published_code = '',
                draft_code = '',
                published_runtime_version = '',
                draft_runtime_version = '',
                published_at = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'),
                draft_edited_at = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'),
                published_by = '',
                draft_edited_by = '',
                last_modified_at = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'),
                last_modified_by = '',
                change_reason = '',
                description = ''
            )
        else:
            return PublishResponseContent(
                function_name = '',
                draft_code = '',
                draft_runtime_version = '',
                draft_edited_at = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'),
                draft_edited_by = '',
                last_modified_at = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'),
                last_modified_by = '',
                change_reason = '',
                description = '',
        )
        """

    def testPublishResponseContent(self):
        """Test PublishResponseContent"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
