# coding: utf-8

"""
    Superposition

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 2025-03-05
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from superposition_sdk_python.models.list_versions_response_content import ListVersionsResponseContent

class TestListVersionsResponseContent(unittest.TestCase):
    """ListVersionsResponseContent unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> ListVersionsResponseContent:
        """Test ListVersionsResponseContent
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `ListVersionsResponseContent`
        """
        model = ListVersionsResponseContent()
        if include_optional:
            return ListVersionsResponseContent(
                total_pages = 1.337,
                total_items = 1.337,
                data = [
                    ''
                    ]
            )
        else:
            return ListVersionsResponseContent(
        )
        """

    def testListVersionsResponseContent(self):
        """Test ListVersionsResponseContent"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
