// Code generated by software.amazon.smithy.rust.codegen.smithy-rs. DO NOT EDIT.
#[allow(missing_docs)] // documentation missing in model
#[non_exhaustive]
#[derive(::std::clone::Clone, ::std::cmp::PartialEq, ::std::fmt::Debug)]
pub struct DeleteFunctionOutput  {
}
impl DeleteFunctionOutput {
    /// Creates a new builder-style object to manufacture [`DeleteFunctionOutput`](crate::operation::delete_function::DeleteFunctionOutput).
    pub fn builder() -> crate::operation::delete_function::builders::DeleteFunctionOutputBuilder {
        crate::operation::delete_function::builders::DeleteFunctionOutputBuilder::default()
    }
}

/// A builder for [`DeleteFunctionOutput`](crate::operation::delete_function::DeleteFunctionOutput).
#[derive(::std::clone::Clone, ::std::cmp::PartialEq, ::std::default::Default, ::std::fmt::Debug)]
#[non_exhaustive]
pub struct DeleteFunctionOutputBuilder {
}
impl DeleteFunctionOutputBuilder {
    /// Consumes the builder and constructs a [`DeleteFunctionOutput`](crate::operation::delete_function::DeleteFunctionOutput).
    pub fn build(self) -> crate::operation::delete_function::DeleteFunctionOutput {
        crate::operation::delete_function::DeleteFunctionOutput {
        }
    }
}

