# coding: utf-8

"""
    Superposition

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 2025-03-05
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from datetime import datetime
from pydantic import BaseModel, ConfigDict, StrictStr
from typing import Any, ClassVar, Dict, List, Optional
from typing import Optional, Set
from typing_extensions import Self

class WorkspaceResponse(BaseModel):
    """
    WorkspaceResponse
    """ # noqa: E501
    workspace_name: StrictStr
    organisation_id: StrictStr
    organisation_name: StrictStr
    workspace_schema_name: StrictStr
    workspace_status: StrictStr
    workspace_admin_email: StrictStr
    created_by: StrictStr
    last_modified_by: StrictStr
    last_modified_at: datetime
    created_at: datetime
    mandatory_dimensions: Optional[List[StrictStr]] = None
    __properties: ClassVar[List[str]] = ["workspace_name", "organisation_id", "organisation_name", "workspace_schema_name", "workspace_status", "workspace_admin_email", "created_by", "last_modified_by", "last_modified_at", "created_at", "mandatory_dimensions"]

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of WorkspaceResponse from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of WorkspaceResponse from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "workspace_name": obj.get("workspace_name"),
            "organisation_id": obj.get("organisation_id"),
            "organisation_name": obj.get("organisation_name"),
            "workspace_schema_name": obj.get("workspace_schema_name"),
            "workspace_status": obj.get("workspace_status"),
            "workspace_admin_email": obj.get("workspace_admin_email"),
            "created_by": obj.get("created_by"),
            "last_modified_by": obj.get("last_modified_by"),
            "last_modified_at": obj.get("last_modified_at"),
            "created_at": obj.get("created_at"),
            "mandatory_dimensions": obj.get("mandatory_dimensions")
        })
        return _obj


