// Code generated by software.amazon.smithy.rust.codegen.smithy-rs. DO NOT EDIT.
pub use crate::operation::create_organisation::_create_organisation_output::CreateOrganisationOutputBuilder;

pub use crate::operation::create_organisation::_create_organisation_input::CreateOrganisationInputBuilder;

impl crate::operation::create_organisation::builders::CreateOrganisationInputBuilder {
                    /// Sends a request with this input using the given client.
                    pub async fn send_with(self, client: &crate::Client) -> ::std::result::Result<
                        crate::operation::create_organisation::CreateOrganisationOutput,
                        ::aws_smithy_runtime_api::client::result::SdkError<
                            crate::operation::create_organisation::CreateOrganisationError,
                            ::aws_smithy_runtime_api::client::orchestrator::HttpResponse
                        >
                    > {
                        let mut fluent_builder = client.create_organisation();
                        fluent_builder.inner = self;
                        fluent_builder.send().await
                    }
                }
/// Fluent builder constructing a request to `CreateOrganisation`.
/// 
/// Creates a new organisation with specified details including name, admin contact, and organisational information.
#[derive(::std::clone::Clone, ::std::fmt::Debug)]
pub struct CreateOrganisationFluentBuilder {
                handle: ::std::sync::Arc<crate::client::Handle>,
                inner: crate::operation::create_organisation::builders::CreateOrganisationInputBuilder,
config_override: ::std::option::Option<crate::config::Builder>,
            }
impl
                crate::client::customize::internal::CustomizableSend<
                    crate::operation::create_organisation::CreateOrganisationOutput,
                    crate::operation::create_organisation::CreateOrganisationError,
                > for CreateOrganisationFluentBuilder
            {
                fn send(
                    self,
                    config_override: crate::config::Builder,
                ) -> crate::client::customize::internal::BoxFuture<
                    crate::client::customize::internal::SendResult<
                        crate::operation::create_organisation::CreateOrganisationOutput,
                        crate::operation::create_organisation::CreateOrganisationError,
                    >,
                > {
                    ::std::boxed::Box::pin(async move { self.config_override(config_override).send().await })
                }
            }
impl CreateOrganisationFluentBuilder {
    /// Creates a new `CreateOrganisationFluentBuilder`.
                    pub(crate) fn new(handle: ::std::sync::Arc<crate::client::Handle>) -> Self {
                        Self {
                            handle,
                            inner: ::std::default::Default::default(),
    config_override: ::std::option::Option::None,
                        }
                    }
    /// Access the CreateOrganisation as a reference.
                    pub fn as_input(&self) -> &crate::operation::create_organisation::builders::CreateOrganisationInputBuilder {
                        &self.inner
                    }
    /// Sends the request and returns the response.
                    ///
                    /// If an error occurs, an `SdkError` will be returned with additional details that
                    /// can be matched against.
                    ///
                    /// By default, any retryable failures will be retried twice. Retry behavior
                    /// is configurable with the [RetryConfig](aws_smithy_types::retry::RetryConfig), which can be
                    /// set when configuring the client.
                    pub async fn send(self) -> ::std::result::Result<crate::operation::create_organisation::CreateOrganisationOutput, ::aws_smithy_runtime_api::client::result::SdkError<crate::operation::create_organisation::CreateOrganisationError, ::aws_smithy_runtime_api::client::orchestrator::HttpResponse>> {
                        let input = self.inner.build().map_err(::aws_smithy_runtime_api::client::result::SdkError::construction_failure)?;
                        let runtime_plugins = crate::operation::create_organisation::CreateOrganisation::operation_runtime_plugins(
                            self.handle.runtime_plugins.clone(),
                            &self.handle.conf,
                            self.config_override,
                        );
                        crate::operation::create_organisation::CreateOrganisation::orchestrate(&runtime_plugins, input).await
                    }
    
                    /// Consumes this builder, creating a customizable operation that can be modified before being sent.
                    pub fn customize(
                        self,
                    ) -> crate::client::customize::CustomizableOperation<crate::operation::create_organisation::CreateOrganisationOutput, crate::operation::create_organisation::CreateOrganisationError, Self> {
                        crate::client::customize::CustomizableOperation::new(self)
                    }
    pub(crate) fn config_override(
                            mut self,
                            config_override: impl ::std::convert::Into<crate::config::Builder>,
                        ) -> Self {
                            self.set_config_override(::std::option::Option::Some(config_override.into()));
                            self
                        }
    
                        pub(crate) fn set_config_override(
                            &mut self,
                            config_override: ::std::option::Option<crate::config::Builder>,
                        ) -> &mut Self {
                            self.config_override = config_override;
                            self
                        }
    #[allow(missing_docs)] // documentation missing in model
    pub fn country_code(mut self, input: impl ::std::convert::Into<::std::string::String>) -> Self {
                    self.inner = self.inner.country_code(input.into());
                    self
                }
    #[allow(missing_docs)] // documentation missing in model
    pub fn set_country_code(mut self, input: ::std::option::Option<::std::string::String>) -> Self {
                    self.inner = self.inner.set_country_code(input);
                    self
                }
    #[allow(missing_docs)] // documentation missing in model
    pub fn get_country_code(&self) -> &::std::option::Option<::std::string::String> {
                    self.inner.get_country_code()
                }
    #[allow(missing_docs)] // documentation missing in model
    pub fn contact_email(mut self, input: impl ::std::convert::Into<::std::string::String>) -> Self {
                    self.inner = self.inner.contact_email(input.into());
                    self
                }
    #[allow(missing_docs)] // documentation missing in model
    pub fn set_contact_email(mut self, input: ::std::option::Option<::std::string::String>) -> Self {
                    self.inner = self.inner.set_contact_email(input);
                    self
                }
    #[allow(missing_docs)] // documentation missing in model
    pub fn get_contact_email(&self) -> &::std::option::Option<::std::string::String> {
                    self.inner.get_contact_email()
                }
    #[allow(missing_docs)] // documentation missing in model
    pub fn contact_phone(mut self, input: impl ::std::convert::Into<::std::string::String>) -> Self {
                    self.inner = self.inner.contact_phone(input.into());
                    self
                }
    #[allow(missing_docs)] // documentation missing in model
    pub fn set_contact_phone(mut self, input: ::std::option::Option<::std::string::String>) -> Self {
                    self.inner = self.inner.set_contact_phone(input);
                    self
                }
    #[allow(missing_docs)] // documentation missing in model
    pub fn get_contact_phone(&self) -> &::std::option::Option<::std::string::String> {
                    self.inner.get_contact_phone()
                }
    #[allow(missing_docs)] // documentation missing in model
    pub fn admin_email(mut self, input: impl ::std::convert::Into<::std::string::String>) -> Self {
                    self.inner = self.inner.admin_email(input.into());
                    self
                }
    #[allow(missing_docs)] // documentation missing in model
    pub fn set_admin_email(mut self, input: ::std::option::Option<::std::string::String>) -> Self {
                    self.inner = self.inner.set_admin_email(input);
                    self
                }
    #[allow(missing_docs)] // documentation missing in model
    pub fn get_admin_email(&self) -> &::std::option::Option<::std::string::String> {
                    self.inner.get_admin_email()
                }
    #[allow(missing_docs)] // documentation missing in model
    pub fn sector(mut self, input: impl ::std::convert::Into<::std::string::String>) -> Self {
                    self.inner = self.inner.sector(input.into());
                    self
                }
    #[allow(missing_docs)] // documentation missing in model
    pub fn set_sector(mut self, input: ::std::option::Option<::std::string::String>) -> Self {
                    self.inner = self.inner.set_sector(input);
                    self
                }
    #[allow(missing_docs)] // documentation missing in model
    pub fn get_sector(&self) -> &::std::option::Option<::std::string::String> {
                    self.inner.get_sector()
                }
    #[allow(missing_docs)] // documentation missing in model
    pub fn name(mut self, input: impl ::std::convert::Into<::std::string::String>) -> Self {
                    self.inner = self.inner.name(input.into());
                    self
                }
    #[allow(missing_docs)] // documentation missing in model
    pub fn set_name(mut self, input: ::std::option::Option<::std::string::String>) -> Self {
                    self.inner = self.inner.set_name(input);
                    self
                }
    #[allow(missing_docs)] // documentation missing in model
    pub fn get_name(&self) -> &::std::option::Option<::std::string::String> {
                    self.inner.get_name()
                }
}

