import type { SidebarsConfig } from "@docusaurus/plugin-content-docs";

const sidebar: SidebarsConfig = {
  apisidebar: [
    {
      type: "doc",
      id: "api/superposition",
    },
    {
      type: "category",
      label: "Audit & Monitoring",
      collapsed: false,
      items: [
        {
          type: "doc",
          id: "api/list-audit-logs",
          label: "ListAuditLogs",
          customProps: {},
          className: "api-method get",
        },
      ],
    },
    {
      type: "category",
      label: "Configuration Management",
      collapsed: false,
      items: [
        {
          type: "doc",
          id: "api/get-config",
          label: "GetConfig",
          customProps: {},
          className: "api-method post",
        },
        {
          type: "doc",
          id: "api/get-config-fast",
          label: "GetConfigFast",
          customProps: {},
          className: "api-method get",
        },
        {
          type: "doc",
          id: "api/get-resolved-config",
          label: "GetResolvedConfig",
          customProps: {},
          className: "api-method post",
        },
        {
          type: "doc",
          id: "api/list-versions",
          label: "ListVersions",
          customProps: {},
          className: "api-method get",
        },
        {
          type: "doc",
          id: "api/get-resolved-config-with-identifier",
          label: "GetResolvedConfigWithIdentifier",
          customProps: {},
          className: "api-method post",
        },
        {
          type: "doc",
          id: "api/get-version",
          label: "GetVersion",
          customProps: {},
          className: "api-method get",
        },
      ],
    },
    {
      type: "category",
      label: "Context Management",
      collapsed: false,
      items: [
        {
          type: "doc",
          id: "api/list-contexts",
          label: "ListContexts",
          customProps: {},
          className: "api-method get",
        },
        {
          type: "doc",
          id: "api/create-context",
          label: "CreateContext",
          customProps: {},
          className: "api-method put",
        },
        {
          type: "doc",
          id: "api/bulk-operation",
          label: "BulkOperation",
          customProps: {},
          className: "api-method put",
        },
        {
          type: "doc",
          id: "api/get-context-from-condition",
          label: "GetContextFromCondition",
          customProps: {},
          className: "api-method post",
        },
        {
          type: "doc",
          id: "api/move-context",
          label: "MoveContext",
          customProps: {},
          className: "api-method put",
        },
        {
          type: "doc",
          id: "api/update-override",
          label: "UpdateOverride",
          customProps: {},
          className: "api-method patch",
        },
        {
          type: "doc",
          id: "api/validate-context",
          label: "ValidateContext",
          customProps: {},
          className: "api-method put",
        },
        {
          type: "doc",
          id: "api/weight-recompute",
          label: "WeightRecompute",
          customProps: {},
          className: "api-method put",
        },
        {
          type: "doc",
          id: "api/delete-context",
          label: "DeleteContext",
          customProps: {},
          className: "api-method delete",
        },
        {
          type: "doc",
          id: "api/get-context",
          label: "GetContext",
          customProps: {},
          className: "api-method get",
        },
      ],
    },
    {
      type: "category",
      label: "Default Configuration",
      collapsed: false,
      items: [
        {
          type: "doc",
          id: "api/list-default-configs",
          label: "ListDefaultConfigs",
          customProps: {},
          className: "api-method get",
        },
        {
          type: "doc",
          id: "api/create-default-config",
          label: "CreateDefaultConfig",
          customProps: {},
          className: "api-method post",
        },
        {
          type: "doc",
          id: "api/delete-default-config",
          label: "DeleteDefaultConfig",
          customProps: {},
          className: "api-method delete",
        },
        {
          type: "doc",
          id: "api/get-default-config",
          label: "GetDefaultConfig",
          customProps: {},
          className: "api-method get",
        },
        {
          type: "doc",
          id: "api/update-default-config",
          label: "UpdateDefaultConfig",
          customProps: {},
          className: "api-method patch",
        },
      ],
    },
    {
      type: "category",
      label: "Dimensions",
      collapsed: false,
      items: [
        {
          type: "doc",
          id: "api/list-dimensions",
          label: "ListDimensions",
          customProps: {},
          className: "api-method get",
        },
        {
          type: "doc",
          id: "api/create-dimension",
          label: "CreateDimension",
          customProps: {},
          className: "api-method post",
        },
        {
          type: "doc",
          id: "api/delete-dimension",
          label: "DeleteDimension",
          customProps: {},
          className: "api-method delete",
        },
        {
          type: "doc",
          id: "api/get-dimension",
          label: "GetDimension",
          customProps: {},
          className: "api-method get",
        },
        {
          type: "doc",
          id: "api/update-dimension",
          label: "UpdateDimension",
          customProps: {},
          className: "api-method patch",
        },
      ],
    },
    {
      type: "category",
      label: "Experiment Groups",
      collapsed: false,
      items: [
        {
          type: "doc",
          id: "api/list-experiment-groups",
          label: "ListExperimentGroups",
          customProps: {},
          className: "api-method get",
        },
        {
          type: "doc",
          id: "api/create-experiment-group",
          label: "CreateExperimentGroup",
          customProps: {},
          className: "api-method post",
        },
        {
          type: "doc",
          id: "api/delete-experiment-group",
          label: "DeleteExperimentGroup",
          customProps: {},
          className: "api-method delete",
        },
        {
          type: "doc",
          id: "api/get-experiment-group",
          label: "GetExperimentGroup",
          customProps: {},
          className: "api-method get",
        },
        {
          type: "doc",
          id: "api/update-experiment-group",
          label: "UpdateExperimentGroup",
          customProps: {},
          className: "api-method patch",
        },
        {
          type: "doc",
          id: "api/add-members-to-group",
          label: "AddMembersToGroup",
          customProps: {},
          className: "api-method patch",
        },
        {
          type: "doc",
          id: "api/remove-members-from-group",
          label: "RemoveMembersFromGroup",
          customProps: {},
          className: "api-method patch",
        },
      ],
    },
    {
      type: "category",
      label: "Experimentation",
      collapsed: false,
      items: [
        {
          type: "doc",
          id: "api/list-experiment",
          label: "ListExperiment",
          customProps: {},
          className: "api-method get",
        },
        {
          type: "doc",
          id: "api/create-experiment",
          label: "CreateExperiment",
          customProps: {},
          className: "api-method post",
        },
        {
          type: "doc",
          id: "api/applicable-variants",
          label: "ApplicableVariants",
          customProps: {},
          className: "api-method post",
        },
        {
          type: "doc",
          id: "api/get-experiment",
          label: "GetExperiment",
          customProps: {},
          className: "api-method get",
        },
        {
          type: "doc",
          id: "api/conclude-experiment",
          label: "ConcludeExperiment",
          customProps: {},
          className: "api-method patch",
        },
        {
          type: "doc",
          id: "api/discard-experiment",
          label: "DiscardExperiment",
          customProps: {},
          className: "api-method patch",
        },
        {
          type: "doc",
          id: "api/update-overrides-experiment",
          label: "UpdateOverridesExperiment",
          customProps: {},
          className: "api-method patch",
        },
        {
          type: "doc",
          id: "api/pause-experiment",
          label: "PauseExperiment",
          customProps: {},
          className: "api-method patch",
        },
        {
          type: "doc",
          id: "api/ramp-experiment",
          label: "RampExperiment",
          customProps: {},
          className: "api-method patch",
        },
        {
          type: "doc",
          id: "api/resume-experiment",
          label: "ResumeExperiment",
          customProps: {},
          className: "api-method patch",
        },
      ],
    },
    {
      type: "category",
      label: "Functions",
      collapsed: false,
      items: [
        {
          type: "doc",
          id: "api/list-function",
          label: "ListFunction",
          customProps: {},
          className: "api-method get",
        },
        {
          type: "doc",
          id: "api/create-function",
          label: "CreateFunction",
          customProps: {},
          className: "api-method post",
        },
        {
          type: "doc",
          id: "api/delete-function",
          label: "DeleteFunction",
          customProps: {},
          className: "api-method delete",
        },
        {
          type: "doc",
          id: "api/get-function",
          label: "GetFunction",
          customProps: {},
          className: "api-method get",
        },
        {
          type: "doc",
          id: "api/update-function",
          label: "UpdateFunction",
          customProps: {},
          className: "api-method patch",
        },
        {
          type: "doc",
          id: "api/publish",
          label: "Publish",
          customProps: {},
          className: "api-method patch",
        },
        {
          type: "doc",
          id: "api/test",
          label: "Test",
          customProps: {},
          className: "api-method post",
        },
      ],
    },
    {
      type: "category",
      label: "Organisation Management",
      collapsed: false,
      items: [
        {
          type: "doc",
          id: "api/list-organisation",
          label: "ListOrganisation",
          customProps: {},
          className: "api-method get",
        },
        {
          type: "doc",
          id: "api/create-organisation",
          label: "CreateOrganisation",
          customProps: {},
          className: "api-method post",
        },
        {
          type: "doc",
          id: "api/get-organisation",
          label: "GetOrganisation",
          customProps: {},
          className: "api-method get",
        },
        {
          type: "doc",
          id: "api/update-organisation",
          label: "UpdateOrganisation",
          customProps: {},
          className: "api-method patch",
        },
      ],
    },
    {
      type: "category",
      label: "Type Templates",
      collapsed: false,
      items: [
        {
          type: "doc",
          id: "api/get-type-templates-list",
          label: "GetTypeTemplatesList",
          customProps: {},
          className: "api-method get",
        },
        {
          type: "doc",
          id: "api/create-type-templates",
          label: "CreateTypeTemplates",
          customProps: {},
          className: "api-method post",
        },
        {
          type: "doc",
          id: "api/delete-type-templates",
          label: "DeleteTypeTemplates",
          customProps: {},
          className: "api-method delete",
        },
        {
          type: "doc",
          id: "api/get-type-template",
          label: "GetTypeTemplate",
          customProps: {},
          className: "api-method get",
        },
        {
          type: "doc",
          id: "api/update-type-templates",
          label: "UpdateTypeTemplates",
          customProps: {},
          className: "api-method patch",
        },
      ],
    },
    {
      type: "category",
      label: "Variables",
      collapsed: false,
      items: [
        {
          type: "doc",
          id: "api/list-variables",
          label: "ListVariables",
          customProps: {},
          className: "api-method get",
        },
        {
          type: "doc",
          id: "api/create-variable",
          label: "CreateVariable",
          customProps: {},
          className: "api-method post",
        },
        {
          type: "doc",
          id: "api/delete-variable",
          label: "DeleteVariable",
          customProps: {},
          className: "api-method delete",
        },
        {
          type: "doc",
          id: "api/get-variable",
          label: "GetVariable",
          customProps: {},
          className: "api-method get",
        },
        {
          type: "doc",
          id: "api/update-variable",
          label: "UpdateVariable",
          customProps: {},
          className: "api-method patch",
        },
      ],
    },
    {
      type: "category",
      label: "Webhooks",
      collapsed: false,
      items: [
        {
          type: "doc",
          id: "api/list-webhook",
          label: "ListWebhook",
          customProps: {},
          className: "api-method get",
        },
        {
          type: "doc",
          id: "api/create-webhook",
          label: "CreateWebhook",
          customProps: {},
          className: "api-method post",
        },
        {
          type: "doc",
          id: "api/get-webhook-by-event",
          label: "GetWebhookByEvent",
          customProps: {},
          className: "api-method get",
        },
        {
          type: "doc",
          id: "api/delete-webhook",
          label: "DeleteWebhook",
          customProps: {},
          className: "api-method delete",
        },
        {
          type: "doc",
          id: "api/get-webhook",
          label: "GetWebhook",
          customProps: {},
          className: "api-method get",
        },
        {
          type: "doc",
          id: "api/update-webhook",
          label: "UpdateWebhook",
          customProps: {},
          className: "api-method patch",
        },
      ],
    },
    {
      type: "category",
      label: "Workspace Management",
      collapsed: false,
      items: [
        {
          type: "doc",
          id: "api/list-workspace",
          label: "ListWorkspace",
          customProps: {},
          className: "api-method get",
        },
        {
          type: "doc",
          id: "api/create-workspace",
          label: "CreateWorkspace",
          customProps: {},
          className: "api-method post",
        },
        {
          type: "doc",
          id: "api/get-workspace",
          label: "GetWorkspace",
          customProps: {},
          className: "api-method get",
        },
        {
          type: "doc",
          id: "api/update-workspace",
          label: "UpdateWorkspace",
          customProps: {},
          className: "api-method patch",
        },
        {
          type: "doc",
          id: "api/migrate-workspace-schema",
          label: "MigrateWorkspaceSchema",
          customProps: {},
          className: "api-method post",
        },
      ],
    },
  ],
};

export default sidebar.apisidebar;
