[request_definition] 
r = sub, dom, obj, act, attr

[policy_definition] 
p = sub, dom, obj, act, attr

[role_definition] 
# USER_MAINTAINED (user - user_group - workspace_schema)
g = _, _, _
# SYTEM_MAINTAINED (resource - action - action_group)
g2 = _, _, _ 
# USER_MAINTAINED (resource:action - workspace_schema - action_group)
g3 = _, _, _

[policy_effect] 
e = some(where (p.eft == allow))

[matchers] 
m = (r.dom == p.dom || p.dom == "*") && (r.sub == p.sub || g(r.sub, p.sub, p.dom) || g(r.sub, p.sub, r.dom)) && (r.obj == p.obj || p.obj == "*") && (r.act == p.act || p.act == "*" || g2(r.obj, r.act, p.act) == true || g3(r.obj + ":" + r.act, r.dom, p.act)) && (r.attr == "*" || p.attr == "*" || globMatch(r.attr, p.attr))

[policies]
p, admin, *, *, *, *
p, *, *, workspace, read, *
p, reader, *, *, read, *

g2, context, get, read
g2, context, get_from_context, read
g2, context, list, read
# g2, context, validate, read
p, context_reader, *, context, read, *

g2, dimension, get, read
g2, dimension, list, read
p, dimension_reader, *, dimension, read, *

g2, default_config, get, read
g2, default_config, list, read
p, default_config_reader, *, default_config, read, *

g2, config, get, read
g2, config, resolve, read
g2, config, list_version, read
g2, config, get_version, read
p, config_reader, *, config, read, *

g2, audit_log, list, read
p, audit_log_reader, *, audit_log, read, *

g2, function, get, read
g2, function, list, read
# g2, function, test, read
p, function_reader, *, function, read, *

g2, type_template, get, read
g2, type_template, list, read
p, type_template_reader, *, type_template, read, *

g2, experiment, get, read
g2, experiment, list, read
g2, experiment, get_applicable_variants, read
p, experiment_reader, *, experiment, read, *

g2, experiment_group, get, read
g2, experiment_group, list, read
p, experiment_group_reader, *, experiment_group, read, *

g2, variable, get, read
g2, variable, list, read
p, variable_reader, *, variable, read, *

g2, webhook, get, read
g2, webhook, list, read
g2, webhook, get_by_event, read
p, webhook_reader, *, webhook, read, *

g2, workspace, get, read
g2, workspace, list, read
p, workspace_reader, *, workspace, read, *

# ayush -> qa 
# qa -> default_Config.login.* -> write
# qa -> function.* -> write 


g, ayush_test, qa, o1_w1
p, qa, o1_w1, default_config, write, login.*
p, qa, o1_w1, function, write, *
g3, default_config:create, o1_w1, write





# p, test, o1_w1, config, get, *
g, test, reader, o1_w1

# adding groups in g will be workspace specific over API
# separate API for adding root_user role to a user, by setting dom to *
g, ayush, admin, o1_w1
g, ayush, admin, o1_w2
g, nata, admin, o2_w1
g, boaz, admin, *
