[request_definition] 
r = sub, dom, obj, act, attr

[policy_definition] 
p = sub, dom, obj, act, attr

[role_definition] 
g = _, _, _ 
g3 = _, _, _ 

[policy_effect] 
e = some(where (p.eft == allow))

[matchers] 
m = (r.dom == p.dom || p.dom == "*") && (r.sub == p.sub || g(r.sub, p.sub, p.dom) || g(r.sub, p.sub, r.dom)) && (r.obj == p.obj || p.obj == "*") && (r.act == p.act || p.act == "*" || g3(r.obj, r.act, p.act) == true) && (r.attr == "*" || p.attr == "*" || globMatch(r.attr, p.attr))

[policies]
p, kat, o1_w1, config, get
p, admin, *, *, *
# p, root_user, *, *, *
p, reader, *, *, read
p, writer, *, *, write

# adding groups in g will be workspace specific over API
# separate API for adding root_user role to a user, by setting dom to *
g, ayush, admin, o1_w1
g, ayush, admin, o1_w2
g, nata, admin, o2_w1
g, boaz, admin, *
# g, boaz, root_user, *

g3, config, get, read
g3, config, list, read 
g3, config, resolve, read 