/*
Superposition

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 2025-03-05
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package superposition_sdk_go

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the CreateDimensionRequestContent type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &CreateDimensionRequestContent{}

// CreateDimensionRequestContent struct for CreateDimensionRequestContent
type CreateDimensionRequestContent struct {
	Dimension string `json:"dimension"`
	Position float32 `json:"position"`
	Schema interface{} `json:"schema"`
	FunctionName *string `json:"function_name,omitempty"`
	Description string `json:"description"`
	ChangeReason string `json:"change_reason"`
}

type _CreateDimensionRequestContent CreateDimensionRequestContent

// NewCreateDimensionRequestContent instantiates a new CreateDimensionRequestContent object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewCreateDimensionRequestContent(dimension string, position float32, schema interface{}, description string, changeReason string) *CreateDimensionRequestContent {
	this := CreateDimensionRequestContent{}
	this.Dimension = dimension
	this.Position = position
	this.Schema = schema
	this.Description = description
	this.ChangeReason = changeReason
	return &this
}

// NewCreateDimensionRequestContentWithDefaults instantiates a new CreateDimensionRequestContent object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewCreateDimensionRequestContentWithDefaults() *CreateDimensionRequestContent {
	this := CreateDimensionRequestContent{}
	return &this
}

// GetDimension returns the Dimension field value
func (o *CreateDimensionRequestContent) GetDimension() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Dimension
}

// GetDimensionOk returns a tuple with the Dimension field value
// and a boolean to check if the value has been set.
func (o *CreateDimensionRequestContent) GetDimensionOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Dimension, true
}

// SetDimension sets field value
func (o *CreateDimensionRequestContent) SetDimension(v string) {
	o.Dimension = v
}

// GetPosition returns the Position field value
func (o *CreateDimensionRequestContent) GetPosition() float32 {
	if o == nil {
		var ret float32
		return ret
	}

	return o.Position
}

// GetPositionOk returns a tuple with the Position field value
// and a boolean to check if the value has been set.
func (o *CreateDimensionRequestContent) GetPositionOk() (*float32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Position, true
}

// SetPosition sets field value
func (o *CreateDimensionRequestContent) SetPosition(v float32) {
	o.Position = v
}

// GetSchema returns the Schema field value
// If the value is explicit nil, the zero value for interface{} will be returned
func (o *CreateDimensionRequestContent) GetSchema() interface{} {
	if o == nil {
		var ret interface{}
		return ret
	}

	return o.Schema
}

// GetSchemaOk returns a tuple with the Schema field value
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *CreateDimensionRequestContent) GetSchemaOk() (*interface{}, bool) {
	if o == nil || IsNil(o.Schema) {
		return nil, false
	}
	return &o.Schema, true
}

// SetSchema sets field value
func (o *CreateDimensionRequestContent) SetSchema(v interface{}) {
	o.Schema = v
}

// GetFunctionName returns the FunctionName field value if set, zero value otherwise.
func (o *CreateDimensionRequestContent) GetFunctionName() string {
	if o == nil || IsNil(o.FunctionName) {
		var ret string
		return ret
	}
	return *o.FunctionName
}

// GetFunctionNameOk returns a tuple with the FunctionName field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CreateDimensionRequestContent) GetFunctionNameOk() (*string, bool) {
	if o == nil || IsNil(o.FunctionName) {
		return nil, false
	}
	return o.FunctionName, true
}

// HasFunctionName returns a boolean if a field has been set.
func (o *CreateDimensionRequestContent) HasFunctionName() bool {
	if o != nil && !IsNil(o.FunctionName) {
		return true
	}

	return false
}

// SetFunctionName gets a reference to the given string and assigns it to the FunctionName field.
func (o *CreateDimensionRequestContent) SetFunctionName(v string) {
	o.FunctionName = &v
}

// GetDescription returns the Description field value
func (o *CreateDimensionRequestContent) GetDescription() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Description
}

// GetDescriptionOk returns a tuple with the Description field value
// and a boolean to check if the value has been set.
func (o *CreateDimensionRequestContent) GetDescriptionOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Description, true
}

// SetDescription sets field value
func (o *CreateDimensionRequestContent) SetDescription(v string) {
	o.Description = v
}

// GetChangeReason returns the ChangeReason field value
func (o *CreateDimensionRequestContent) GetChangeReason() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.ChangeReason
}

// GetChangeReasonOk returns a tuple with the ChangeReason field value
// and a boolean to check if the value has been set.
func (o *CreateDimensionRequestContent) GetChangeReasonOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.ChangeReason, true
}

// SetChangeReason sets field value
func (o *CreateDimensionRequestContent) SetChangeReason(v string) {
	o.ChangeReason = v
}

func (o CreateDimensionRequestContent) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o CreateDimensionRequestContent) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["dimension"] = o.Dimension
	toSerialize["position"] = o.Position
	if o.Schema != nil {
		toSerialize["schema"] = o.Schema
	}
	if !IsNil(o.FunctionName) {
		toSerialize["function_name"] = o.FunctionName
	}
	toSerialize["description"] = o.Description
	toSerialize["change_reason"] = o.ChangeReason
	return toSerialize, nil
}

func (o *CreateDimensionRequestContent) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"dimension",
		"position",
		"schema",
		"description",
		"change_reason",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varCreateDimensionRequestContent := _CreateDimensionRequestContent{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varCreateDimensionRequestContent)

	if err != nil {
		return err
	}

	*o = CreateDimensionRequestContent(varCreateDimensionRequestContent)

	return err
}

type NullableCreateDimensionRequestContent struct {
	value *CreateDimensionRequestContent
	isSet bool
}

func (v NullableCreateDimensionRequestContent) Get() *CreateDimensionRequestContent {
	return v.value
}

func (v *NullableCreateDimensionRequestContent) Set(val *CreateDimensionRequestContent) {
	v.value = val
	v.isSet = true
}

func (v NullableCreateDimensionRequestContent) IsSet() bool {
	return v.isSet
}

func (v *NullableCreateDimensionRequestContent) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableCreateDimensionRequestContent(val *CreateDimensionRequestContent) *NullableCreateDimensionRequestContent {
	return &NullableCreateDimensionRequestContent{value: val, isSet: true}
}

func (v NullableCreateDimensionRequestContent) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableCreateDimensionRequestContent) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


