/*
Superposition

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 2025-03-05
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package superposition_sdk_go

import (
	"encoding/json"
	"time"
	"bytes"
	"fmt"
)

// checks if the GetFunctionResponseContent type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &GetFunctionResponseContent{}

// GetFunctionResponseContent struct for GetFunctionResponseContent
type GetFunctionResponseContent struct {
	FunctionName string `json:"function_name"`
	PublishedCode *string `json:"published_code,omitempty"`
	DraftCode string `json:"draft_code"`
	PublishedRuntimeVersion *string `json:"published_runtime_version,omitempty"`
	DraftRuntimeVersion string `json:"draft_runtime_version"`
	PublishedAt *time.Time `json:"published_at,omitempty"`
	DraftEditedAt time.Time `json:"draft_edited_at"`
	PublishedBy *string `json:"published_by,omitempty"`
	DraftEditedBy string `json:"draft_edited_by"`
	LastModifiedAt time.Time `json:"last_modified_at"`
	LastModifiedBy string `json:"last_modified_by"`
	ChangeReason string `json:"change_reason"`
	Description string `json:"description"`
}

type _GetFunctionResponseContent GetFunctionResponseContent

// NewGetFunctionResponseContent instantiates a new GetFunctionResponseContent object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewGetFunctionResponseContent(functionName string, draftCode string, draftRuntimeVersion string, draftEditedAt time.Time, draftEditedBy string, lastModifiedAt time.Time, lastModifiedBy string, changeReason string, description string) *GetFunctionResponseContent {
	this := GetFunctionResponseContent{}
	this.FunctionName = functionName
	this.DraftCode = draftCode
	this.DraftRuntimeVersion = draftRuntimeVersion
	this.DraftEditedAt = draftEditedAt
	this.DraftEditedBy = draftEditedBy
	this.LastModifiedAt = lastModifiedAt
	this.LastModifiedBy = lastModifiedBy
	this.ChangeReason = changeReason
	this.Description = description
	return &this
}

// NewGetFunctionResponseContentWithDefaults instantiates a new GetFunctionResponseContent object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewGetFunctionResponseContentWithDefaults() *GetFunctionResponseContent {
	this := GetFunctionResponseContent{}
	return &this
}

// GetFunctionName returns the FunctionName field value
func (o *GetFunctionResponseContent) GetFunctionName() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.FunctionName
}

// GetFunctionNameOk returns a tuple with the FunctionName field value
// and a boolean to check if the value has been set.
func (o *GetFunctionResponseContent) GetFunctionNameOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.FunctionName, true
}

// SetFunctionName sets field value
func (o *GetFunctionResponseContent) SetFunctionName(v string) {
	o.FunctionName = v
}

// GetPublishedCode returns the PublishedCode field value if set, zero value otherwise.
func (o *GetFunctionResponseContent) GetPublishedCode() string {
	if o == nil || IsNil(o.PublishedCode) {
		var ret string
		return ret
	}
	return *o.PublishedCode
}

// GetPublishedCodeOk returns a tuple with the PublishedCode field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GetFunctionResponseContent) GetPublishedCodeOk() (*string, bool) {
	if o == nil || IsNil(o.PublishedCode) {
		return nil, false
	}
	return o.PublishedCode, true
}

// HasPublishedCode returns a boolean if a field has been set.
func (o *GetFunctionResponseContent) HasPublishedCode() bool {
	if o != nil && !IsNil(o.PublishedCode) {
		return true
	}

	return false
}

// SetPublishedCode gets a reference to the given string and assigns it to the PublishedCode field.
func (o *GetFunctionResponseContent) SetPublishedCode(v string) {
	o.PublishedCode = &v
}

// GetDraftCode returns the DraftCode field value
func (o *GetFunctionResponseContent) GetDraftCode() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.DraftCode
}

// GetDraftCodeOk returns a tuple with the DraftCode field value
// and a boolean to check if the value has been set.
func (o *GetFunctionResponseContent) GetDraftCodeOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.DraftCode, true
}

// SetDraftCode sets field value
func (o *GetFunctionResponseContent) SetDraftCode(v string) {
	o.DraftCode = v
}

// GetPublishedRuntimeVersion returns the PublishedRuntimeVersion field value if set, zero value otherwise.
func (o *GetFunctionResponseContent) GetPublishedRuntimeVersion() string {
	if o == nil || IsNil(o.PublishedRuntimeVersion) {
		var ret string
		return ret
	}
	return *o.PublishedRuntimeVersion
}

// GetPublishedRuntimeVersionOk returns a tuple with the PublishedRuntimeVersion field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GetFunctionResponseContent) GetPublishedRuntimeVersionOk() (*string, bool) {
	if o == nil || IsNil(o.PublishedRuntimeVersion) {
		return nil, false
	}
	return o.PublishedRuntimeVersion, true
}

// HasPublishedRuntimeVersion returns a boolean if a field has been set.
func (o *GetFunctionResponseContent) HasPublishedRuntimeVersion() bool {
	if o != nil && !IsNil(o.PublishedRuntimeVersion) {
		return true
	}

	return false
}

// SetPublishedRuntimeVersion gets a reference to the given string and assigns it to the PublishedRuntimeVersion field.
func (o *GetFunctionResponseContent) SetPublishedRuntimeVersion(v string) {
	o.PublishedRuntimeVersion = &v
}

// GetDraftRuntimeVersion returns the DraftRuntimeVersion field value
func (o *GetFunctionResponseContent) GetDraftRuntimeVersion() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.DraftRuntimeVersion
}

// GetDraftRuntimeVersionOk returns a tuple with the DraftRuntimeVersion field value
// and a boolean to check if the value has been set.
func (o *GetFunctionResponseContent) GetDraftRuntimeVersionOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.DraftRuntimeVersion, true
}

// SetDraftRuntimeVersion sets field value
func (o *GetFunctionResponseContent) SetDraftRuntimeVersion(v string) {
	o.DraftRuntimeVersion = v
}

// GetPublishedAt returns the PublishedAt field value if set, zero value otherwise.
func (o *GetFunctionResponseContent) GetPublishedAt() time.Time {
	if o == nil || IsNil(o.PublishedAt) {
		var ret time.Time
		return ret
	}
	return *o.PublishedAt
}

// GetPublishedAtOk returns a tuple with the PublishedAt field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GetFunctionResponseContent) GetPublishedAtOk() (*time.Time, bool) {
	if o == nil || IsNil(o.PublishedAt) {
		return nil, false
	}
	return o.PublishedAt, true
}

// HasPublishedAt returns a boolean if a field has been set.
func (o *GetFunctionResponseContent) HasPublishedAt() bool {
	if o != nil && !IsNil(o.PublishedAt) {
		return true
	}

	return false
}

// SetPublishedAt gets a reference to the given time.Time and assigns it to the PublishedAt field.
func (o *GetFunctionResponseContent) SetPublishedAt(v time.Time) {
	o.PublishedAt = &v
}

// GetDraftEditedAt returns the DraftEditedAt field value
func (o *GetFunctionResponseContent) GetDraftEditedAt() time.Time {
	if o == nil {
		var ret time.Time
		return ret
	}

	return o.DraftEditedAt
}

// GetDraftEditedAtOk returns a tuple with the DraftEditedAt field value
// and a boolean to check if the value has been set.
func (o *GetFunctionResponseContent) GetDraftEditedAtOk() (*time.Time, bool) {
	if o == nil {
		return nil, false
	}
	return &o.DraftEditedAt, true
}

// SetDraftEditedAt sets field value
func (o *GetFunctionResponseContent) SetDraftEditedAt(v time.Time) {
	o.DraftEditedAt = v
}

// GetPublishedBy returns the PublishedBy field value if set, zero value otherwise.
func (o *GetFunctionResponseContent) GetPublishedBy() string {
	if o == nil || IsNil(o.PublishedBy) {
		var ret string
		return ret
	}
	return *o.PublishedBy
}

// GetPublishedByOk returns a tuple with the PublishedBy field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GetFunctionResponseContent) GetPublishedByOk() (*string, bool) {
	if o == nil || IsNil(o.PublishedBy) {
		return nil, false
	}
	return o.PublishedBy, true
}

// HasPublishedBy returns a boolean if a field has been set.
func (o *GetFunctionResponseContent) HasPublishedBy() bool {
	if o != nil && !IsNil(o.PublishedBy) {
		return true
	}

	return false
}

// SetPublishedBy gets a reference to the given string and assigns it to the PublishedBy field.
func (o *GetFunctionResponseContent) SetPublishedBy(v string) {
	o.PublishedBy = &v
}

// GetDraftEditedBy returns the DraftEditedBy field value
func (o *GetFunctionResponseContent) GetDraftEditedBy() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.DraftEditedBy
}

// GetDraftEditedByOk returns a tuple with the DraftEditedBy field value
// and a boolean to check if the value has been set.
func (o *GetFunctionResponseContent) GetDraftEditedByOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.DraftEditedBy, true
}

// SetDraftEditedBy sets field value
func (o *GetFunctionResponseContent) SetDraftEditedBy(v string) {
	o.DraftEditedBy = v
}

// GetLastModifiedAt returns the LastModifiedAt field value
func (o *GetFunctionResponseContent) GetLastModifiedAt() time.Time {
	if o == nil {
		var ret time.Time
		return ret
	}

	return o.LastModifiedAt
}

// GetLastModifiedAtOk returns a tuple with the LastModifiedAt field value
// and a boolean to check if the value has been set.
func (o *GetFunctionResponseContent) GetLastModifiedAtOk() (*time.Time, bool) {
	if o == nil {
		return nil, false
	}
	return &o.LastModifiedAt, true
}

// SetLastModifiedAt sets field value
func (o *GetFunctionResponseContent) SetLastModifiedAt(v time.Time) {
	o.LastModifiedAt = v
}

// GetLastModifiedBy returns the LastModifiedBy field value
func (o *GetFunctionResponseContent) GetLastModifiedBy() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.LastModifiedBy
}

// GetLastModifiedByOk returns a tuple with the LastModifiedBy field value
// and a boolean to check if the value has been set.
func (o *GetFunctionResponseContent) GetLastModifiedByOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.LastModifiedBy, true
}

// SetLastModifiedBy sets field value
func (o *GetFunctionResponseContent) SetLastModifiedBy(v string) {
	o.LastModifiedBy = v
}

// GetChangeReason returns the ChangeReason field value
func (o *GetFunctionResponseContent) GetChangeReason() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.ChangeReason
}

// GetChangeReasonOk returns a tuple with the ChangeReason field value
// and a boolean to check if the value has been set.
func (o *GetFunctionResponseContent) GetChangeReasonOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.ChangeReason, true
}

// SetChangeReason sets field value
func (o *GetFunctionResponseContent) SetChangeReason(v string) {
	o.ChangeReason = v
}

// GetDescription returns the Description field value
func (o *GetFunctionResponseContent) GetDescription() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Description
}

// GetDescriptionOk returns a tuple with the Description field value
// and a boolean to check if the value has been set.
func (o *GetFunctionResponseContent) GetDescriptionOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Description, true
}

// SetDescription sets field value
func (o *GetFunctionResponseContent) SetDescription(v string) {
	o.Description = v
}

func (o GetFunctionResponseContent) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o GetFunctionResponseContent) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["function_name"] = o.FunctionName
	if !IsNil(o.PublishedCode) {
		toSerialize["published_code"] = o.PublishedCode
	}
	toSerialize["draft_code"] = o.DraftCode
	if !IsNil(o.PublishedRuntimeVersion) {
		toSerialize["published_runtime_version"] = o.PublishedRuntimeVersion
	}
	toSerialize["draft_runtime_version"] = o.DraftRuntimeVersion
	if !IsNil(o.PublishedAt) {
		toSerialize["published_at"] = o.PublishedAt
	}
	toSerialize["draft_edited_at"] = o.DraftEditedAt
	if !IsNil(o.PublishedBy) {
		toSerialize["published_by"] = o.PublishedBy
	}
	toSerialize["draft_edited_by"] = o.DraftEditedBy
	toSerialize["last_modified_at"] = o.LastModifiedAt
	toSerialize["last_modified_by"] = o.LastModifiedBy
	toSerialize["change_reason"] = o.ChangeReason
	toSerialize["description"] = o.Description
	return toSerialize, nil
}

func (o *GetFunctionResponseContent) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"function_name",
		"draft_code",
		"draft_runtime_version",
		"draft_edited_at",
		"draft_edited_by",
		"last_modified_at",
		"last_modified_by",
		"change_reason",
		"description",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varGetFunctionResponseContent := _GetFunctionResponseContent{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varGetFunctionResponseContent)

	if err != nil {
		return err
	}

	*o = GetFunctionResponseContent(varGetFunctionResponseContent)

	return err
}

type NullableGetFunctionResponseContent struct {
	value *GetFunctionResponseContent
	isSet bool
}

func (v NullableGetFunctionResponseContent) Get() *GetFunctionResponseContent {
	return v.value
}

func (v *NullableGetFunctionResponseContent) Set(val *GetFunctionResponseContent) {
	v.value = val
	v.isSet = true
}

func (v NullableGetFunctionResponseContent) IsSet() bool {
	return v.isSet
}

func (v *NullableGetFunctionResponseContent) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableGetFunctionResponseContent(val *GetFunctionResponseContent) *NullableGetFunctionResponseContent {
	return &NullableGetFunctionResponseContent{value: val, isSet: true}
}

func (v NullableGetFunctionResponseContent) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableGetFunctionResponseContent) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


