/*
Superposition

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 2025-03-05
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package superposition_sdk_go

import (
	"encoding/json"
)

// checks if the ListVersionsResponseContent type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &ListVersionsResponseContent{}

// ListVersionsResponseContent struct for ListVersionsResponseContent
type ListVersionsResponseContent struct {
	TotalPages *float32 `json:"total_pages,omitempty"`
	TotalItems *float32 `json:"total_items,omitempty"`
	Data []string `json:"data,omitempty"`
}

// NewListVersionsResponseContent instantiates a new ListVersionsResponseContent object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewListVersionsResponseContent() *ListVersionsResponseContent {
	this := ListVersionsResponseContent{}
	return &this
}

// NewListVersionsResponseContentWithDefaults instantiates a new ListVersionsResponseContent object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewListVersionsResponseContentWithDefaults() *ListVersionsResponseContent {
	this := ListVersionsResponseContent{}
	return &this
}

// GetTotalPages returns the TotalPages field value if set, zero value otherwise.
func (o *ListVersionsResponseContent) GetTotalPages() float32 {
	if o == nil || IsNil(o.TotalPages) {
		var ret float32
		return ret
	}
	return *o.TotalPages
}

// GetTotalPagesOk returns a tuple with the TotalPages field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ListVersionsResponseContent) GetTotalPagesOk() (*float32, bool) {
	if o == nil || IsNil(o.TotalPages) {
		return nil, false
	}
	return o.TotalPages, true
}

// HasTotalPages returns a boolean if a field has been set.
func (o *ListVersionsResponseContent) HasTotalPages() bool {
	if o != nil && !IsNil(o.TotalPages) {
		return true
	}

	return false
}

// SetTotalPages gets a reference to the given float32 and assigns it to the TotalPages field.
func (o *ListVersionsResponseContent) SetTotalPages(v float32) {
	o.TotalPages = &v
}

// GetTotalItems returns the TotalItems field value if set, zero value otherwise.
func (o *ListVersionsResponseContent) GetTotalItems() float32 {
	if o == nil || IsNil(o.TotalItems) {
		var ret float32
		return ret
	}
	return *o.TotalItems
}

// GetTotalItemsOk returns a tuple with the TotalItems field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ListVersionsResponseContent) GetTotalItemsOk() (*float32, bool) {
	if o == nil || IsNil(o.TotalItems) {
		return nil, false
	}
	return o.TotalItems, true
}

// HasTotalItems returns a boolean if a field has been set.
func (o *ListVersionsResponseContent) HasTotalItems() bool {
	if o != nil && !IsNil(o.TotalItems) {
		return true
	}

	return false
}

// SetTotalItems gets a reference to the given float32 and assigns it to the TotalItems field.
func (o *ListVersionsResponseContent) SetTotalItems(v float32) {
	o.TotalItems = &v
}

// GetData returns the Data field value if set, zero value otherwise.
func (o *ListVersionsResponseContent) GetData() []string {
	if o == nil || IsNil(o.Data) {
		var ret []string
		return ret
	}
	return o.Data
}

// GetDataOk returns a tuple with the Data field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ListVersionsResponseContent) GetDataOk() ([]string, bool) {
	if o == nil || IsNil(o.Data) {
		return nil, false
	}
	return o.Data, true
}

// HasData returns a boolean if a field has been set.
func (o *ListVersionsResponseContent) HasData() bool {
	if o != nil && !IsNil(o.Data) {
		return true
	}

	return false
}

// SetData gets a reference to the given []string and assigns it to the Data field.
func (o *ListVersionsResponseContent) SetData(v []string) {
	o.Data = v
}

func (o ListVersionsResponseContent) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o ListVersionsResponseContent) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.TotalPages) {
		toSerialize["total_pages"] = o.TotalPages
	}
	if !IsNil(o.TotalItems) {
		toSerialize["total_items"] = o.TotalItems
	}
	if !IsNil(o.Data) {
		toSerialize["data"] = o.Data
	}
	return toSerialize, nil
}

type NullableListVersionsResponseContent struct {
	value *ListVersionsResponseContent
	isSet bool
}

func (v NullableListVersionsResponseContent) Get() *ListVersionsResponseContent {
	return v.value
}

func (v *NullableListVersionsResponseContent) Set(val *ListVersionsResponseContent) {
	v.value = val
	v.isSet = true
}

func (v NullableListVersionsResponseContent) IsSet() bool {
	return v.isSet
}

func (v *NullableListVersionsResponseContent) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableListVersionsResponseContent(val *ListVersionsResponseContent) *NullableListVersionsResponseContent {
	return &NullableListVersionsResponseContent{value: val, isSet: true}
}

func (v NullableListVersionsResponseContent) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableListVersionsResponseContent) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


