/*
Superposition

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 2025-03-05
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package superposition_sdk_go

import (
	"encoding/json"
	"time"
	"bytes"
	"fmt"
)

// checks if the DefaultConfigFull type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &DefaultConfigFull{}

// DefaultConfigFull struct for DefaultConfigFull
type DefaultConfigFull struct {
	Key string `json:"key"`
	Value interface{} `json:"value"`
	Schema interface{} `json:"schema"`
	Description string `json:"description"`
	ChangeReason string `json:"change_reason"`
	// Optional
	FunctionName *string `json:"function_name,omitempty"`
	CreatedAt time.Time `json:"created_at"`
	CreatedBy string `json:"created_by"`
	LastModifiedAt time.Time `json:"last_modified_at"`
	LastModifiedBy string `json:"last_modified_by"`
}

type _DefaultConfigFull DefaultConfigFull

// NewDefaultConfigFull instantiates a new DefaultConfigFull object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewDefaultConfigFull(key string, value interface{}, schema interface{}, description string, changeReason string, createdAt time.Time, createdBy string, lastModifiedAt time.Time, lastModifiedBy string) *DefaultConfigFull {
	this := DefaultConfigFull{}
	this.Key = key
	this.Value = value
	this.Schema = schema
	this.Description = description
	this.ChangeReason = changeReason
	this.CreatedAt = createdAt
	this.CreatedBy = createdBy
	this.LastModifiedAt = lastModifiedAt
	this.LastModifiedBy = lastModifiedBy
	return &this
}

// NewDefaultConfigFullWithDefaults instantiates a new DefaultConfigFull object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewDefaultConfigFullWithDefaults() *DefaultConfigFull {
	this := DefaultConfigFull{}
	return &this
}

// GetKey returns the Key field value
func (o *DefaultConfigFull) GetKey() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Key
}

// GetKeyOk returns a tuple with the Key field value
// and a boolean to check if the value has been set.
func (o *DefaultConfigFull) GetKeyOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Key, true
}

// SetKey sets field value
func (o *DefaultConfigFull) SetKey(v string) {
	o.Key = v
}

// GetValue returns the Value field value
// If the value is explicit nil, the zero value for interface{} will be returned
func (o *DefaultConfigFull) GetValue() interface{} {
	if o == nil {
		var ret interface{}
		return ret
	}

	return o.Value
}

// GetValueOk returns a tuple with the Value field value
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *DefaultConfigFull) GetValueOk() (*interface{}, bool) {
	if o == nil || IsNil(o.Value) {
		return nil, false
	}
	return &o.Value, true
}

// SetValue sets field value
func (o *DefaultConfigFull) SetValue(v interface{}) {
	o.Value = v
}

// GetSchema returns the Schema field value
// If the value is explicit nil, the zero value for interface{} will be returned
func (o *DefaultConfigFull) GetSchema() interface{} {
	if o == nil {
		var ret interface{}
		return ret
	}

	return o.Schema
}

// GetSchemaOk returns a tuple with the Schema field value
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *DefaultConfigFull) GetSchemaOk() (*interface{}, bool) {
	if o == nil || IsNil(o.Schema) {
		return nil, false
	}
	return &o.Schema, true
}

// SetSchema sets field value
func (o *DefaultConfigFull) SetSchema(v interface{}) {
	o.Schema = v
}

// GetDescription returns the Description field value
func (o *DefaultConfigFull) GetDescription() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Description
}

// GetDescriptionOk returns a tuple with the Description field value
// and a boolean to check if the value has been set.
func (o *DefaultConfigFull) GetDescriptionOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Description, true
}

// SetDescription sets field value
func (o *DefaultConfigFull) SetDescription(v string) {
	o.Description = v
}

// GetChangeReason returns the ChangeReason field value
func (o *DefaultConfigFull) GetChangeReason() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.ChangeReason
}

// GetChangeReasonOk returns a tuple with the ChangeReason field value
// and a boolean to check if the value has been set.
func (o *DefaultConfigFull) GetChangeReasonOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.ChangeReason, true
}

// SetChangeReason sets field value
func (o *DefaultConfigFull) SetChangeReason(v string) {
	o.ChangeReason = v
}

// GetFunctionName returns the FunctionName field value if set, zero value otherwise.
func (o *DefaultConfigFull) GetFunctionName() string {
	if o == nil || IsNil(o.FunctionName) {
		var ret string
		return ret
	}
	return *o.FunctionName
}

// GetFunctionNameOk returns a tuple with the FunctionName field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *DefaultConfigFull) GetFunctionNameOk() (*string, bool) {
	if o == nil || IsNil(o.FunctionName) {
		return nil, false
	}
	return o.FunctionName, true
}

// HasFunctionName returns a boolean if a field has been set.
func (o *DefaultConfigFull) HasFunctionName() bool {
	if o != nil && !IsNil(o.FunctionName) {
		return true
	}

	return false
}

// SetFunctionName gets a reference to the given string and assigns it to the FunctionName field.
func (o *DefaultConfigFull) SetFunctionName(v string) {
	o.FunctionName = &v
}

// GetCreatedAt returns the CreatedAt field value
func (o *DefaultConfigFull) GetCreatedAt() time.Time {
	if o == nil {
		var ret time.Time
		return ret
	}

	return o.CreatedAt
}

// GetCreatedAtOk returns a tuple with the CreatedAt field value
// and a boolean to check if the value has been set.
func (o *DefaultConfigFull) GetCreatedAtOk() (*time.Time, bool) {
	if o == nil {
		return nil, false
	}
	return &o.CreatedAt, true
}

// SetCreatedAt sets field value
func (o *DefaultConfigFull) SetCreatedAt(v time.Time) {
	o.CreatedAt = v
}

// GetCreatedBy returns the CreatedBy field value
func (o *DefaultConfigFull) GetCreatedBy() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.CreatedBy
}

// GetCreatedByOk returns a tuple with the CreatedBy field value
// and a boolean to check if the value has been set.
func (o *DefaultConfigFull) GetCreatedByOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.CreatedBy, true
}

// SetCreatedBy sets field value
func (o *DefaultConfigFull) SetCreatedBy(v string) {
	o.CreatedBy = v
}

// GetLastModifiedAt returns the LastModifiedAt field value
func (o *DefaultConfigFull) GetLastModifiedAt() time.Time {
	if o == nil {
		var ret time.Time
		return ret
	}

	return o.LastModifiedAt
}

// GetLastModifiedAtOk returns a tuple with the LastModifiedAt field value
// and a boolean to check if the value has been set.
func (o *DefaultConfigFull) GetLastModifiedAtOk() (*time.Time, bool) {
	if o == nil {
		return nil, false
	}
	return &o.LastModifiedAt, true
}

// SetLastModifiedAt sets field value
func (o *DefaultConfigFull) SetLastModifiedAt(v time.Time) {
	o.LastModifiedAt = v
}

// GetLastModifiedBy returns the LastModifiedBy field value
func (o *DefaultConfigFull) GetLastModifiedBy() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.LastModifiedBy
}

// GetLastModifiedByOk returns a tuple with the LastModifiedBy field value
// and a boolean to check if the value has been set.
func (o *DefaultConfigFull) GetLastModifiedByOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.LastModifiedBy, true
}

// SetLastModifiedBy sets field value
func (o *DefaultConfigFull) SetLastModifiedBy(v string) {
	o.LastModifiedBy = v
}

func (o DefaultConfigFull) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o DefaultConfigFull) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["key"] = o.Key
	if o.Value != nil {
		toSerialize["value"] = o.Value
	}
	if o.Schema != nil {
		toSerialize["schema"] = o.Schema
	}
	toSerialize["description"] = o.Description
	toSerialize["change_reason"] = o.ChangeReason
	if !IsNil(o.FunctionName) {
		toSerialize["function_name"] = o.FunctionName
	}
	toSerialize["created_at"] = o.CreatedAt
	toSerialize["created_by"] = o.CreatedBy
	toSerialize["last_modified_at"] = o.LastModifiedAt
	toSerialize["last_modified_by"] = o.LastModifiedBy
	return toSerialize, nil
}

func (o *DefaultConfigFull) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"key",
		"value",
		"schema",
		"description",
		"change_reason",
		"created_at",
		"created_by",
		"last_modified_at",
		"last_modified_by",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varDefaultConfigFull := _DefaultConfigFull{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varDefaultConfigFull)

	if err != nil {
		return err
	}

	*o = DefaultConfigFull(varDefaultConfigFull)

	return err
}

type NullableDefaultConfigFull struct {
	value *DefaultConfigFull
	isSet bool
}

func (v NullableDefaultConfigFull) Get() *DefaultConfigFull {
	return v.value
}

func (v *NullableDefaultConfigFull) Set(val *DefaultConfigFull) {
	v.value = val
	v.isSet = true
}

func (v NullableDefaultConfigFull) IsSet() bool {
	return v.isSet
}

func (v *NullableDefaultConfigFull) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableDefaultConfigFull(val *DefaultConfigFull) *NullableDefaultConfigFull {
	return &NullableDefaultConfigFull{value: val, isSet: true}
}

func (v NullableDefaultConfigFull) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableDefaultConfigFull) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


