// Code generated by software.amazon.smithy.rust.codegen.smithy-rs. DO NOT EDIT.
pub use crate::operation::import_config_toml::_import_config_toml_output::ImportConfigTomlOutputBuilder;

pub use crate::operation::import_config_toml::_import_config_toml_input::ImportConfigTomlInputBuilder;

impl crate::operation::import_config_toml::builders::ImportConfigTomlInputBuilder {
                    /// Sends a request with this input using the given client.
                    pub async fn send_with(self, client: &crate::Client) -> ::std::result::Result<
                        crate::operation::import_config_toml::ImportConfigTomlOutput,
                        ::aws_smithy_runtime_api::client::result::SdkError<
                            crate::operation::import_config_toml::ImportConfigTomlError,
                            ::aws_smithy_runtime_api::client::orchestrator::HttpResponse
                        >
                    > {
                        let mut fluent_builder = client.import_config_toml();
                        fluent_builder.inner = self;
                        fluent_builder.send().await
                    }
                }
/// Fluent builder constructing a request to `ImportConfigToml`.
/// 
/// Imports a full config from a TOML document, persisting dimensions, default-configs and contexts in a single transaction after validating the document.
#[derive(::std::clone::Clone, ::std::fmt::Debug)]
pub struct ImportConfigTomlFluentBuilder {
                handle: ::std::sync::Arc<crate::client::Handle>,
                inner: crate::operation::import_config_toml::builders::ImportConfigTomlInputBuilder,
config_override: ::std::option::Option<crate::config::Builder>,
            }
impl
                crate::client::customize::internal::CustomizableSend<
                    crate::operation::import_config_toml::ImportConfigTomlOutput,
                    crate::operation::import_config_toml::ImportConfigTomlError,
                > for ImportConfigTomlFluentBuilder
            {
                fn send(
                    self,
                    config_override: crate::config::Builder,
                ) -> crate::client::customize::internal::BoxFuture<
                    crate::client::customize::internal::SendResult<
                        crate::operation::import_config_toml::ImportConfigTomlOutput,
                        crate::operation::import_config_toml::ImportConfigTomlError,
                    >,
                > {
                    ::std::boxed::Box::pin(async move { self.config_override(config_override).send().await })
                }
            }
impl ImportConfigTomlFluentBuilder {
    /// Creates a new `ImportConfigTomlFluentBuilder`.
                    pub(crate) fn new(handle: ::std::sync::Arc<crate::client::Handle>) -> Self {
                        Self {
                            handle,
                            inner: ::std::default::Default::default(),
    config_override: ::std::option::Option::None,
                        }
                    }
    /// Access the ImportConfigToml as a reference.
                    pub fn as_input(&self) -> &crate::operation::import_config_toml::builders::ImportConfigTomlInputBuilder {
                        &self.inner
                    }
    /// Sends the request and returns the response.
                    ///
                    /// If an error occurs, an `SdkError` will be returned with additional details that
                    /// can be matched against.
                    ///
                    /// By default, any retryable failures will be retried twice. Retry behavior
                    /// is configurable with the [RetryConfig](aws_smithy_types::retry::RetryConfig), which can be
                    /// set when configuring the client.
                    pub async fn send(self) -> ::std::result::Result<crate::operation::import_config_toml::ImportConfigTomlOutput, ::aws_smithy_runtime_api::client::result::SdkError<crate::operation::import_config_toml::ImportConfigTomlError, ::aws_smithy_runtime_api::client::orchestrator::HttpResponse>> {
                        let input = self.inner.build().map_err(::aws_smithy_runtime_api::client::result::SdkError::construction_failure)?;
                        let runtime_plugins = crate::operation::import_config_toml::ImportConfigToml::operation_runtime_plugins(
                            self.handle.runtime_plugins.clone(),
                            &self.handle.conf,
                            self.config_override,
                        );
                        crate::operation::import_config_toml::ImportConfigToml::orchestrate(&runtime_plugins, input).await
                    }
    
                    /// Consumes this builder, creating a customizable operation that can be modified before being sent.
                    pub fn customize(
                        self,
                    ) -> crate::client::customize::CustomizableOperation<crate::operation::import_config_toml::ImportConfigTomlOutput, crate::operation::import_config_toml::ImportConfigTomlError, Self> {
                        crate::client::customize::CustomizableOperation::new(self)
                    }
    pub(crate) fn config_override(
                            mut self,
                            config_override: impl ::std::convert::Into<crate::config::Builder>,
                        ) -> Self {
                            self.set_config_override(::std::option::Option::Some(config_override.into()));
                            self
                        }
    
                        pub(crate) fn set_config_override(
                            &mut self,
                            config_override: ::std::option::Option<crate::config::Builder>,
                        ) -> &mut Self {
                            self.config_override = config_override;
                            self
                        }
    #[allow(missing_docs)] // documentation missing in model
    pub fn workspace_id(mut self, input: impl ::std::convert::Into<::std::string::String>) -> Self {
                    self.inner = self.inner.workspace_id(input.into());
                    self
                }
    #[allow(missing_docs)] // documentation missing in model
    pub fn set_workspace_id(mut self, input: ::std::option::Option<::std::string::String>) -> Self {
                    self.inner = self.inner.set_workspace_id(input);
                    self
                }
    #[allow(missing_docs)] // documentation missing in model
    pub fn get_workspace_id(&self) -> &::std::option::Option<::std::string::String> {
                    self.inner.get_workspace_id()
                }
    #[allow(missing_docs)] // documentation missing in model
    pub fn org_id(mut self, input: impl ::std::convert::Into<::std::string::String>) -> Self {
                    self.inner = self.inner.org_id(input.into());
                    self
                }
    #[allow(missing_docs)] // documentation missing in model
    pub fn set_org_id(mut self, input: ::std::option::Option<::std::string::String>) -> Self {
                    self.inner = self.inner.set_org_id(input);
                    self
                }
    #[allow(missing_docs)] // documentation missing in model
    pub fn get_org_id(&self) -> &::std::option::Option<::std::string::String> {
                    self.inner.get_org_id()
                }
    /// How the import applies file entities to the workspace. Defaults to upsert.
    pub fn strategy(mut self, input: crate::types::ImportStrategy) -> Self {
                    self.inner = self.inner.strategy(input);
                    self
                }
    /// How the import applies file entities to the workspace. Defaults to upsert.
    pub fn set_strategy(mut self, input: ::std::option::Option<crate::types::ImportStrategy>) -> Self {
                    self.inner = self.inner.set_strategy(input);
                    self
                }
    /// How the import applies file entities to the workspace. Defaults to upsert.
    pub fn get_strategy(&self) -> &::std::option::Option<crate::types::ImportStrategy> {
                    self.inner.get_strategy()
                }
    /// Whether to abort (default) or continue on per-entity errors.
    pub fn on_error(mut self, input: crate::types::ImportOnError) -> Self {
                    self.inner = self.inner.on_error(input);
                    self
                }
    /// Whether to abort (default) or continue on per-entity errors.
    pub fn set_on_error(mut self, input: ::std::option::Option<crate::types::ImportOnError>) -> Self {
                    self.inner = self.inner.set_on_error(input);
                    self
                }
    /// Whether to abort (default) or continue on per-entity errors.
    pub fn get_on_error(&self) -> &::std::option::Option<crate::types::ImportOnError> {
                    self.inner.get_on_error()
                }
    /// When true, validates and summarises the import without persisting anything. Defaults to false.
    pub fn dry_run(mut self, input: bool) -> Self {
                    self.inner = self.inner.dry_run(input);
                    self
                }
    /// When true, validates and summarises the import without persisting anything. Defaults to false.
    pub fn set_dry_run(mut self, input: ::std::option::Option<bool>) -> Self {
                    self.inner = self.inner.set_dry_run(input);
                    self
                }
    /// When true, validates and summarises the import without persisting anything. Defaults to false.
    pub fn get_dry_run(&self) -> &::std::option::Option<bool> {
                    self.inner.get_dry_run()
                }
    #[allow(missing_docs)] // documentation missing in model
    pub fn config_tags(mut self, input: impl ::std::convert::Into<::std::string::String>) -> Self {
                    self.inner = self.inner.config_tags(input.into());
                    self
                }
    #[allow(missing_docs)] // documentation missing in model
    pub fn set_config_tags(mut self, input: ::std::option::Option<::std::string::String>) -> Self {
                    self.inner = self.inner.set_config_tags(input);
                    self
                }
    #[allow(missing_docs)] // documentation missing in model
    pub fn get_config_tags(&self) -> &::std::option::Option<::std::string::String> {
                    self.inner.get_config_tags()
                }
    #[allow(missing_docs)] // documentation missing in model
    pub fn toml_config(mut self, input: impl ::std::convert::Into<::std::string::String>) -> Self {
                    self.inner = self.inner.toml_config(input.into());
                    self
                }
    #[allow(missing_docs)] // documentation missing in model
    pub fn set_toml_config(mut self, input: ::std::option::Option<::std::string::String>) -> Self {
                    self.inner = self.inner.set_toml_config(input);
                    self
                }
    #[allow(missing_docs)] // documentation missing in model
    pub fn get_toml_config(&self) -> &::std::option::Option<::std::string::String> {
                    self.inner.get_toml_config()
                }
}

