/*
 * Superposition
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2025-03-05
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct CreateWorkspaceResponseContent {
    #[serde(rename = "workspace_name")]
    pub workspace_name: String,
    #[serde(rename = "organisation_id")]
    pub organisation_id: String,
    #[serde(rename = "organisation_name")]
    pub organisation_name: String,
    #[serde(rename = "workspace_schema_name")]
    pub workspace_schema_name: String,
    #[serde(rename = "workspace_status")]
    pub workspace_status: String,
    #[serde(rename = "workspace_admin_email")]
    pub workspace_admin_email: String,
    #[serde(rename = "created_by")]
    pub created_by: String,
    #[serde(rename = "last_modified_by")]
    pub last_modified_by: String,
    #[serde(rename = "last_modified_at")]
    pub last_modified_at: f64,
    #[serde(rename = "created_at")]
    pub created_at: f64,
    #[serde(rename = "mandatory_dimensions", skip_serializing_if = "Option::is_none")]
    pub mandatory_dimensions: Option<Vec<String>>,
}

impl CreateWorkspaceResponseContent {
    pub fn new(workspace_name: String, organisation_id: String, organisation_name: String, workspace_schema_name: String, workspace_status: String, workspace_admin_email: String, created_by: String, last_modified_by: String, last_modified_at: f64, created_at: f64) -> CreateWorkspaceResponseContent {
        CreateWorkspaceResponseContent {
            workspace_name,
            organisation_id,
            organisation_name,
            workspace_schema_name,
            workspace_status,
            workspace_admin_email,
            created_by,
            last_modified_by,
            last_modified_at,
            created_at,
            mandatory_dimensions: None,
        }
    }
}

