[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"

[project]
name = "superposition_provider"
version = "0.0.1"
description = "superposition_provider"
readme = "README.md"
requires-python = ">=3.12"
keywords = ["openfeature", "superposition_provider"]
license = {text = "Apache-2.0"}

dependencies = [
    "superposition_sdk",
    "superposition_bindings"
]

[tool.setuptools.packages.find]
where = ["."]
include = ["superposition_provider"]