// Code generated by software.amazon.smithy.rust.codegen.smithy-rs. DO NOT EDIT.

/// Indicates that the operation succeeded but the webhook call failed. The response body contains the successful result, but the client should be aware that webhook notification did not complete.
#[non_exhaustive]
#[derive(::std::clone::Clone, ::std::cmp::PartialEq, ::std::fmt::Debug)]
pub struct WebhookFailed  {
    /// The successful operation result that would have been returned with HTTP 200. The structure matches the operation's normal output type.
    pub data: ::std::option::Option<::aws_smithy_types::Document>,
    #[allow(missing_docs)] // documentation missing in model
    pub message: ::std::option::Option<::std::string::String>,
    pub(crate) meta: ::aws_smithy_types::error::ErrorMetadata,
}
impl  WebhookFailed  {
    /// The successful operation result that would have been returned with HTTP 200. The structure matches the operation's normal output type.
    pub fn data(&self) -> ::std::option::Option<&::aws_smithy_types::Document> {
        self.data.as_ref()
    }
}
impl WebhookFailed {
    /// Returns the error message.
                        pub fn message(&self) -> ::std::option::Option<&str> { self.message.as_deref() }
}
impl ::std::fmt::Display for WebhookFailed {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        ::std::write!(f, "WebhookFailed")?;
        if let ::std::option::Option::Some(inner_1) = &self.message {
             {
                ::std::write!(f, ": {}", inner_1)?;
            }
        }
        Ok(())
    }
}
impl ::std::error::Error for WebhookFailed {}
impl ::aws_smithy_types::error::metadata::ProvideErrorMetadata for WebhookFailed {
    fn meta(&self) -> &::aws_smithy_types::error::ErrorMetadata { &self.meta }
}
impl WebhookFailed {
    /// Creates a new builder-style object to manufacture [`WebhookFailed`](crate::types::error::WebhookFailed).
    pub fn builder() -> crate::types::error::builders::WebhookFailedBuilder {
        crate::types::error::builders::WebhookFailedBuilder::default()
    }
}

/// A builder for [`WebhookFailed`](crate::types::error::WebhookFailed).
#[derive(::std::clone::Clone, ::std::cmp::PartialEq, ::std::default::Default, ::std::fmt::Debug)]
#[non_exhaustive]
pub struct WebhookFailedBuilder {
    pub(crate) data: ::std::option::Option<::aws_smithy_types::Document>,
    pub(crate) message: ::std::option::Option<::std::string::String>,
    meta: std::option::Option<::aws_smithy_types::error::ErrorMetadata>,
}
impl WebhookFailedBuilder {
    /// The successful operation result that would have been returned with HTTP 200. The structure matches the operation's normal output type.
    pub fn data(mut self, input: ::aws_smithy_types::Document) -> Self {
        self.data = ::std::option::Option::Some(input);
        self
    }
    /// The successful operation result that would have been returned with HTTP 200. The structure matches the operation's normal output type.
    pub fn set_data(mut self, input: ::std::option::Option<::aws_smithy_types::Document>) -> Self {
        self.data = input; self
    }
    /// The successful operation result that would have been returned with HTTP 200. The structure matches the operation's normal output type.
    pub fn get_data(&self) -> &::std::option::Option<::aws_smithy_types::Document> {
        &self.data
    }
    #[allow(missing_docs)] // documentation missing in model
    pub fn message(mut self, input: impl ::std::convert::Into<::std::string::String>) -> Self {
        self.message = ::std::option::Option::Some(input.into());
        self
    }
    #[allow(missing_docs)] // documentation missing in model
    pub fn set_message(mut self, input: ::std::option::Option<::std::string::String>) -> Self {
        self.message = input; self
    }
    #[allow(missing_docs)] // documentation missing in model
    pub fn get_message(&self) -> &::std::option::Option<::std::string::String> {
        &self.message
    }
    /// Sets error metadata
                                                pub fn meta(mut self, meta: ::aws_smithy_types::error::ErrorMetadata) -> Self {
                                                    self.meta = Some(meta);
                                                    self
                                                }
    
                                                /// Sets error metadata
                                                pub fn set_meta(&mut self, meta: std::option::Option<::aws_smithy_types::error::ErrorMetadata>) -> &mut Self {
                                                    self.meta = meta;
                                                    self
                                                }
    /// Consumes the builder and constructs a [`WebhookFailed`](crate::types::error::WebhookFailed).
    pub fn build(self) -> crate::types::error::WebhookFailed {
        crate::types::error::WebhookFailed {
            data: self.data
            ,
            message: self.message
            ,
            meta: self.meta.unwrap_or_default(),
        }
    }
}

