// Code generated by software.amazon.smithy.rust.codegen.smithy-rs. DO NOT EDIT.

/// Returned when a workspace write operation cannot proceed because another write operation currently holds the workspace lock.
#[non_exhaustive]
#[derive(::std::clone::Clone, ::std::cmp::PartialEq, ::std::fmt::Debug)]
pub struct WorkspaceLockConflict  {
    #[allow(missing_docs)] // documentation missing in model
    pub message: ::std::string::String,
    /// Metadata for an active workspace write lock. Present only while another write operation is holding the workspace lease.
    pub lock: crate::types::WorkspaceLock,
    pub(crate) meta: ::aws_smithy_types::error::ErrorMetadata,
}
impl  WorkspaceLockConflict  {
    /// Metadata for an active workspace write lock. Present only while another write operation is holding the workspace lease.
    pub fn lock(&self) -> &crate::types::WorkspaceLock {
        &self.lock
    }
}
impl WorkspaceLockConflict {
    /// Returns the error message.
                        pub fn message(&self) -> &str { &self.message }
}
impl ::std::fmt::Display for WorkspaceLockConflict {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        ::std::write!(f, "WorkspaceLockConflict")?;
         {
            ::std::write!(f, ": {}", &self.message)?;
        }
        Ok(())
    }
}
impl ::std::error::Error for WorkspaceLockConflict {}
impl ::aws_smithy_types::error::metadata::ProvideErrorMetadata for WorkspaceLockConflict {
    fn meta(&self) -> &::aws_smithy_types::error::ErrorMetadata { &self.meta }
}
impl WorkspaceLockConflict {
    /// Creates a new builder-style object to manufacture [`WorkspaceLockConflict`](crate::types::error::WorkspaceLockConflict).
    pub fn builder() -> crate::types::error::builders::WorkspaceLockConflictBuilder {
        crate::types::error::builders::WorkspaceLockConflictBuilder::default()
    }
}

/// A builder for [`WorkspaceLockConflict`](crate::types::error::WorkspaceLockConflict).
#[derive(::std::clone::Clone, ::std::cmp::PartialEq, ::std::default::Default, ::std::fmt::Debug)]
#[non_exhaustive]
pub struct WorkspaceLockConflictBuilder {
    pub(crate) message: ::std::option::Option<::std::string::String>,
    pub(crate) lock: ::std::option::Option<crate::types::WorkspaceLock>,
    meta: std::option::Option<::aws_smithy_types::error::ErrorMetadata>,
}
impl WorkspaceLockConflictBuilder {
    #[allow(missing_docs)] // documentation missing in model
    /// This field is required.
    pub fn message(mut self, input: impl ::std::convert::Into<::std::string::String>) -> Self {
        self.message = ::std::option::Option::Some(input.into());
        self
    }
    #[allow(missing_docs)] // documentation missing in model
    pub fn set_message(mut self, input: ::std::option::Option<::std::string::String>) -> Self {
        self.message = input; self
    }
    #[allow(missing_docs)] // documentation missing in model
    pub fn get_message(&self) -> &::std::option::Option<::std::string::String> {
        &self.message
    }
    /// Metadata for an active workspace write lock. Present only while another write operation is holding the workspace lease.
    /// This field is required.
    pub fn lock(mut self, input: crate::types::WorkspaceLock) -> Self {
        self.lock = ::std::option::Option::Some(input);
        self
    }
    /// Metadata for an active workspace write lock. Present only while another write operation is holding the workspace lease.
    pub fn set_lock(mut self, input: ::std::option::Option<crate::types::WorkspaceLock>) -> Self {
        self.lock = input; self
    }
    /// Metadata for an active workspace write lock. Present only while another write operation is holding the workspace lease.
    pub fn get_lock(&self) -> &::std::option::Option<crate::types::WorkspaceLock> {
        &self.lock
    }
    /// Sets error metadata
                                                pub fn meta(mut self, meta: ::aws_smithy_types::error::ErrorMetadata) -> Self {
                                                    self.meta = Some(meta);
                                                    self
                                                }

                                                /// Sets error metadata
                                                pub fn set_meta(&mut self, meta: std::option::Option<::aws_smithy_types::error::ErrorMetadata>) -> &mut Self {
                                                    self.meta = meta;
                                                    self
                                                }
    /// Consumes the builder and constructs a [`WorkspaceLockConflict`](crate::types::error::WorkspaceLockConflict).
    /// This method will fail if any of the following fields are not set:
    /// - [`message`](crate::types::error::builders::WorkspaceLockConflictBuilder::message)
    /// - [`lock`](crate::types::error::builders::WorkspaceLockConflictBuilder::lock)
    pub fn build(self) -> ::std::result::Result<crate::types::error::WorkspaceLockConflict, ::aws_smithy_types::error::operation::BuildError> {
        ::std::result::Result::Ok(
            crate::types::error::WorkspaceLockConflict {
                message: self.message
                    .ok_or_else(||
                        ::aws_smithy_types::error::operation::BuildError::missing_field("message", "message was not specified but it is required when building WorkspaceLockConflict")
                    )?
                ,
                lock: self.lock
                    .ok_or_else(||
                        ::aws_smithy_types::error::operation::BuildError::missing_field("lock", "lock was not specified but it is required when building WorkspaceLockConflict")
                    )?
                ,
                meta: self.meta.unwrap_or_default(),
            }
        )
    }
}

