name: Create release tags

permissions:
    contents: write

on: workflow_dispatch

concurrency:
    group: ${{ github.workflow }}-${{ github.ref }}
    cancel-in-progress: true

jobs:
    tag-release:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout repository
              uses: actions/checkout@v4
              with:
                  fetch-depth: 0
                  token: ${{ secrets.SUPERPOSITION_TOKEN }}

            - name: Install Rust
              uses: dtolnay/rust-toolchain@master
              with:
                  toolchain: 1.78.0
                  targets: wasm32-unknown-unknown
                  components: rustfmt, clippy

            - name: install cargo-edit to perform set-version
              uses: baptiste0928/cargo-install@v2.2.0
              with:
                  crate: cargo-edit
                  version: "0.13.0"

            - name: install cocogitto
              uses: baptiste0928/cargo-install@v2.2.0
              with:
                  crate: cocogitto
                  version: "6.2.0"

            - name: Semver release
              shell: bash
              run: |
                  git config user.email "super_bot@juspay.in"
                  git config user.name "Superposition Bot"
                  cog bump --auto --skip-ci-override "[skip ci]"

            - name: Push code to main
              shell: bash
              run: |
                  git push origin main
                  git push origin --tags
