name: Create superposition example docker image

on: workflow_dispatch

concurrency:
    group: ${{ github.workflow }}-${{ github.ref }}
    cancel-in-progress: true

jobs:
    docker:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout repository
              uses: actions/checkout@v4
              with:
                  ref: "demo"
                  fetch-depth: 0
                  token: ${{ secrets.SUPERPOSITION_TOKEN }}

            - name: Set up QEMU
              uses: docker/setup-qemu-action@v3

            - name: Set up Docker Buildx
              uses: docker/setup-buildx-action@v3

            - name: Get latest tag
              id: git_tag
              shell: bash
              run: |
                docker_tag=`git tag -l --sort=-creatordate | grep "^v" | head -n 1 | sed 's/^v//'`
                echo "docker_tag=$docker_tag" >> $GITHUB_OUTPUT

            - name: Login to Docker Hub
              uses: docker/login-action@v3
              with:
                  username: ${{ secrets.DOCKERHUB_USERNAME }}
                  password: ${{ secrets.DOCKERHUB_TOKEN }}

            - name: Build and push example image
              uses: docker/build-push-action@v6
              with:
                  push: true
                  context: .
                  platforms: linux/amd64
                  file: ./example.Dockerfile
                  tags: datron1/superposition-demo-app:demo-${{ steps.git_tag.outputs.docker_tag }}
