name: "CI Nix"
on:
  push:
    branches:
      - main
  pull_request:
jobs:
  checks:
    runs-on: ${{ matrix.system }}
    permissions:
      contents: read
    strategy:
      matrix:
        system: [ x86_64-linux ]
    steps:
      - uses: actions/checkout@v4
      - run: om ci run --extra-access-tokens ${{ secrets.GITHUB_TOKEN }} --systems "${{ matrix.system }}"
