name: Create a superposition stable release

on: workflow_dispatch

concurrency:
    group: ${{ github.workflow }}-${{ github.ref }}
    cancel-in-progress: true

jobs:
    tag-release:
        runs-on: ubuntu-latest
        permissions:
            contents: write
            id-token: write
        if: github.ref == 'refs/heads/main'
        outputs:
            version: ${{ steps.git_tag.outputs.version }}
            updated_ref: ${{ steps.push_main.outputs.updated_ref }}
        steps:
            - name: Checkout repository
              uses: actions/checkout@v4
              with:
                  fetch-depth: 0
                  token: ${{ secrets.SUPERPOSITION_TOKEN }}

            - name: Install Rust
              uses: dtolnay/rust-toolchain@master
              with:
                  toolchain: 1.90.0
                  targets: wasm32-unknown-unknown
                  components: rustfmt, clippy

            - name: install cargo-edit to perform set-version
              uses: baptiste0928/cargo-install@v2.2.0
              with:
                  crate: cargo-edit
                  version: "0.13.6"

            - name: install cocogitto
              uses: baptiste0928/cargo-install@v2.2.0
              with:
                  crate: cocogitto
                  version: "6.2.0"

            - name: Semver release
              shell: bash
              run: |
                  git config user.email "super_bot@juspay.in"
                  git config user.name "Superposition Bot"
                  cog bump --auto --skip-ci-override "[skip ci]"

            - name: Set latest tag
              id: git_tag
              shell: bash
              run: |
                  version=`git tag -l --sort=-creatordate | grep -E '^v[0-9]+\.[0-9]+\.[0-9]+$' | head -n 1 | sed 's/^v//'`
                  echo "version=$version" >> $GITHUB_OUTPUT

            - name: Set the tag version to all crates
              run: |
                  cargo set-version --workspace ${{ steps.git_tag.outputs.version }}
                  cargo upgrade --package superposition_types@${{ steps.git_tag.outputs.version }}
                  cargo upgrade --package superposition_derives@${{ steps.git_tag.outputs.version }}
                  cargo upgrade --package superposition_macros@${{ steps.git_tag.outputs.version }}
                  cargo upgrade --package superposition_core@${{ steps.git_tag.outputs.version }}
                  cargo upgrade --package superposition_provider@${{ steps.git_tag.outputs.version }}
                  cargo upgrade --package superposition_sdk@${{ steps.git_tag.outputs.version }}
                  cargo upgrade --package service_utils@${{ steps.git_tag.outputs.version }}
                  sed -i "s/superposition: \"[0-9]\+\.[0-9]\+\.[0-9]\+\"/superposition: \"${{ steps.git_tag.outputs.version }}\"/" docs/src/constants/versions.js
                  git add .
                  git commit --amend --no-edit

            - name: install yq
              run: |
                  mkdir -p ${{ github.workspace }}/bin
                  wget -qO ${{ github.workspace }}/bin/yq https://github.com/mikefarah/yq/releases/download/v4.44.2/yq_linux_amd64
                  chmod +x ${{ github.workspace }}/bin/yq
                  echo "${{ github.workspace }}/bin" >> $GITHUB_PATH

            - name: Update Helm chart appVersion
              run: |
                  yq eval ".appVersion = \"${{ steps.git_tag.outputs.version }}\"" -i helm/Chart.yaml
                  git add helm/Chart.yaml
                  git commit --amend --no-edit

            - name: Push code to main
              id: push_main
              shell: bash
              run: |
                  git pull --rebase origin main
                  git push origin main
                  git push origin --tags
                  echo "updated_ref=$(git rev-parse HEAD)" >> $GITHUB_OUTPUT

    build-docker-images:
        needs: tag-release
        if: github.ref == 'refs/heads/main'
        permissions:
            contents: read
            packages: write
        uses: ./.github/workflows/docker_images_common.yaml
        with:
            version: ${{ needs.tag-release.outputs.version }}
            alias_tag: latest
        secrets: inherit

    build-language-artifacts:
        needs: tag-release
        if: github.ref == 'refs/heads/main'
        permissions:
            contents: write
            id-token: write
        uses: ./.github/workflows/language_artifacts_common.yaml
        with:
            version: ${{ needs.tag-release.outputs.version }}
            ref: ${{ needs.tag-release.outputs.updated_ref }}
            release_tag: v${{ needs.tag-release.outputs.version }}
            python_version: ${{ needs.tag-release.outputs.version }}
            run_java: true
            run_python: true
            run_js: true
            run_rust_crates: true
            publish_java: true
            publish_python: true
            publish_js: true
            publish_rust_crates: true
            npm_dist_tag: latest
            create_github_release: true
            release_draft: true
        secrets: inherit
