[project]
name = "openfeature_provider_python"
version = "0.0.1"
description = "openfeature_provider_python"
readme = "README.md"
requires-python = ">=3.12"
keywords = ["openfeature", "openfeature_provider_python"]
license = {text = "Apache-2.0"}

dependencies = [
    "smithy_core",
    "superposition_python_sdk",
    "json",
    "asyncio"
]
